Fix PaStA bugs and minor fixes
se-sic/coronet pull request #189
Opened 2020-12-01 19:43 UTC by hechtlC

### Prerequisites

- [X] I adhere to the coding conventions (described [here](https://github.com/se-passau/coronet/blob/master/CONTRIBUTING.md)) in my code.
- [X] I have updated the copyright headers of the files I have modified.
- [X] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [X] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](https://github.com/se-passau/coronet/blob/master/NEWS.md) appropriately.
- [X] The pull request is opened against the branch `dev`.

### Description

There are a couple of problems with the PaStA data in coronet which are fixed with this pull request. One problem is that the output of PaStA has a new, slightly different format. The file which contains the data is now called 'patch-groups' and at the end of the file there are new lines with all the commit hashes of a project that did not get matched in the following format: '=> hash'.

Another problem is that when merging the PaStA data to the mail and commit data, the revision set ids get duplicated in some cases. And there are cases where message ids or commit hashes that appear in the PaStA data do not appear in the mail and commit data. These problems are fixed with this pull request as well.

### Changelog

This is still missing and will be added both here and in the NEWS.md file once the pull request is reviewed.

2020-12-01 20:00 UTC, bockthom commented on util-data.R
> +                pasta.commit.hashes = unlist(private$pasta[["commit.hash"]])
Maybe you can do the `!is.na` check already for `pasta.commit.hashes`. Then we have fewer elements for doing the `%in%` checks and you can remove this NA check below for `commit.hashes.to.eliminate`.

2020-12-01 20:01 UTC, bockthom commented on util-data.R
> +                rows.to.remove = unlist(private$pasta["commit.hash"]) %in% commit.hashes.to.eliminate
Please use the square bracket notation when accessing `pasta[["commit.hash"]]`.

2020-12-01 20:11 UTC, bockthom requested changes

2020-12-01 20:11 UTC, bockthom commented on util-data.R
> +                              To clean this up you can call the function cleanup.pasta().")
Please use single quotation marks around `'cleanup.pasta.data()'`. (See also comment below)

2020-12-01 20:11 UTC, bockthom commented on util-data.R
> +        cleanup.pasta = function() {
To be consistent with the update function, we should call this function `cleanup.pasta.data`.

And is there a reason why you use three lines for the function documentation? I bet that two lines would be enough as you don't use the maximally allowed length of 120 characters per line :wink

2020-12-01 20:15 UTC, bockthom commented
Somehow my overall review comment disappeared. I am sorry for that. Here is it again:

Thanks for this nice little changes @hechtlC. There are four minor issues which need to be fixed before we merge this PR.
In addition to that, please adjust the formatting of your commit messages as they violate our conventions of commit messages: There has to be a line break after 80 characters when writing detailed explanations in commit messages.
As you have to rebase your commits for that, you can also incorporate all the four other changes on the fly during rebasing :wink:

2020-12-01 20:18 UTC, bockthom commented on util-read.R
> +#' Read and parse the PaStA data from the 'patch-groups' file.
Shouldn't this be also changed in the corresponding file name in our test suite?

2020-12-02 08:40 UTC, hechtlC commented on util-data.R
> +                pasta.commit.hashes = unlist(private$pasta[["commit.hash"]])
I have just tried this and for some reason this does not work as intended. So I will just keep it the way it is.

2020-12-02 09:17 UTC, bockthom commented on util-data.R
> +                pasta.commit.hashes = unlist(private$pasta[["commit.hash"]])
Ok, then let's keep this as is (and save it for future improvements :wink:)

2020-12-02 12:01 UTC, hechtlC commented on util-data.R
> +                rows.to.remove = unlist(private$pasta["commit.hash"]) %in% commit.hashes.to.eliminate
Done. Thanks for catching that.

2020-12-02 12:02 UTC, hechtlC commented on util-data.R
> +                              To clean this up you can call the function cleanup.pasta().")
Done.

2020-12-02 12:02 UTC, hechtlC commented on util-data.R
> +        cleanup.pasta = function() {
Done.

2020-12-02 12:49 UTC, bockthom commented on util-data.R
> +                private$pasta = private$pasta[!rows.to.remove,]
Here a space is missing after the comma. Sorry for not saying this earlier.

2020-12-02 12:51 UTC, bockthom commented
Please don't forget to add the new bug fix regarding patch-stack filtering (d9fcd19) to the changelog file.

2020-12-02 13:07 UTC, hechtlC commented on util-data.R
> +                private$pasta = private$pasta[!rows.to.remove,]
Done.

2020-12-02 15:20 UTC, bockthom approved these changes
Thanks for all the PaStA-related fixes @hechtlC , looks good!
So I will merge right away.

2020-12-02 15:22 UTC, merged