Add commit message merge functionality
se-sic/coronet pull request #193
Opened 2021-01-07 20:34 UTC by nlschn

### Prerequisites

- [x] I adhere to the coding conventions (described [here](https://github.com/se-passau/coronet/blob/master/CONTRIBUTING.md)) in my code.
- [x] I have updated the copyright headers of the files I have modified.
- [x] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [x] I have put signed-off tags in *all* commits.
- [x] I have updated the changelog file [NEWS.md](https://github.com/se-passau/coronet/blob/master/NEWS.md) appropriately.
- [x] The pull request is opened against the branch `dev`.

### Description
[Now from mydev branch]
In order to address issue #180 this PR adds functionality to read and process commit message data in "commitMessages.list" files. The first non-white-space line of the message is considered the title, the rest the body of the commit message.
This functionality can be found in "util-read.R"

The ability to merge the commit messages to the commit data is implemented in "set.commits" in "util-data.R" and a new attribute "commit.messages" has been added to "proj.conf" to control what data shall be merged.

For each new functionality tests are provided.

### Changelog

- Add functionality to read and process commit messages in order to merge them to the commit data (See issue #180). Three values are available for the new attribute `commit.messages` in `proj.conf`: 
  1. `none` is the default value and does not change the previous behavior of `proj.data$set.commits`.
  2. `title` merges the commit message titles (i.e. the first non white space line of a commit message) to the commit data. This gives the data frame an additional column `title`.
  3. `messages` merges both titles and message bodies to the commit data frame. This adds two new columns `title` and `message.body`.

2021-01-10 12:18 UTC, clhunsen requested changes
Hi @nlschn!

Thank you very much for your PR! :grinning::+1: And congrats for opening your (kind of) first one for coronet! :partying_face: Your work integrates a feature that @bockthom requested for a long time. He is definitely very happy about this! :grin: 

I added some comments to your changes, with the main goal to improve maintainability:
- There is an implementation error in the method `ProjectData$get.commit.messages`. I highlighted the corresponding comment with the symbol :bug:.
- You access and modify data.frames using indices in several places – instead of using columns names. This may cause problems when functionality changes in the future. You should always avoid using indices in any case if possible (*at least*, outside the file `util-read.R`).
- The algorithm of post-processing commit messages (after they have initially been read from disk) can be tweaked to speed things up and make the implementation more comprehensible.
- You have added a configuration option to the class `ProjectConf`, but you have not updated the README file accordingly. I added a corresponding comment to your update of the file `NEWS.md`.

Your additions to coronet are a very nice piece of work! Keep it up! :+1: 

If you have any questions regarding my comments or anything else, please do not hesitate to ask. :slightly_smiling_face: 

------------

By the way, if you got an e-mail indicating a single new and, in the end, non-existing comment on PR #192: Sorry for this! I accidentally clicked the wrong button when starting to review the PR and, then, deleted the comment right away. :man_facepalming:

2021-01-13 13:55 UTC, nlschn commented on util-read.R
> +    "hash", "title", "message.body"
No, there is not. I will change it to message, this is shorter.

2021-01-13 14:41 UTC, nlschn commented on util-data.R
> +        get.commit.messages = function() {
Not that I am aware of it.

2021-01-13 14:52 UTC, nlschn commented on util-read.R
> +    message.split = strsplit(commit.message.data.unprocessed[[3]], COMMIT.MESSAGE.LINE.SEP.CODEFACE)
If I would add names beforehand, I would need another constant with the column names because, as you say, the unprocessed data has only 3 columns. Or I take the vector I already have and use only 3 components.

2021-01-13 15:02 UTC, nlschn commented on util-read.R
> +    message.split = strsplit(commit.message.data.unprocessed[[3]], COMMIT.MESSAGE.LINE.SEP.CODEFACE)
I just went with the second approach.

Also to answer your last question, yes I do exactly this.

2021-01-15 11:10 UTC, bockthom commented on README.md
> +  - [Table of contents](#table-of-contents)
Just a quick question: What was the intention behind changing the table of contents (i.e., replacing `-` by `*` and adding `coronet - The network library`, the `Table of conents` itself, and others to the table of conents) ? I guess you just have used an auto-formatter which automatically added the missing sections to the table of contents. On the one hand I like it, as it seems that previously missing sections are now part of the table of contents (e.g., Contributing). One the other hand, it is kind of weird and counter-intuitive that the initial section and the table of contents appear in the table of contents. So, maybe you can adjust the table of contents to prevent the appearance of the these to section. I don't know if there is an automatic way to ignore them or whether manually removing them is the only way to fix this...

2021-01-15 12:44 UTC, nlschn commented on README.md
> +  - [Table of contents](#table-of-contents)
It could be that VS Code has added this whole stuff without me noticing... But glad you like (parts of) it anyway 😇 I will look into how to fix this last issue.

2021-01-15 13:14 UTC, bockthom requested changes
Thanks @nlschn, your implementation looks really good. Sorry for my late review, I have hoped to achieve that earlier. Anyway, I just have found a few minor issues addressing consistency. So, please have a look at them (and please don't overstate the number of my comments, most of my comments go into the same direction). Don't hesitate to ask if something is unclear to you.

Also thanks to @clhunsen for your review, you already have pointed out the most important issues.

2021-01-15 13:14 UTC, bockthom commented on util-read.R
> +    ## prepare the message.split-object so that it contains a two-element
the 'message.split' object

In addition, removing the line break would make the comment easier to read. Remember that you are allowed to have up to 120 characters in one line :wink:

2021-01-15 13:14 UTC, bockthom commented on util-read.R
> +    commit.message.data[["commit.id"]] = sprintf("<commit-%s>", commit.message.data[["commit.id"]])
I am not sure, but if I remember correctly, we do this in a similar way for the commit data. Maybe would should add some kind of helper function or use constants for this to avoid code duplication (i.e., to only have one place where to adjust this instead of two).

2021-01-15 13:14 UTC, bockthom commented on util-read.R
> +#' names and column datatypes defined in \code{COMMIT.MESSAGE.LIST.COLUMNS} and \code{COMMIT.MESSAGE.LIST.DATA.TYPES}, respectively.
Please respect a line length of 120 characters (for implementation files). This may be not the case for previously existing parts of this file, but should respect that, at least, when adding new content :smile:

2021-01-15 13:23 UTC, nlschn commented on tests/test-data.R
> +    # we do not care for their order in the test
I have totally missed the hidden comments, but I found them now.

2021-01-15 15:44 UTC, nlschn commented on util-data.R
> +        get.commit.messages = function() {
Implemented one because of [this comment](https://github.com/se-sic/coronet/pull/193#discussion_r558275858)

2021-01-20 14:27 UTC, bockthom requested changes

2021-01-20 14:27 UTC, bockthom commented on util-conf.R
> +## Copyright 2020-21 by Niklas Schneider <s8nlschn@stud.uni-saarland.de>
2020-2021

2021-01-20 14:27 UTC, bockthom commented on README.md
> +- `data.table`: For faster data processing.
Please remove the full stop for consistency reasons, as we don't have a full stop for the remaining package descriptions.

2021-01-21 13:34 UTC, clhunsen commented
I have some further comments but will not have time before tonight, at the earliest, to write them down.

To mention one major point right now: I would like to remove the new dependency 'data.table' to keep the number of dependencies as minimal as possible. We can use `lapply`, data.frames, and `plyr::rbind.fill` to avoid the new dependency.

2021-01-21 13:39 UTC, hechtlC commented
> To mention one major point right now: I would like to remove the new dependency 'data.table' to keep the number of dependencies as minimal as possible. We can use `lapply`, data.frames, and `plyr::rbind.fill` to avoid the new dependency.

Actually, I would like to incorporate the 'data.table' package in the whole project. This is basically just an extension for 'data.frame' but has a way better performance. The internet even says that it is faster than 'plyr' and 'dplyr'.

2021-01-21 20:33 UTC, clhunsen commented
> > To mention one major point right now: I would like to remove the new dependency 'data.table' to keep the number of dependencies as minimal as possible. We can use `lapply`, data.frames, and `plyr::rbind.fill` to avoid the new dependency.
> 
> Actually, I would like to incorporate the 'data.table' package in the whole project. This is basically just an extension for 'data.frame' but has a way better performance. The internet even says that it is faster than 'plyr' and 'dplyr'.
> 
> Edit: Just one link that proves that (out of many more): [Link](https://www.analyticsvidhya.com/blog/2016/05/data-table-data-frame-work-large-data-sets/)

Ah, I confused `data.table` with `tibble`, which was proposed as a new dependency some time ago. My fault, sorry. :man_facepalming: Nevertheless, the code that is using the new dependency can be optimized by using an `lapply` statement. :slightly_smiling_face:

2021-01-21 21:09 UTC, clhunsen requested changes
Thanks a lot, @nlschn! We are nearing completion. :smiley::+1:

For me, there is just one major point of discussion left: The for-loop in the function `read.commit.messages` and the surrounding code seems to be quite sub-optimal, in my opinion. Using an `lapply` statement and well-designed return values can improve the speed, comprehensibility, and, I guess, maintainability of this code. Please have a look on my comments. I am really interested what you all think.

2021-01-21 21:24 UTC, bockthom commented on util-data.R
> +                    commit.messages = commit.messages[ , colnames(commit.messages) != "message"]
Nevertheless, using the comma looks more intuitive to me, as it can be clearly seen that we keep all the rows and select some columns. Without the comma, it is not that obvious what's happening to the columns and rows. Hence, I would like to keep the comma in such cases.

2021-01-21 21:25 UTC, bockthom commented on util-data.R
> +            update.commit.message.data()
Good point!

2021-01-21 21:51 UTC, bockthom commented on util-read.R
> +    message.split = data.table::rbindlist(lapply(message.split, as.data.frame.list))
Thanks for your example @clhunsen. We already had some discussions about this part of the pull request yesterday in our weekly meeting. At the first glance, I didn't see any big performance improvements here as the `for` loop just updates some values of an existing data frame. However, seeing your code example, I think it is worth to replace the loop by an `lapply` as we then can get rid of the `lapply` containing the `as.data.frame.list` call. So, we just have one "loop" (`lapply`) instead of two subsequent loops (`for` followed by `lapply`). Hence, I like your example (except for the last two lines of your example––instead, I just would go with the already present data.frame creation in lines 510-513 and update them accordingly).
@hechtlC Would you agree with that?

2021-01-21 22:06 UTC, hechtlC commented on util-read.R
> +    message.split = data.table::rbindlist(lapply(message.split, as.data.frame.list))
Yes I agree. But thanks for the example @clhunsen :)

2021-01-21 22:10 UTC, hechtlC commented
> Ah, I confused `data.table` with `tibble`, which was proposed as a new dependency some time ago. My fault, sorry. man_facepalming Nevertheless, the code that is using the new dependency can be optimized by using an `lapply` statement. slightly_smiling_face

Ok then we are all good here :smile:  . I will open an issue in the coming days on the conversion from 'data.frame' to 'data.table'. I think that this is an enhancement we should make as it can potentially improve the performance for large data sets.

2021-01-21 22:34 UTC, bockthom commented
By sheer chance, while using coronet to work on something else which is not related to this PR a few minutes ago,––thanks to our verbose log messages––I spotted another function which needs to be updated regarding the commit message data, which I completely wasn't aware of any more:

The function `split.data.time.based` in the `util-split.R` module deals with all the additional data sources during data splitting. That is, we need to initialize the commit-message data on the RangeData objects, as we do for the other additional data sources here: https://github.com/se-sic/coronet/blob/a7f4123dcb86a7a0f76adf791b66a7d9c24f7647/util-split.R#L71-L75
@nlschn Could you please add the commit-messages data there? Just call the getter as for the remaining data sources. When changing this, I guess that also all the splitting tests ([`test-split.R`](https://github.com/se-sic/coronet/blob/a7f4123dcb86a7a0f76adf791b66a7d9c24f7647/tests/test-split.R) and [`test-split-sliding-window.R`](https://github.com/se-sic/coronet/blob/a7f4123dcb86a7a0f76adf791b66a7d9c24f7647/tests/test-split-sliding-window.R)) need to be updated, unfortunately. However, as we don't use the commit messages in these tests, it should be enough to just copy the corresponding behavior of the synchronicity data or pasta data in these tests. Sorry for the additional efforts on that, I had completely forgotten about that.

Nonetheless, I am not sure if we need further adjustments regarding the commit messages of the split data. I hope not. @hechtlC Do you know what happens to the PaStA data while splitting? The additional columns in the commit data should be automatically correct due to the nature of data splitting, but the PaStA data remains as before, i.e., containing all the information which was present before splitting. Is this correct? If so, everything is fine also with the commit messages. If not, that is, if the PaStA data is updated, then we would need to do that also for the commit messages.

2021-01-25 10:12 UTC, bockthom commented on util-read.R
> +        ## set title and message empty in case there was on actual commit message or it was consisting of spaces only
"on" --> "no"

2021-01-25 10:12 UTC, bockthom commented on util-data.R
> +                if (is.null(private$scommit.messages)) {
**`s`**`commit.message` will always be null, as it does not exist :wink:

2021-01-25 22:09 UTC, bockthom commented on tests/test-split-sliding-window.R
> +#
Please keep the `##` for comments here, as before, to stay consistent.

2021-01-30 11:10 UTC, nlschn commented
I have tested the `cleanup.synchronicity` function manually on busybox data with the given parameters (`artifact=file` and `synchronicity=5`) as suggested by @bockthom and it seems to work fine.

2021-01-30 12:33 UTC, JoJoDeveloping commented
> Except for R-3.3, there is the same error as in #194. 😢

Is it possible that this fail is a problem with the pipeline in general? Does it also appear if you re-run the pipeline for `master` or `dev`? @bockthom

2021-01-30 13:13 UTC, bockthom commented
> > Except for R-3.3, there is the same error as in #194. cry
> 
> Is it possible that this fail is a problem with the pipeline in general? Does it also appear if you re-run the pipeline for `master` or `dev`? @bockthom

Yes, this problem will occur everywhere where package `sqldf` is installed on R 3.3. I had a quick look at the test logs and what I can see there is that `sqldf` cannot be installed on R 3.3 anymore as there might be some dependencies of `sqldf` not be available anymore. I will have a closer look at this tonight or tomorrow, not sure if there really is a solution for that problem, but I will check.
@nlschn @JoJoDeveloping just ignore the failing pipeline on R 3.3, it is not related to your PRs and you don't have to deal with that :wink:

2021-01-31 13:47 UTC, bockthom commented
> Yes, this problem will occur everywhere where package `sqldf` is installed on R 3.3. I had a quick look at the test logs and what I can see there is that `sqldf` cannot be installed on R 3.3 anymore as there might be some dependencies of `sqldf` not be available anymore. I will have a closer look at this tonight or tomorrow, not sure if there really is a solution for that problem, but I will check.

After spending more than two hours an investigating why the pipeline fails for R 3.3, eventually, I was able to find out what is going wrong there:
Package `sqldf` imports package `RSQLite`, which in turn imports package `memoise`. Last Tuesday (2021-01-26), a new version of package `memoise` was released (which explains why the pipeline still ran successfully at the beginning of last week). The new release of `memoise` has introduced a new dependency to package `cachem` (this dependency was not present before). Package `cachem` imports package `fastmap` (which is also new in our dependency tree). And now we are close to the failing builds: The installation and compilation of package `fastmap` ends up in an "internal compiler error: Segmentation fault" for R 3.3.3. There is no segmentation fault for more recent R versions (>= 3.4), and also no segmentation fault for the even earlier versions R 3.3.1 and R 3.3.2. So only R 3.3.3. is the problem. I will open a bug report on `fastmap` soon––but I am not sure how they will react on my bug report, as R 3.3.3 is already quite outdated and I am not sure if they are willing to debug old R versions. Even if they will fix this bug, it will take some time until a new release will be available on CRAN. So, for the moment (i.e., current and future PRs on coronet), we have only the following two options: Either completely ignore the build fail on R 3.3 and hope the problem to be fixed soon, or temporarily replace R 3.3.3 by R 3.3.2 in our pipeline to get the green check mark again :smile:

2021-01-31 15:17 UTC, bockthom reviewed
All the changes in this PR look good already. I have only found some minor issues. And this time I really hope that we can merge the PR afterwards...

2021-01-31 21:33 UTC, clhunsen submitted a review, later dismissed
This PR looks pretty close to merging! Nice work, @nlschn! :slightly_smiling_face: I only have one tiny bug that needs to be fixed and one (optional) suggestion for improving code comprehensibility. When the bug is fixed and @bockthom's comments are addressed, this PR is ready to be merged. :grinning:

2021-02-01 08:42 UTC, bockthom commented on util-read.R
> +                                     message.split.df[["message"]]) # message
My bad! I just wanted to keep the assignment as it was to clearly see all the columns of the data frame. However, I did not recognize that the first two columns just replace existing columns in the already present data frame; I thought that this was a different data frame. That was the reason why I had told @nlschn to keep the assignment as it was before. But now as I see that this actually is the same data frame, we should go with your suggestion, as it may lead to a better performance in both memory and time. Sorry for the confusion.

2021-02-01 09:06 UTC, bockthom reviewed
Just spotted two other things:

For the first one: We have a warning notifying the user about cleaning up the PaStA data, which we should also add for the synchronicity data. Could you please add the following warning in line 450 of `util-data.R`, in `update.synchronicity.data` (in a similary way as in `update.pasta.data`): 

```R
logging::logwarn("There might be synchronicity data that does not appear in the commit data.
                  To clean this up you can call the function 'cleanup.synchronicity.data()'.")
```
And also in a similar way for commit messages.

The second one is just an update of the NEWS.md, as we have added these cleanup functions, see comment below.

(Now I am finished with my review. I won't look at the existing parts of this PR any more unless someone else spots any other issues.)

2021-02-01 09:06 UTC, bockthom commented on NEWS.md
> +
Could you please add a second bullet point:
´´´Add functions `cleanup.commit.message.data` and `cleanup.synchronicity.data` to remove commit hashes that are not any more present in the commit data from the commit-message data or synchronicity data (...)```

2021-02-01 11:45 UTC, bockthom commented
> After spending more than two hours on investigating why the pipeline fails for R 3.3, eventually, I was able to find out what is going wrong there:

Just for documentation reasons: The discussion about the failing pipeline for R 3.3.3 will be continued here: https://github.com/se-sic/coronet/issues/161#issuecomment-770795753

2021-02-01 18:26 UTC, bockthom approved these changes

2021-02-01 19:59 UTC, clhunsen submitted a review, later dismissed
Nice work! :partying_face::+1:

2021-02-03 14:06 UTC, bockthom approved these changes
Good work @nlschn, thanks for your endurance.

As everyone has approved this PR and also the test pipeline succeeds again as of the pipeline fix, I will merge right away.

2021-02-03 14:09 UTC, merged