Mail count
se-sic/coronet pull request #194
Opened 2021-01-27 11:50 UTC by JoJoDeveloping

### Prerequisites

- [X] I adhere to the coding conventions (described [here](https://github.com/se-passau/coronet/blob/master/CONTRIBUTING.md)) in my code.
- [X] I have updated the copyright headers of the files I have modified.
- [X] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [X] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](https://github.com/se-passau/coronet/blob/master/NEWS.md) appropriately.
- [ ] The pull request is opened against the branch `dev`. (not checked since `dev` is 3 years behind at this point)

### Description

Adds methods that add relevant attributes to implement the changes noted in #188 
These are per-author and include:
* issue count
* issue comment count
* mail count
* mail thread count
* PR count
* PR comment count

The definition of when an author is related to an issue are tentative and should be looked over. In particular we have:
* An issue is counted for someone if they participated in that issue in any way (i.e. labeling, commenting, opening/closing, mentioning)
* An issue is counted for someone if they comment in it
* A PR is counted for the person opening it
* A PR is counted for a person when they comment in it (this includes the initial author, mostly, as they write the initial description)
* A PR is counted for a person when they participate it in any way (i.e. labeling, commenting, opening/closing, mentioning, _adding comments to it_)

2021-01-30 12:31 UTC, JoJoDeveloping commented
I don't know why CI fails. I can build it locally and run the tests just fine. The CI also only fails for version 3.3 with an error indicating sqldf is missing (?).

2021-02-01 15:56 UTC, JoJoDeveloping commented on util-core-peripheral.R
> +                                 GROUP BY `",grouping.keys.formatted,"` ORDER BY `freq` DESC, `",grouping.keys.formatted,"`",sep="")
Well, yes, but actually no since `ASC` is the default ordering used.

2021-02-02 05:17 UTC, JoJoDeveloping commented on util-core-peripheral.R
> +    logging::logdebug("get.author.mail.thread.count: finished")
Yes, the reason was that I did not want to make the helper function too fancy. Adding this either requires specifying part of the SQL query as a string, or at least two args (does R have option types?). Making the function too general means one has to always look up what it does, which makes things harder.

2021-02-02 14:01 UTC, hechtlC requested changes
Nice work @JoJoDeveloping . I found a couple of additional things which were not mentioned in @bockthom's review.

2021-02-02 14:02 UTC, hechtlC commented on util-core-peripheral.R
> +get.author.issues.commented.in.count = function(proj.data) {
I was not involved in this as far as I can remember (I might be wrong though).

2021-02-07 12:47 UTC, clhunsen reviewed
Thanks for your PR, @JoJoDeveloping! :smiley: Keep up the good work!

This is _not_ a full review as I have not looked into the implementation in detail. I just want to share my thoughts on some things that I spotted while scanning the comments of @bockthom and @hechtlC. :wink:

2021-02-07 12:47 UTC, clhunsen commented on util-core-peripheral.R
> +#' @param distrinctize Whether to remove duplicates
Sounds like a typo for me. I guess this verb should come from `distinct` or `distinctive` (so, without an `r`!). In the end and for me, `remove.duplicates` or just `distinct` seem to be better choices.

2021-02-07 12:47 UTC, clhunsen commented on util-core-peripheral.R
> +        logging::logdebug(paste(name, ": starting.", sep=""))
The functions `logging::log*` have `sprintf` built-in (see [here](https://github.com/mfrasca/r-logging/blob/master/pkg/R/utils.R#L165) and also look for `logging-entrypoints` in [the documentation](https://cran.r-project.org/web/packages/logging/logging.pdf), parameter `...` in particular). Thus, you could use the following rightaway:
```R
logging::logdebug("%s: starting.", name)
```

2021-02-07 12:47 UTC, clhunsen commented on util-core-peripheral.R
> +    logging::logdebug(paste("get.author.mail.thread.count: running SQL ", stmt,sep=""))
... or use the built-in `sprintf` of `logging::log*` functions rightaway (see my comment above).

2021-02-07 12:47 UTC, clhunsen commented on util-core-peripheral.R
> +    for (rnum in 1:nrow(df)) {
Please use `seq_len(nrow(df))`. If the data.frame has no rows, `1:0` yields `c(1, 0)` and, thus, wrong computations. My code snippet yields `integer(0)` and no iteration in the loop at all.

This holds also for other instances of this pattern!

2021-02-07 12:47 UTC, clhunsen commented on util-data.R
> +        get.issues.unfiltered = function() {
Please consider [my comment](https://github.com/se-sic/coronet/issues/185#issuecomment-774655806) on Issue #185 in your discussions.

Also, shouldn't the function `ProjectData$get.issues` rely on `ProjectData$get.issues.unfiltered` to avoid code duplication and potential problems when extending the functionality of these functions?

2021-02-07 17:33 UTC, JoJoDeveloping commented on tests/codeface-data/results/testing/test_feature/feature/issues-github.list
> +"1";"Example pull request 1";"[""pull request""]";"closed";"[]";"2013-05-13 02:46:44";"2013-09-05 14:48:10";"[]";"created";"Thomas";"thomas@example.org";"2016-07-12 15:59:25";"open";"[]"
These pull requests are the reason tests are failing. Unfortunately, I do not understand what some of the tests are even testing. We might need to discuss this next meeting.

2021-03-11 15:06 UTC, hechtlC requested changes
First of all thanks for the good work on this enhancement @JoJoDeveloping. 

There are some problems here (mostly documentation). These will need to be fixed. Please also check whether there are more than one occurrence of the documentation problems as I have not marked every one.

Please also don't forget to address the old comments.

2021-03-11 15:06 UTC, hechtlC commented on util-networks-covariates.R
> +#' Add issues-count attribute based on the number of issues created in where the person represented by the vertex is the author.
I guess the 'in' can be removed here.

2021-03-11 15:06 UTC, hechtlC commented on util-networks-covariates.R
> +        default.value, function(data) {return (get.author.issues.created.count(data, type = issue.type))}, "author.name"
No space between return and the (

2021-03-11 15:06 UTC, hechtlC commented on util-split.R
> +## Copyright 2021 by Johannes Hostert <s8johost@stud.uni-saarland.de>
We already talked about this.

2021-03-17 16:47 UTC, bockthom requested changes
Thanks @JoJoDeveloping for working on this PR. I just had a quick view at it and spotted only minor issues. I will do a full pass when all the remaining issues (especially to the test suite) are fixed.

I have already spotted a few issues:

1. This PR contains files which should not be part of it, e.g., `tests/testthat-problems.rds`. Please remove them via rebase, as we don't want such files to show up in the commit history. Please also check if there are other files that should not appear here.
2. There still are some violations of the coding conventions (spacing, indentation, etc.). The individual comments below just indicate some of them. Please also check for similar violations not explicitly mentioned in our reviews.
3. The test data for pull-requests contains unrealistic data. Please adjust events in such a way that they can occur in a real setting, see also my comments below.

Please see also the individual comments below.

2021-03-17 16:47 UTC, bockthom commented on tests/codeface-data/results/testing/test_feature/feature/issues-github.list
> +"1";"Example pull request 1";"[""pull request""]";"closed";"[]";"2016-07-14 13:37:00";"2017-01-01 01:01:01";"[]";"created";"Thomas";"thomas@example.org";"2016-07-12 15:59:25";"open";"[]"
Is there any reason for quoting the id in the first column?

2021-03-17 16:47 UTC, bockthom commented on tests/codeface-data/results/testing/test_feature/feature/issues-github.list
> +"1";"Example pull request 1";"[""pull request""]";"closed";"[]";"2016-07-14 13:37:00";"2017-01-01 01:01:01";"[]";"state_updated";"Thomas";"thomas@example.org";"2016-07-12 15:59:59";"closed";"""open""
Please try to use realistic scenarios. Updating the state from open to closed but having commented events afterwards in which the state is open?
As this are pull requests, it may additionally be helpful to also incorporate traditional PR events, such as "merged" etc. :wink:

2021-03-17 16:47 UTC, bockthom commented on tests/test-networks-covariates.R
> +            networks.and.data[["networks"]], networks.and.data[["project.data"]], aggregation.level = level, issue.type = "pull.requests", name = "pull.request.count"
In such function calls, we should break lines after 120 characters. We only make exceptions when setting test data or expected data, for comprehensibility reasons.

2021-03-17 16:47 UTC, bockthom commented on util-core-peripheral.R
> +#' For example, called with name="commit.count", data.extractor=function(proj.data) {return(proj.data$get.commits.filtered())},
Please also respect our coding conventions within comments, that is, add spaces around `=` etc.
As this actually is code, please use \code{...}. (We do this to achieve automated rendering in typewriter font when we will generate documentation out of this comments in far far future :smile:)

2021-03-17 16:47 UTC, bockthom commented on util-core-peripheral.R
> +#' 5. return a dataframe with cols commiter.name and freq, which contains the number of commits authored by each author
Please add quotation marks around colnames

2021-03-17 16:47 UTC, bockthom commented on util-core-peripheral.R
> +                                 GROUP BY `", grouping.keys.formatted, "` ORDER BY `freq` DESC, `", grouping.keys.formatted, "`")
Here the indentation seems to be broken.

2021-03-17 16:47 UTC, bockthom commented on util-core-peripheral.R
> +        logging::logdebug(paste0(name, ": running SQL ", stmt))
Please omit `paste0` here and use the syntax you also have used two lines below :wink:

2021-03-17 16:47 UTC, bockthom commented on util-core-peripheral.R
> +                df = df[sapply(df[["issue.type"]], function (k) {return ("issue" %in% k)}), c("author.name", "issue.id", "event.name")]
Please don't copy-paste the vector `c("author.name", "issue.id", "event.name")` that often in this function. Just assigning it to variable and reusing the variable will do it :wink: 

In addition, there should be no space between `function` and its parameters.

2021-03-17 16:47 UTC, bockthom commented on util-read.R
> +    # the original date for commit_added events is stored in event.info.2 in any case
Please use quotation marks around "commit_added" and also for column names

2021-03-18 14:53 UTC, bockthom commented on util-core-peripheral.R
> +                df = df[sapply(df[["issue.type"]], function (k) {return ("issue" %in% k)}), c("author.name", "issue.id", "event.name")]
Just to not forget about it: When adding a new file `util-data-misc.R` for the issue-data related and generally usable helper functions, please don't forget to add the new file to the [File/Module overview](https://github.com/se-sic/coronet#filemodule-overview) in the `README.md`.
I would suggest to add the new file directly below `util-data.R` and phrase the description of the new file in a similar way than for `util-networks-misc.R`.

And also please remember that the new file needs to be added to `util-init.R`.

2021-03-24 13:08 UTC, bockthom requested changes
I had a closer look at your pull request and have identified a few more issues. In the NEWS.md, there are still the issues which we have already identified in our past reviews, please have a look at them again.

In addition, please also have a look at the new comments below.

2021-03-26 11:15 UTC, clhunsen reviewed
Thanks for your work on this PR, @JoJoDeveloping! :+1:  Please have a look on my comments, I just wanted to add my two cents on your changes: mostly some things for a good discussion with @bockthom and @hechtlC. :wink:

2021-03-26 11:48 UTC, bockthom commented on util-core-peripheral.R
> +}
Sounds good! I'd support this idea :+1:

2021-03-30 21:40 UTC, JoJoDeveloping commented on util-init.R
> +source("util-data-misc.R")
Which line, directly below what line?

2021-03-31 14:42 UTC, hechtlC requested changes
Thanks again for the nice additions and addressed issues.

I just found a couple more small issues with the PR. Once these are addressed (and also the outstanding ones), I will be fine with merging.

2021-04-13 21:15 UTC, bockthom reviewed
Fortunately, I eventually found the time to have a closer look at the count-related tests of this PR. While comprehending all these tests in detail, I reflected also about some other implementation details. In sum, I really like this PR and all the implementations. Really nice work!

I just spotted a few highly relevant issues which we need to discuss in our next meeting, and also some minor documentation-related issues (as always when performing reviews :wink:).
Please find my detailed comments below. I am looking forward to discussing some of them in our next meeting in detail.

2021-04-13 21:15 UTC, bockthom commented on tests/test-networks-covariates.R
> +    )
Unfortunately, in this test, we only consider mail threads which exactly consist of one single e-mail. So, the test result is exactly the same as for testing mail count. So, I am not convinced that the test really tests for the thread count. Let's think about whether there is an easy solution to test also for e-mail threads having more than one e-mail – without adding new data which would force us to adjust all the data/network tests... Let's discuss about the test data in our next meeting.

2021-04-13 21:15 UTC, bockthom commented on tests/test-networks-covariates.R
> +    )
We should also test for the "all" variant here and also for all the other issue-related test functions here. Should be easy to achieve, as we just need to sum up expected attributes for "issues.only" and "prs.only".

2021-04-13 21:15 UTC, bockthom commented on util-data-misc.R
> +get.author.issue.count = function(proj.data, type = "all") {
Let's talk about the `type` parameter in our next meeting. I just have a few questions here – but nothing to worry about.

2021-04-13 21:15 UTC, bockthom commented on util-data.R
> +        get.issues.filtered = function() {
Just a reminder for the discussion in our next meeting:
For getting filtered commit data, there is an `uncached` function variant.
@hechtlC Should we also add such a function for filtering issues `uncached`, to make both filtering procedures consistent? I am not really sure about that. This is open for discussion.

2021-04-15 00:30 UTC, JoJoDeveloping commented on util-data-misc.R
> +  df = proj.data$get.issues()
1. One really wants to use the unfiltered data, since the usual filters that `.filtered` uses are ones like "only retain `"comment"` events", which would mean that methods like `get.author.issue.creation.count` and related would assing `0` for each author since all issue creation events got filtered.

2021-04-22 12:47 UTC, bockthom requested changes
Yet another review on my part :smiley: 

In the end, I have added way more comments than I wanted to add... but I think that we are close to merging, though, if the comments are adressed.  However, the longer the time span between two subsequent reviews, the higher the probability that I will spot new issues that I have not spotted yet :wink:
Maybe you would like make use of this information when addressing my comments :smile: 
Anyway, please find my detailed comments below. If anything is unclear, don't hesitate to ask.

2021-04-22 12:47 UTC, bockthom commented on util-networks-covariates.R
> +#' @param name The attribute name to add. You might want to change this [default: "issues.count"]
Wrong default value. Should be "issue.count"

2021-04-22 12:47 UTC, bockthom commented on util-networks-covariates.R
> +#' @param name The attribute name to add [default: "issue.count.by.commenting"]
Wrong default value. Should be "issue.commented.count"

2021-04-22 12:47 UTC, bockthom commented on util-networks-covariates.R
> +#' Add issues-count attribute based on the number of issues created, where the person represented by the vertex is the author.
Line length and "issue-count"

2021-04-22 12:47 UTC, bockthom commented on util-networks-covariates.R
> +#' @param name The attribute name to add [default: "issues.count.by.commenting"]
Wrong default value. Should be "issue.creation.count"

2021-04-22 12:47 UTC, bockthom commented on util-networks-covariates.R
> +#' Add issue-comments-count attribute based on the number of issues participated in by commenting, where the person represented by the vertex is the author.
Line length and "issue-comment-count"

2021-04-22 12:47 UTC, bockthom commented on util-read.R
> +    issue.data[commit.added.events.before.creation, "date"] = issue.data[commit.added.events.before.creation, "creation.date"]
This one is still missing: If the "creation.date" is missing (e.g., ""), the we agreed to not perform the date fixes (neither update "event.info.2", nor "date").

2021-04-22 12:47 UTC, bockthom commented on tests/test-networks-covariates.R
> +                                                author.relation = "cochange") {
Please provide the possible options here: `author.relation = c("cochange", "issue", "mail")` and add `author.relation = match.arg(author.relation)`.

2021-04-22 12:47 UTC, bockthom commented on tests/test-networks-covariates.R
> +    )
Unfortunately, the mail-count related tests are not changed to use mail data :disappointed: 
(Instead, you adjusted all the issue-count related tests to use issue data, which has not been necessary but time consuming..... :angry:).

2021-04-22 12:47 UTC, bockthom commented on NEWS.md
> +- Add per-author vertex attributes regarding issue/pull request/mail count and derived quantities (like mail thread count, issue creation count) (PR #194, 9f9150a97ffbb64607df0ddcbce299e16c2580da, 72
Please use some hyphens here for clarification:
"issue/pull-request/mail count"
"mail-thread count"
"issue-creation count"
"issue-comment count"
and also reference not only PR 194, but also the related issue number.

Maybe it is also worth to mention the function `preprocess.issue.data` (and what it can be used for) explicitly in a separate item (before the vertex attributes).

In addition, please add an additional item stating that we have added a new function `get.issues.filtered.uncached`.

2021-04-22 12:47 UTC, bockthom commented on NEWS.md
> +- Fix fencing issue timing data so that all issue actions "happen" after the issue was created (issue #185, 627873c641410182ca8fee0e78b95d7bda1e8e6b, 6ff585d9da1da3432668605f0c09f8e182ad0d2f)
Please talk about events instead of actions.
Unfortunately the description here does not correspond to the implementation: In the implementation we only adjust all the "commit_added" events but not "all" events in general (even if these was the purpose, this is not what we have implemented). And also "after" is not correct–we just make sure that it is "not before", so same time is still possible. Please also add the information that the original dates are not completely removed but now stored as event.info.2.

(And don't forget to adjust hashes in case they are outdated.)

2021-04-28 19:57 UTC, JoJoDeveloping commented on util-data-misc.R
> +#'         and the others the respective grouping
Their length is exactly 120 :tada:

2021-04-28 20:05 UTC, JoJoDeveloping commented on util-data-misc.R
> +#' Get the issue/pr comment count for each author based on the issues data contained in the specified \code{ProjectData}.
It has length 112

2021-04-28 22:42 UTC, bockthom commented on util-data-misc.R
> +## Copyright 2019 by Jakob Kronawitter <kronawij@fim.uni-passau.de>
Adjusting the copyright header does not mean to just copy the copyright header of the other file. Only take the copy-right information for the functions you have moved from the previous file. Therefore, you need to have a look at the git blame **and** at the commit history of the file `util-core-peripheral.R` to see which persons have been involved (and when they have been involved) in editing the moved functions.
To make a long story short, I had a quick look at the history of `util-core-peripheral.R` right now and figured out that the following people have **not** been involved in editing the moved functions, so please *remove* them from the copy right header of the file `util-data-misc.R` (ideally using a rebase so that these people will never show up in the copyright header in the history of the `util-data-misc.R` file):
Mitchell, Christian, Thomas.

2021-04-28 22:47 UTC, bockthom commented on util-data-misc.R
> +#'         and the others the respective grouping
Lucky you.

2021-04-28 22:52 UTC, JoJoDeveloping commented on util-data-misc.R
> +## Copyright 2019 by Jakob Kronawitter <kronawij@fim.uni-passau.de>
Thanks for looking at that history!

2021-04-28 23:01 UTC, bockthom commented on util-data-misc.R
> +0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901
What's that?

2021-04-28 23:04 UTC, bockthom commented on util-data.R
> +        filter.issues = function(issues, issues.only.comments) {
You return issues, not commits :wink: 
And if you already touch this again, please also add a blank line before the `## * * issue filtering` line. Thanks!

2021-04-28 23:10 UTC, bockthom commented on util-read.R
> +    issue.data[commit.added.events.before.creation, "date"] = issue.data[commit.added.events.before.creation, "creation.date"]
This one still seems to be not completely fixed, if I am correct. Missing "create.date" values indicated by an *empty string* are still not catched...

2021-04-28 23:14 UTC, JoJoDeveloping commented on util-read.R
> +    issue.data[commit.added.events.before.creation, "date"] = issue.data[commit.added.events.before.creation, "creation.date"]
In the current code, we do
```R
    commit.added.events.before.creation = commit.added.events &
        !is.na(issue.data["creation.date"]) & (issue.data["date"] < issue.data["creation.date"])
```

Which works, because `issue.data["creation.date"]` has already been passed through `get.date.from.string` (see line 344), which returns `NA` when given an empty string. Thus catching `NA` suffices.

2021-04-28 23:15 UTC, bockthom commented on util-read.R
> +    issue.data[commit.added.events.before.creation, "date"] = issue.data[commit.added.events.before.creation, "creation.date"]
Ok, I take back what I said. I just overlooked that the `get.date.from.string` is called before. (Sorry for my previous comment.)
I guess it is time for sleeping now instead of posting wrong comments...

2021-04-28 23:20 UTC, bockthom commented on showcase.R
> +###### TODO HERE
Last comment for tonight: Is this intended (e.g., to ask for further clarifications), or did you just forget about updating the showcase file?

2021-04-28 23:21 UTC, JoJoDeveloping commented on showcase.R
> +###### TODO HERE
It is still to do.

2021-04-29 09:26 UTC, bockthom commented on NEWS.md
> +- Fix fencing issue timing data so that all issue actions "happen" after the issue was created (issue #185, 627873c641410182ca8fee0e78b95d7bda1e8e6b, 6ff585d9da1da3432668605f0c09f8e182ad0d2f)
> Unfortunately the description here does not correspond to the implementation: In the implementation we only adjust all the "commit_added" events but not "all" events in general (even if these was the purpose, this is not what we have implemented). And also "after" is not correct–we just make sure that it is "not before", so same time is still possible. Please also add the information that the original dates are not completely removed but now stored as event.info.2.


This part of the NEWS.md still is imprecise and waits for an adjustment...

2021-04-29 09:37 UTC, bockthom commented on showcase.R
> +# sample.pull.requests = add.vertex.attribute.issue.count(my.networks, x.data, issue.type = "pull.requests")
Maybe we should also add a custom name (e.g., `"pr.count"`) when calling `add.vertex.attribute.issue.count` with `issue.type = "pull.requests"`, as the default name is `"issue.count"`.

This way, I just spotted another issue: All the `add.vertex.attribute.issue.*.count` have a parameter `issue.type`. But in the function declaration, only the default value `"all"` is mentioned. Could you please add a vector `issue.type = c("all", "issues", "pull.requests")` to all these function declarations in `util-data-misc.R` ?

(With that, I finished reviewing your changes. However, I will have a final check at the recently added tests soon.)

2021-04-29 12:33 UTC, bockthom commented on tests/test-networks-covariates.R
> +    )
Thanks for updating the test. Unfortunately, the new test reveals the same issue as the previous test: Mail count and mail thread count still are identical, and so the test for the thread count does not really test for the thread count.
The reason for this is that Hans (which is the person who participates in the same thread multiple times and, thus, makes a difference in these tests) only participated in 2010, whereas the ranges cover the ranges between 2016-07-12 15:00:00 and 2016-08-31 18:00:00.

However, I have a suggestion for an easy solution of this problem: We need to have a range which contains Hans's e-mails, but only for these tests. Hence, I suggest to add a new global variable `mybins.starting.from.2010` and also `myranges.starting.from.2010` (see lines 41-42). In the new bins, we can have an additional range at the beginning to cover Hans's activity: `c("2010-07-12 12:00:00", "2016-07-12 15:00:00", "2016-07-12 16:00:00", "2016-07-12 16:05:00", "2016-08-31 18:00:00")` 

Then we could add an additional parameter `ranges` to `get.network.covariates.test.networks` which defaults to `myranges`. In the two tests where we need Hans's data, we then can pass `myranges.starting.from.2010` to the function. Then we have four ranges there, where the first one covers Hans's mailing mail activity to the same thread. This should fix the problem, if I didn't overlook anything.

2021-04-29 12:47 UTC, bockthom commented on NEWS.md
> +- Add function `get.issues.filtered.uncached`, which gets the issues filtered without poisoning or using the cache.
Commit hashes are missing.

2021-04-29 12:48 UTC, bockthom commented on NEWS.md
> +- Rename `get.issues` to `get.issues.filtered`, write a new `get.issues` to get the unfiltered issues so that these methods follow the naming scheme known from the respective methods for commits, and
`get.issues.filtered.uncached` is not added in this commit. However, as we mention this function in the Added section, it is not necessary to mention it here.

2021-04-29 12:50 UTC, bockthom commented
I've done with my final review! As soon as the stated issues regarding test, news, and showcase/util-networks-metrics are fixed, this PR can be merged.

2021-04-29 23:17 UTC, bockthom commented
Thanks @JoJoDeveloping for your endurance. This PR contains a lot of substantial and valuable changes and will definitively improve coronet in various directions.
All the implementation-related issues (at least, those which we have spotted) are fixed now, looks really good :smile: :+1: 

The only point of criticism left is that the last commit does not contain a signed-off tag :wink:

2021-04-30 09:55 UTC, bockthom approved these changes

2021-04-30 09:56 UTC, hechtlC approved these changes

2021-04-30 09:59 UTC, merged