Add more explanation to 'metrics.avg.path.length' as well as default …
se-sic/coronet pull request #195
Opened 2021-02-09 09:30 UTC by nlschn

### Prerequisites

- [x] I adhere to the coding conventions (described [here](https://github.com/se-passau/coronet/blob/master/CONTRIBUTING.md)) in my code.
- [x] I have updated the copyright headers of the files I have modified.
- [x] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [x] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](https://github.com/se-passau/coronet/blob/master/NEWS.md) appropriately.
- [x] The pull request is opened against the branch `dev`.

### Description
Fix some bugs discussed in #181 in `util-network-metrics`:  
- [ ] (1) Clarify `metrics.avg.pathlength`
- [ ] (2) Add default values to several methods
- [ ] (3) Clarify `is.smallworld`
- [ ] (4) Handle error in `metrics.smallworldness`
- [ ] (5) Handle empty networks in `metrics.hub.degree`
- [ ] (6) Integrate centrality functions into `util-network-metrics`
### Changelog

To be written....

2021-02-09 16:36 UTC, bockthom reviewed
Thanks for working on these little fixes @nlschn. I know that this PR is just a draft PR and not yet ready for review. However, I just spotted two issues which I would already highlight while you are working on the PR, as you could potentially take care of that in similar situations in the remaining part of this PR.

(In addition, I would like to get rid of the empty merge commit. But this is not yet relevant as long as this PR is just a draft :wink: )

I will do a full review once the PR is ready for review. (Sorry for sliding in already.)

2021-02-09 16:36 UTC, bockthom commented on util-networks-metrics.R
> +#'                    If TRUE only the lengths of the existing paths are considered and averaged;
Please follow our [coding conventions](https://github.com/se-sic/coronet/blob/master/CONTRIBUTING.md#r-coding-conventions):
> Variable names, class names, or other code snippets which are part of the function documentation must be placed within \code{...}

So, please use `\code{TRUE}` and `\code{FALSE}` within `roxygen2` function documentation. (Note that this doesn't hold for the default value [default: ...] as the default value is assumed to always be code (this also part of our conventions).

2021-02-09 16:36 UTC, bockthom commented on util-networks-metrics.R
> +#' @param mode the mode to be used for determining the degrees [default: c("total", "in", "out")]
This is actually wrong, unfortunately. It is a bit tricky here: Usually, you would be right and the default value is the complete vector assigned to the parameter in the default setting. However, there is one exception: If there is a `match.arg(...)` call at the beginning of the function's implementation, then this does not hold. `match.arg` makes sure that the given parameter is **one** of the allowed ones specified in the default setting. Otherwise, an error is thrown. If no parameter is explicitly passed to the function, only the **first** element of the vector is taken. Only if `match.arg(..., several.ok = TRUE)` is used, then multiple values are allowed and the complete vector is used as default.
However, all this only holds if the parameter variable is reassigned when calling `match.arg`, as it is the case in line 38: `mode = match.arg(mode)`. Without the reassignment, the complete vector would still be the default value. I hope I didn't confuse you with all the details, that's a bit tricky :mag: 
<sub>(To be honest, the functionality of `match.arg` even was not sufficient for our needs in some cases, as sometimes we would like to have another default value than `match.arg` provides us with the first element. Therefore, we also have written our own extension to `match.arg`, namely `match.arg.or.default` which behaves a little bit different (see `util-misc.R`), but to the best of my knowledge, our extension is not used in the metrics module, so you don't need to check for that one here.)</sub>

2021-02-27 13:19 UTC, nlschn commented
The rebase in order to erase the empty merge commit created by GitHub lead to the commits getting new hashes and being dated to today. However the old commits still seem to appear in this conversation, whereas the history is correct in the commits tab above.
I now removed the "draft" tag so the PR can be reviewed. I hope, that I don't have forgotten anything 😇

2021-03-01 14:42 UTC, bockthom requested changes
Thank you very much for working on this PR @nlschn, good work!

One comment on the commits mentioned in this PR: Outdated commits are appearing in this PR as you have referenced this PR in your commit message. (Btw, mentioning the PR there is not necessary, but you can do that if you are happy to do so). For reviewing, we should stick to the commits tab anyway, and on this tab only the current commits are displayed. So, no worries.

I just found a few documentation-related issues which are worth to be fixed, mostly small stuff.
However, there is one issue regarding error handling in the smallworldness function which I would like you to adjust for better comprehensibility.

In addition, there is a bigger issue with the `metrics.centrality` function which I have not yet thought about (my fault)––see the corresponding individual comment. Let's discuss this one in our weekly meeting, maybe we find with a pragmatic solution that does not cost that much effort :crossed_fingers: 

Tests will be reviewed later (see also the corresponding individual comment).

2021-03-01 14:42 UTC, bockthom commented on util-networks.R
> +#' empty relation, i.e. \code{character(0)}
The first sentence (just describing the function in general) should end with a period.
Between parameter description and return-value description, there should be an empty line.

In addition, please don't forget to add your copyright header to this file :wink:

2021-03-01 14:42 UTC, bockthom commented on util-networks.R
> +            }
Did you really encounter such a case where the relation actually is `character(0)`? If so, I would be happy if you could tell me where/when this actually happens :smile:

2021-03-01 14:42 UTC, bockthom commented on util-networks.R
> +        }, USE.NAMES = FALSE)
The indentation looks weird. Let's make the indentation of the line containing `}` the same as for the line containing the corresponding `}`

2021-03-01 14:42 UTC, bockthom commented on NEWS.md
> +- Add 'metrics.centrality' function to metrics module in order to simplify getting a data frame containing author names
Wrong quotation marks use here :wink: However, the name of this function may change anyway.

2021-03-01 14:42 UTC, bockthom commented on NEWS.md
> +- Add tests for the `get.data.sources.from.relations` function (PR #195, afbba88f85e7777828534611445e8463be4d55dc)
It's not worth to mention that (as tests should usually come with newly implemented functionality). It's only worth to mention if there are a bunch of new tests for already existing functionality.
However, it doesn't hurt to mention your tests. So you can keep it here :wink:

2021-03-01 14:42 UTC, bockthom commented on tests/test-networks.R
> +# ## All Rights Reserved.
Was this change intended?

Also for the rest of this test file: You have removed almost all tests of this file. Please undo that :exclamation: 
It is quite hard to figure out where the tests are which you have newly added to this file, as the git diff is bloated. As a consequence, I will review your tests as soon you have fixed the changes regarding the already existing tests.

2021-03-01 14:42 UTC, bockthom commented on NEWS.md
> +- Add default parameters to documentation of several other methods missing them (PR #195, 2085024661fcdc287a009cf6aa7f438cad7459ae)
I would suggest to combine those two bullet points. In the news file, we don't need to be that detailed, but just summarize the changes on a higher level. So just mentioning that the documentation in the metrics module `util-networks-metrics.R` is updated should be enough.

2021-03-01 14:42 UTC, bockthom commented on NEWS.md
> +- Handle error in igraph function by printing user warning instead. When calling  `metrics.smallworldness` with a network that is too large, i.e. that has too many edges a warning is being printed an
This is not worth to mention, as it belongs to the "documentation update" above.

2021-03-01 14:42 UTC, bockthom commented on NEWS.md
> +- Add check for empty network in `metrics.hub-degree` function. In the case of an empty network, a warning is being printed and `NA` is returned (PR #195, 231affc5d1c201b0cc3ea093477afde6acd6b9a5)
This is a change in the behavior which needs to be mentioned here. However, the function is called `metrics.hub.degree`, isn't it?

2021-03-02 01:08 UTC, nlschn commented on tests/test-networks.R
> +# ## All Rights Reserved.
Ohhh, sorry, that was absolutely not on purpose.

2021-03-02 08:55 UTC, nlschn commented on util-networks.R
> +            }
No, I didn't. When I tried to create a network with an empty relation by hand it failed when trying to build. 
But I recall from the meeting that I was supposed to implement a check nevertheless, just in case.

2021-03-02 09:07 UTC, nlschn commented on tests/test-networks.R
> +# ## All Rights Reserved.
So it should be repaired now. I am again very sorry, that should not happen.

2021-03-02 09:16 UTC, nlschn commented on util-networks-metrics.R
> +#requireNamespace("util-core-peripheral")
This is not meant to be there (anymore). I thought I'd have to include the namespace manually, because a function was not found. Turned out it was a spelling error. So I commented the line out. As I don't need it, I will remove it.

2021-03-02 09:39 UTC, bockthom commented on tests/test-networks.R
> +# ## All Rights Reserved.
No worries, something of the like has happened to everyone of us. Even if that should not happen, sometimes it happens :wink:

2021-03-02 09:51 UTC, bockthom commented on tests/test-networks.R
> +# ## All Rights Reserved.
The tests look good to me, I have no further comments on them. :smiley:

2021-03-02 10:12 UTC, nlschn commented on util-networks-metrics.R
> +            restrict.classification.to.authors = get.authors.by.data.source(get.data.sources.from.relations(network),
From what I can see using the busybox and openssl examples, the only relation returned by `unique(igraph::E(bipartite.network))$relation` seems to be the artifact relation; the author relation seems to be ignored.

2021-03-02 11:28 UTC, bockthom reviewed
Thanks for your fast adjustments @nlschn, most of the identified problems are fixed now. I just spotted a few additional or newly introduced minor issues.

In addition, unfortunately, many of your commit messages lack the signed-off-tag.

2021-03-02 11:28 UTC, bockthom commented on util-networks-metrics.R
> +VERTEX_CENTRALITIES_COLUMN_NAMES = c("vertex.name", "centrality")
Missed that already in my previous review: Use "." in variable names instead of "_". This also holds for constants.

2021-03-02 11:28 UTC, bockthom commented on util-networks-metrics.R
> +#' \code{restrict.classification.to.vertices} vector.
We don't need this sentence any more as we have added a similar one directly below :wink:

2021-03-02 11:28 UTC, bockthom commented on NEWS.md
> +- Add check for empty network in `metrics-hub-degree` function. In the case of an empty network, a warning is being printed and `NA` is returned (PR #195, 231affc5d1c201b0cc3ea093477afde6acd6b9a5)
Interesting change in the function-name spelling. Unfortunately, you have changed the wrong separator, as the function is called `metrics.hub.degree`

2021-03-02 12:10 UTC, nlschn commented on NEWS.md
> +- Add check for empty network in `metrics-hub-degree` function. In the case of an empty network, a warning is being printed and `NA` is returned (PR #195, 231affc5d1c201b0cc3ea093477afde6acd6b9a5)
I hope I don't need a third time to finally get it right...

2021-03-02 16:04 UTC, bockthom commented on NEWS.md
> +- Add check for empty network in `metrics.hub.degree` function. In the case of an empty network, a warning is being printed and `NA` is returned (PR #195, 231affc5d1c201b0cc3ea093477afde6acd6b9a5)
Almost done :wink: Thanks for adding the missing signed-off tags.
As a follow-up task, as you have rebased the commits, several commit hashes now wait for being updated :wink:

2021-03-02 16:25 UTC, nlschn commented on NEWS.md
> +- Add check for empty network in `metrics.hub.degree` function. In the case of an empty network, a warning is being printed and `NA` is returned (PR #195, 231affc5d1c201b0cc3ea093477afde6acd6b9a5)
~third~ second time's the charm 🌟

2021-03-08 14:58 UTC, hechtlC requested changes
First of all great work @nlschn. I have identified a couple of problems and potential problems, which should be fixed/addressed before merging. Let's talk about that in our next meeting.

2021-03-08 14:58 UTC, hechtlC commented on tests/test-networks.R
> +    expected.relations = c("mails")
Maybe rename this to `expected.data.sources`, as you compare it to the data.sources you extract from the relations. Just to be consistent.

2021-03-08 14:58 UTC, hechtlC commented on util-networks-metrics.R
> +#' @param unconnected whether there are vertices in the network that are not connected.
This might be wrong but aren't we using 'isolated' for unconnected vertices in coronet @bockthom ? If I am right, then we should keep naming consistent.

2021-03-08 14:58 UTC, hechtlC commented on util-networks-metrics.R
> +    ## else return whether the network is smallworld
Why else? I think you can remove the else here.

2021-03-08 14:58 UTC, hechtlC commented on util-networks-metrics.R
> +#' @param proj.data the \code{ProjectData} containing the vertices to classify
I am not completely sold on that wording. The `ProjectData` object does not hold the vertices but the data for them. I am not sure if I am too sensitive here or not. What do you think @bockthom.

2021-03-08 14:58 UTC, hechtlC commented on util-networks-metrics.R
> +            restrict.classification.to.vertices = get.authors.by.data.source(get.data.sources.from.relations(network),
Shouldn't we rename the function `get.authors.by.data.source` as the plan was to also support artifact networks? Or am I missing something? Maybe this is subject to further discussion in our next meeting.

2021-03-08 14:58 UTC, hechtlC commented on util-networks-metrics.R
> +        ## 'get.auther.class.by.type' function
'auther' should be 'author'. Also in line 337.

2021-03-08 15:11 UTC, bockthom commented on util-networks-metrics.R
> +#' @param unconnected whether there are vertices in the network that are not connected.
No, you are wrong here @hechtlC. `unconnected` really means `unconnected` :wink: 
Let me just cite Wikipedia on the quick: ["A graph is said to be connected if every pair of vertices in the graph is connected. This means that there is a path between every pair of vertices."](https://en.wikipedia.org/wiki/Connectivity_(graph_theory))
Hence, a network is unconnected if there are, for example, two separate components (you may call them clusters, not isolates) of the network that are not connected by an edge.
And there is another reason why this parameter is called `unconnected`: igraph also calls it `unconnected` :smile:

2021-03-08 15:14 UTC, bockthom commented on util-networks-metrics.R
> +    ## else return whether the network is smallworld
Good point, missed that. This is a relic of the former implementation where there was an unnecessary check at the beginning.

2021-03-08 15:19 UTC, bockthom commented on util-networks-metrics.R
> +#' @param proj.data the \code{ProjectData} containing the vertices to classify
Hm. On the one hand I agree that the data do not hold vertices. But on the other hand, explaining that in more detail would be very complex and even more confusing, I guess. Instead of vertices, we would need to differentiate between authors, artifacts, and what else could be passed to this function in the future. As there is no common superordinate, I would just stick to vertices, even if it is not 100 percent precise.

2021-03-08 15:24 UTC, bockthom commented on util-networks-metrics.R
> +            restrict.classification.to.vertices = get.authors.by.data.source(get.data.sources.from.relations(network),
This is the only review comment from my review which is [not resolved yet ](https://github.com/se-sic/coronet/pull/195#discussion_r584730047):wink: We already have discussed that last week in our meeting and @nlschn is currently working on this.
Indeed, you are missing something here @hechtlC: We cannot rename the function, but need to call different functions dependent on whether the vertex types in the network are "author", "artifact", or both. There is already a function `get.artifacts` which gets the data.sources, but this one is not ready for handling mutliple data sources, so @nlschn is also working on that right now.

2021-03-08 15:29 UTC, bockthom commented on util-data.R
> +            data.source = match.arg.or.default(data.source, several.ok = TRUE)
Please check if the default value has changed. `several.ok = TRUE` might take the vector of all possible values as default, but I am not sure. I am also not sure if there are any usages within coronet which rely on the default value. Please also check that.

2021-03-08 15:31 UTC, bockthom commented on util-data.R
> +            data.source.col = sapply(data.source, function (d) {
Please remove space between function name and its parameters: `function(d)` (two occurrences)

2021-03-08 15:32 UTC, hechtlC commented on util-networks-metrics.R
> +#' @param proj.data the \code{ProjectData} containing the vertices to classify
I am ok with that.

2021-03-08 15:34 UTC, bockthom commented on util-networks-metrics.R
> +            }
The implementation looks good to me, but one case is missing:
If there are both artifacts and authors in the network we need to combine the lists from `get.authors.by.data.source` and `get.artifacts` into one vector containing all of them.
Only if there only artifacts, then we can simply collect only artifacts :smile:

2021-03-08 15:45 UTC, nlschn commented on util-data.R
> +            data.source = match.arg.or.default(data.source, several.ok = TRUE)
this function uses the R function `match.arg` internally, when `several.ok` is set to `TRUE`.  This however returns only the first element of the choice vector when provided with the argument `NULL`. So everything should be fine.

2021-03-08 15:57 UTC, hechtlC commented on util-networks-metrics.R
> +#' @param unconnected whether there are vertices in the network that are not connected.
@bockthom and I have just talked about this. My confusion came from the wording 'unconnected vertices' but we are here talking about unconnected subnetworks. A single unconnected vertex would just be an isolate. So please change the documentation accordingly.

2021-03-08 16:15 UTC, bockthom commented on util-data.R
> +            data.source = match.arg.or.default(data.source, several.ok = TRUE)
I am not yet convinced. Default values behave different when `several.ok = TRUE`. Just have a look at the following snippet:

```R
> x = function(a = c("1", "2", "3")) {a = match.arg(a, several.ok = TRUE); print(a);}
> x()
[1] "1" "2" "3"

```

2021-03-08 16:23 UTC, bockthom commented on util-data.R
> +                print(unique.artifacts)
Did you forget to remove the `print` statement?

2021-03-08 16:28 UTC, nlschn commented on util-data.R
> +                print(unique.artifacts)
oops, sorry, yes, seems like I did...

2021-03-08 17:48 UTC, nlschn commented on util-data.R
> +            data.source = match.arg.or.default(data.source, several.ok = TRUE)
What the function calls is `match.arg(arg, choices, several.ok)` with three parameters.
For example
```
> match.arg(c("1", "2"), c("1", "2", "3"), several.ok = TRUE)
[1] "1" "2"

> match.arg(NULL, c("1", "2", "3"), several.ok = TRUE)
[1] "1"
```
In the case of `get.artifacts` the function `match.arg.or.default` is called with the parameters 
```
match.arg.or.default(data.source, several.ok = TRUE)
```
Because the parameter `choice` is missing, it is calculated from the parent function's signature and therefore is `c("commits", "mails", "issues")`. So the function will return
```
match.arg(data.sources, c("commits", "mails", "issues"), several.ok)
```
And then we are at my first snippet, when only the first element of the choice vector is returned, if `data.sources` is `NULL`.
Do I miss something here?

2021-03-08 19:34 UTC, bockthom commented on util-data.R
> +            data.source = match.arg.or.default(data.source, several.ok = TRUE)
This behavior of `match.arg` is weird. A missing argument is handled differently than `NULL` :cry: 
All your examples are totally correct, but they assume that the function parameter `arg` is actually set. Without that, the behavior is different, as the following example shows:

```R
> x = function(a = c("1", "2", "3")) {print(a); a = match.arg(a, choices = c("1", "2", "3"), several.ok = TRUE); print(a);}
> x()
[1] "1" "2" "3"
[1] "1" "2" "3"
> x(NULL)
NULL
[1] "1"
```
In case of a missing argument, the vector from the function declaration is taken, and since several values are ok, all of them are kept instead of just the first one...

2021-03-08 22:06 UTC, nlschn commented on util-data.R
> +            data.source = match.arg.or.default(data.source, several.ok = TRUE)
okay, now it is clear, although I still find it a little weird, as you said. But I will address this and try to restore the old default behaviour.

2021-03-09 09:08 UTC, nlschn commented on util-data.R
> +            data.source = match.arg.or.default(data.source, several.ok = TRUE)
I have now tried to fix the problem, using the same rather "hacky" method as can be found in the implementation of `match.arg.or.default`. 
One could argue to introduce yet another 'match.arg. ...' function with this behavior, just in case it is wanted elsewhere, because I assume changing `match.arg.or.default` would cause issues with exisiting calls to that function.

2021-03-09 12:14 UTC, bockthom commented on util-data.R
> +            data.source = match.arg.or.default(data.source, several.ok = TRUE)
We should separate the handling of default values from the actual implementation of this function. At the moment, I see two options: Either we create a new default-handling function, or we adjust the existing one.
As creating a new function may lead to confusions (which function to use when?), I would prefer to integrate the behavior into the existing one. We just need to add an additional parameter `single.default.when.several.ok` (or any other name which is more suitable). This parameter needs to default to `FALSE`. If the parameter value is actively set to `TRUE`, the corresponding if-else cascade in `match.arg.or.default` needs to be adjusted. This should not cause any issues, as we have tests for this function––but then it is be necessary to add an additional test case for that.
@hechtlC Do you agree with that?

2021-03-09 18:32 UTC, nlschn commented on util-data.R
> +            data.source = match.arg.or.default(data.source, several.ok = TRUE)
After trying for a while now I face a problem when attempting to implement your suggestion.
When calling `single.default.when.several.ok(arg, choices, severl.ok = TRUE)` where `arg` was not given it becomes problematic. Because inside `single.default.when.several.ok` the `arg` equals the default vector of the calling function and it is not possible any more to tell whether it has been set so deliberately or it was not given and has been replaced by the default vector.

For example:
```
> f = function(x) {print(missing(x))}
> g = function(y = c("a", "b", "c") {return(f(y))}
> g()
[1] FALSE
> f = function(x) {print(x)}
> g()
[1] "a", "b", "c"
```

I have no idea where to get the information from that in `f` the parameter was missing when calling `g`. 
Maybe you have some ideas on that?

2021-03-09 20:30 UTC, bockthom commented on util-data.R
> +            data.source = match.arg.or.default(data.source, several.ok = TRUE)
To answer your question:
In your example, `f` always gets a parameter, it is never missing when calling `g`, as you actually call `f(y)` inside `g`. It does not depend on where `y` comes from, `y` is always passed to `f`, so `x` is never missing. If you would like to create an example, where `x` is missing, you need to adjust `g` so that it calls `f()` without argument.

But thanks for the example, it showed me that my idea from above does not work :see_no_evil: My bad! I did not have in mind that we need to figure out whether the argument is missing or not, just thought that `match.arg` does some magic for us, but it actually doesn't.

However, I have two pretty new ideas now (without guarantee that they work as intended):

1. This idea just adjusts your implementation of `get.artifacts` and uses a trick, resulting in one statement replacing the current if-else blocks there:
    ```R
    data.source = match.arg(data.source, several.ok = !missing(data.source))
    ```
    This should exactly do what we want––please correct me if I'm wrong.

2. If the idea above does not work, we could think about adding a `missing` parameter to `match.arg.or.default` and try to handle our situation inside `match.arg.or.default` then, but this sounds a little bit ugly to me...

2021-03-09 20:42 UTC, nlschn commented on util-data.R
> +            data.source = match.arg.or.default(data.source, several.ok = TRUE)
I get your idea and testing it with the console I could not find a case where it goes wrong. Thanks a lot!

2021-03-10 10:37 UTC, bockthom commented on util-data.R
> +            data.source = match.arg.or.default(data.source, several.ok = TRUE)
I am glad that the suggested solution works this time, and we have even achieved to address this problem using just one line of code :smile: 
I have spotted just one part in this functions which could be improved (see my comment below), then we are done with this PR––at least from my view.

2021-03-10 10:58 UTC, bockthom commented on util-data.R
> +            }
First of all a question: Why not combining the different `sapply` (resp. `lapply`) statements into one `lapply`, as it is done here: https://github.com/se-sic/coronet/blob/a7f4123dcb86a7a0f76adf791b66a7d9c24f7647/util-data.R#L1377-L1380

And then I would like also to get rid of the `for` loop here, which can be easily achieved, if I did not miss anything:
`unique(unlist(lapply(data, function(d) { ... })`

And I just noticed that we adjusted the parameter name `data.source` to `data.sources` when enabling multiple data sources in `get.authors.by.data.source`. I would like to stay consistent in these two functions and rename the parameter also here. As the parameter name seems to be used nowhere outside in this function, there should be no need for further adjustments on any function call.

And finally, please also add a sentence to the changelog file that we have adjusted this function, for example:

 Adjust the function `ProjectData$get.artifacts`: Rename its single parameter to `data.sources` and change the function so that it can extract the artifacts for multiple data sources at once. The default is still that only artifacts from the commit data are extracted. (...)

This should be the very last change on this PR, then we should be done, except @hechtlC has further comments.

2021-03-11 08:00 UTC, bockthom approved these changes

2021-03-11 14:30 UTC, hechtlC approved these changes

2021-03-11 18:31 UTC, merged