Fix wrong data path issue and emerging bugs
se-sic/coronet pull request #199
Opened 2021-03-29 13:45 UTC by nlschn

### Prerequisites

- [X] I adhere to the coding conventions (described [here](https://github.com/se-passau/coronet/blob/master/CONTRIBUTING.md)) in my code.
- [ ] I have updated the copyright headers of the files I have modified.
- [ ] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [ ] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](https://github.com/se-passau/coronet/blob/master/NEWS.md) appropriately.
- [X] The pull request is opened against the branch `dev`.

### Description

This shall at some time fix #197 and #177.

### Changelog

Nothing yet.

2021-04-22 16:07 UTC, bockthom commented on NEWS.md
> +- Adjust the function `update.pasta.data()`: no warning is being printed anymore when calling the cleanup function (PR #199, 432c66b839932660f144050c6399dc9112b023f3)
If you mention pasta, then you should also mention the other two functions where this holds :wink: 
Moreover, instead of "when calling the cleanup function", it should rather be "when being called from the corresponding cleanup function"

2021-04-22 16:09 UTC, bockthom commented on NEWS.md
> +- Fix issue where the data path on `ProjectData` objects was wrong in special cases. Introduce a (private) flag that is set according to how the object has been created (splitting manually or reading
The data path on `RangeData` objects was wrong, not on `ProjectData` objects. If you start a new sentence, don't forget the period at the end of the sentence before.

2021-04-22 16:12 UTC, bockthom commented on NEWS.md
>  ## 3.7
All the three bullet points would rather fit to category "### Fixed" (but this again will cause merge conflicts later on).
And please don't remove the blank lines between your fixes and the last release number.

2021-04-23 14:50 UTC, nlschn commented on tests/test-split.R
> +    mails <- project.data$get.mails()
I am a bit confused though. I have added a check which reflects my understanding of your post; but I am not 100% sure whether this understanding is right. I'd be happy to read your comments on this changes in the next review stage.

2021-04-23 14:51 UTC, nlschn commented on tests/test-split.R
> +    range.paths = run.lapply(data, "get.data.path")
Always glad to help 😇

2021-04-23 14:54 UTC, nlschn commented on util-bulk.R
> +    ranges = project.conf$get.value("ranges", TRUE)
I have probably pasted `, TRUE` to the wrong place. Thanks

2021-04-23 15:23 UTC, nlschn commented on util-data.R
> +
I can easily delete it if it is not necessary.

2021-04-23 15:36 UTC, nlschn commented on util-bulk.R
> +        range.data = RangeData$new(project.conf, range, built.from.range.data = TRUE)
There is nothing to replace in `showcase.R` (at least nothing I am aware of

2021-04-23 16:00 UTC, bockthom commented on tests/test-split.R
> +    mails <- project.data$get.mails()
I had a quick look at your changes, your understanding is right. I would just suppose to additional changes:
1. Please move the check for the correct data path (`expected`, `result`, and `expect_identical`) up directly below the function call `get.data.cut.to.same.date`. Everything what is done below is not needed for this particular check.
2. Please adjust the comments for the second check at the end: At the moment, there are two comments stating that something is checked after resetting.

2021-04-23 16:02 UTC, bockthom commented on util-data.R
> +            if(caller != "cleanup.pasta.data()") {
Btw, there is a space missing after `if`. Also holds for similar statements (even after the changes you already did here).

2021-04-23 16:09 UTC, bockthom commented on util-bulk.R
> +        range.data = RangeData$new(project.conf, range, built.from.range.data = TRUE)
I am not sure if this really is the case. 
Let's consider the following statement, which is part of the showcase file: `RangeData$new(project.conf = proj.conf, range = ranges[[22]])`
The `ranges` seem to come from the project configuration and not from splitting. Please print these ranges and check where they come from.
And there are similar statements in the ProjectConf.
It might be the case that we don't need to set the flag here, but I am not sure about this.

2021-04-23 16:16 UTC, nlschn commented on util-bulk.R
> +        range.data = RangeData$new(project.conf, range, built.from.range.data = TRUE)
When running the showcase with the test data it spit out the two codeface ranges.

2021-04-30 12:44 UTC, hechtlC requested changes
Nice work @nlschn!
I only have two minor remarks which I added as comments.
One other thing is that you forgot the copyright header in util-misc.R so please add that.

2021-04-30 12:44 UTC, hechtlC commented on tests/test-data.R
> +    project.configuration$update.value("mails.filter.patchstack.mails", TRUE)
Why are you filtering patchstack mails here?

2021-04-30 12:44 UTC, hechtlC commented on util-misc.R
> +get.last.but.one.element = function(v) {
I think the name and description of this function can be a bit confusing. Am I understanding it correctly that you get the last element of a vector **if** the vector has a least 2 elements? I think you should clarify that. It is explained in the @return tag but I think it should be explained in the description itself.
What do you think @bockthom ?

2021-04-30 14:13 UTC, bockthom commented on tests/test-data.R
> +    project.configuration$update.value("mails.filter.patchstack.mails", TRUE)
I'd guess that this was part of my minimum working example. I may have added it to somehow read the e-mails implicitly at the beginning. It does not hurt to keep that one also in the test, but as it seems not to be necessary for this test, we could also remove it.

2021-04-30 16:32 UTC, nlschn commented
Since the empty merge conflict is _before_ the logo commits that I pulled, every time I try to remove the empty commit it changes the hashes of @bockthom's commits concerning the logo. Is there any possibility how to avoid that?

2021-04-30 19:49 UTC, bockthom commented
> Since the empty merge conflict is _before_ the logo commits that I pulled, every time I try to remove the empty commit it changes the hashes of @bockthom's commits concerning the logo. Is there any possibility how to avoid that?

Maybe the following steps will do it (without any guarantees –– so make sure to not get lost of anything):

1. Create a new local branch from your branch `mydev`: `checkout -b mydev2`
2. Create a new local branch from your branch `mydev`: `checkout -b mydev3`
3. On `mydev3`, make a hard reset to the merge commit from the logo PR: `git reset --hard bf8b331cd874f6fef787af0a6ad69c2a0496d3bb`
4. On `mydev2` (`git checkout mydev2`), make a hard reset to your last commit before the merge commit we want to remove: `git reset --hard 87a243f5fea4d9c40aa5418965fff4e0c23c3358`
5. Rebase this one on the previous dev after the logo PR: `git rebase mydev3`. After that, everything before the merge commit you want to remove should be correctly rebased.
6. On `mydev` (`git checkout mydev`), rebase on the stuff we have cleaned before: `git rebase mydev2`
7. Then everything should be fine (please check if all commits are still there and the unwanted merge commit is removed and commits up to bf8b331 have not changed their hashes).

I hope that this would solve the problem, if I did not overlook anything.

2021-05-01 18:14 UTC, clhunsen commented on util-misc.R
> +get.last.but.one.element = function(v) {
Would you consider renaming this function to `get.second.last.element`? As @hechtlC, I myself was confused by reading "last but one" (and variants!) in the description text. Writing and reading about the "second-last element" is less confusing, I guess.

2021-05-03 15:20 UTC, nlschn commented
I have managed to get rid of the empty merge commit, pulled the commits (using `--rebase` this time...) from @JoJoDeveloping 's PR and tried to manually resolve the conflicts (as predicted there were a few). As soon as you have reviewed this, I am going to change the hashes in the changelog  to the new ones and then it should be ready to go.

2021-05-06 08:19 UTC, hechtlC commented on tests/test-data.R
> +    project.configuration$update.value("mails.filter.patchstack.mails", TRUE)
Ok so please remove this @nlschn .

2021-05-06 08:19 UTC, hechtlC commented
Please don't forget about your copyright header in `util-misc.R` @nlschn .

2021-05-06 11:54 UTC, nlschn commented on tests/test-data.R
> +    project.configuration$update.value("mails.filter.patchstack.mails", TRUE)
This should have happened with e0145e2b72aa9c6be706fd6f08abd8d7da811215

2021-05-06 12:46 UTC, bockthom reviewed
Almost done. Looking forward to merging this PR soon.

2021-05-06 12:46 UTC, bockthom commented on NEWS.md
> +- Fix the function `reset.environment()` of both the `ProjectData` and `NetworkBuilder` class; they now reset all the data (PR #199, 87a243f5fea4d9c40aa5418965fff4e0c23c3358)
This commit hash is still outdated...

2021-05-06 12:46 UTC, bockthom commented on NEWS.md
> +- Fix issue where the data path on `RangeData` objects was wrong in special cases. Introduce a (private) flag that is set according to how the object has been created (splitting manually or reading c
Could you please add the name of the (private) flag  `...` here? Then please also reference commit 
169c03 as third commit here.
For the tests, please also add the commit hashes d454e5a and 66ad127 as in this two commits the test behavior is substantially updated.

2021-05-06 13:07 UTC, bockthom approved these changes

2021-05-06 13:09 UTC, hechtlC approved these changes

2021-05-06 13:22 UTC, merged