Fix #198: Wrong ProjectConf after various data splittings
se-sic/coronet pull request #200
Opened 2021-04-22 03:59 UTC by JoJoDeveloping

- [x] I adhere to the coding conventions (described [here](https://github.com/se-passau/coronet/blob/master/CONTRIBUTING.md)) in my code.
- [x] I have updated the copyright headers of the files I have modified.
- [x] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [x] I have put signed-off tags in *all* commits.
- [x] I have updated the changelog file [NEWS.md](https://github.com/se-passau/coronet/blob/master/NEWS.md) appropriately.
- [x] The pull request is opened against the branch `dev`.

### Description

Make splitting create new configuration objects for the split data results, as discussed in #198.

Closes #198

2021-04-30 10:29 UTC, bockthom reviewed
Nice work @JoJoDeveloping , I like it. :+1: 
I only have some minor comments on how we could further improve our tests.

2021-04-30 10:29 UTC, bockthom commented on tests/test-split-sliding-window.R
> +        expect_equal(res$get.project.conf()$get.value("ranges"), expected, info = "Time ranges.")})
Could you please move the `})` at the end to a new line and align the new one with the indentation of `lapply`?
(This also holds for similar statements below and also in the other touched test files.)

In addition, shouldn't we also test that the original `proj.conf` is not adjusted, to make sure that we indeed have different object instances here?

2021-04-30 10:29 UTC, bockthom commented on util-split.R
>          type = "time-based",
Can we also add some checks for that in some of the existing splitting tests, to make sure that the splitting info is adjusted correctly everywhere (that is, on the cloned conf objects but not on the original one) ?

2021-04-30 10:29 UTC, bockthom commented on NEWS.md
> +- Make splitting no longer modify the original ProjectConf, instead create a copy (70e73ea16e09fbb2b4bd9be38a19e89c798d4d8e)
I would rather move that to the `### Fixed` section, as the previous behavior was actually wrong.
@hechtlC What is your opinion on that?

2021-04-30 14:56 UTC, JoJoDeveloping commented on tests/test-split-sliding-window.R
> +    expect_equal(proj.conf$get.value("ranges"), c("v1-v2", "v2-v3"))
`info` means into the documentation of that "method"?

2021-04-30 14:58 UTC, bockthom commented on tests/test-split-sliding-window.R
> +    expect_equal(proj.conf$get.value("ranges"), c("v1-v2", "v2-v3"))
I'm not sure what you are referring to. I refer to the `info` parameter of the `expect_equal` function (see also two lines above) that provides a very short notice on what is covered with the `expect_equal` statement.

2021-04-30 14:59 UTC, JoJoDeveloping commented on tests/test-split-sliding-window.R
> +    expect_equal(proj.conf$get.value("ranges"), c("v1-v2", "v2-v3"))
Ah, I was not aware that parameter existed.
Will do.

2021-04-30 15:09 UTC, JoJoDeveloping commented on util-split.R
>          type = "time-based",
Is there a way to get more than 1 value from the config? Something like `$get.values(c("foo", "bar"))` which then returns a dataframe, or a vector, or something like that??

2021-04-30 15:15 UTC, bockthom commented on util-split.R
>          type = "time-based",
No, i don't think so. (There is a function `get.conf.as.string` which dumps the complete config with all its values, but this is not what you are looking for, I guess).

2021-04-30 15:18 UTC, JoJoDeveloping commented on util-split.R
>          type = "time-based",
I would propose we do something like this
```
expected = list(
    split.type = "time-based",
    split.length = "3 min",
    split.basis="commits"
    split.sliding.window = FALSE,
    split.revisions = c("2016-07-12 15:58:59", "2016-07-12 16:01:59", "2016-07-12 16:04:59", "2016-07-12 16:06:33"),
    split.revision.dates=NULL
)
actual = lapply(names(expected), function(x) {the.split.config$get.entry(x)})
expect_equal(expected,actual)
```

2021-04-30 15:19 UTC, JoJoDeveloping commented on util-split.R
>          type = "time-based",
These 6 entries are set by `set.splitting.info`. It also sets `split.ranges`, however that is constructed from these 6 values within `set.splitting.info`, so we don't need to test for it if we only want to assert that the parameters of that function are set correctly

2021-04-30 15:20 UTC, JoJoDeveloping commented on tests/test-split-sliding-window.R
> +    expect_equal(proj.conf$get.value("ranges"), c("v1-v2", "v2-v3"))
like this?
```
    lapply(results, function(res) {
        expect_equal(res$get.project.conf()$get.value("ranges"), expected, info = "Time ranges.")
    })
    ## `c("v1-v2", "v2-v3")` is the default, make sure that did not change
    expect_equal(proj.conf$get.value("ranges"), c("v1-v2", "v2-v3"), info = "splitting modified original ProjectConf!")
    ```

2021-04-30 15:28 UTC, bockthom commented on util-split.R
>          type = "time-based",
Yes, sounds like a good idea (if you also fix the spacing issues etc...)

2021-04-30 15:32 UTC, bockthom commented on tests/test-split-sliding-window.R
> +    expect_equal(proj.conf$get.value("ranges"), c("v1-v2", "v2-v3"))
I would like to start with "make sure that the original project configuration did not change" (and then you could explain the default in parentheses, if wanted).

Regarding the info parameter: Your suggestions specifies the opposite of what is expected, if I am correct.

2021-04-30 15:34 UTC, JoJoDeveloping commented on tests/test-split-sliding-window.R
> +    expect_equal(proj.conf$get.value("ranges"), c("v1-v2", "v2-v3"))
The info is what is printed out when the assert fails. Thus  I made it denote the error condition.

2021-04-30 15:40 UTC, bockthom commented on tests/test-split-sliding-window.R
> +    expect_equal(proj.conf$get.value("ranges"), c("v1-v2", "v2-v3"))
That might be actually true (but we never have used it in coronet in such a way to denote the error condition, if I am true, but rather phased it in a neutral way).
So, I don't care, phrase it like you would like to and let's @hechtlC decide on that :wink:

2021-04-30 18:43 UTC, JoJoDeveloping reviewed
Is this a bug?

2021-04-30 18:43 UTC, JoJoDeveloping commented on tests/test-split-sliding-window.R
> +        split.sliding.window = FALSE, ## TODO is this the supposed value
split.sliding.window is `FALSE` as per this:
https://github.com/se-sic/coronet/blob/9a4ccb156127fd3ec001fb5ec534c6c870f64590/util-split.R#L103

Is this intended?

2021-04-30 19:14 UTC, bockthom commented on tests/test-split-sliding-window.R
> +        split.sliding.window = FALSE, ## TODO is this the supposed value
> Is this intended?

Yes, it is. When bins are specified, we cannot have sliding windows. Thus, the `sliding.window` parameter is ignored in this case. See also the comment which describes this test:
https://github.com/JoJoDeveloping/coronet/blob/dc74235abb7b3eab5c4347b5e55b64d319333727/tests/test-split-sliding-window.R#L412

---

Btw, could you please add a blank line before each of your comments `## This value should...` and `## test thatthe config ...` as this would ease reading.

2021-05-27 10:13 UTC, bockthom requested changes
Thanks @JoJoDeveloping, your PR looks really good now. I only have one minor comment regarding the warning you have added, as it is a little bit imprecise in certain cases - please see my comment below. (And when you fix that, please reword the commit message as we don't have "javadoc" as it is not java, just talk about function documentation.)

As soon as you have fixed that, please rebase onto the current `dev` branch and make sure that the commit hash mentioned in the line you have added to the NEWS.md gets updated correctly. Then we can merge this PR right away.

2021-05-27 10:13 UTC, bockthom commented on util-split.R
> +                             activity.amount, activity.type, project.data$get.class.name(), activity)
This warning is a little bit imprecise in one specific case, namely when splitting issues:
If `activity.type` is `issues`, then you would print `Can not form bins of x issues ...`. However, we don't count issues, but activities, that is, issue events. Could you please create a variable that takes the `activity.type` when talking about commits or mails, but uses "issue events" in case of issues and use the new variable instead of `activity.type` when printing the warning. Please also use the variable again at the end instead of "data rows", to also be more precise here, since we don't count data rows but activities.

2021-05-28 05:20 UTC, bockthom commented
Signed-off tags are still missing in the last few commits...

2021-05-30 14:41 UTC, bockthom approved these changes

2021-05-30 14:43 UTC, merged