Enable to read data at every point in time
se-sic/coronet pull request #201
Opened 2021-05-13 11:54 UTC by nlschn

### Prerequisites

- [x] I adhere to the coding conventions (described [here](https://github.com/se-passau/coronet/blob/master/CONTRIBUTING.md)) in my code.
- [x] I have updated the copyright headers of the files I have modified.
- [x] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [x] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](https://github.com/se-passau/coronet/blob/master/NEWS.md) appropriately.
- [x] The pull request is opened against the branch `dev`.

### Description

This PR adresses #177, specifically [this comment](https://github.com/se-sic/coronet/issues/177#issuecomment-806912711)

### Changelog

2021-05-24 22:08 UTC, nlschn commented
When trying to find the many bugs I created, I just stumbled upon an interesting question.
With the new functionality, that not all data sources are read when splitting, there is a possibility that when splitting e.g. by commits, that the commits have not been read yet. This happens for example in `test_that("Check consistency of data and network time-based splitting."` (`tests-split.R`, line 1638). The test fails because there is no commit data, that it can read the dates from which results in a rather cryptic error message (missing value where TRUE/FALSE was expected). But when I call `project.data$get.commits()` before actually splitting, it works (or rather fails with a different message, but that's something else...) so now it has the data and the corresponding "date" column. 
Long story short: My question is, what should happen in this case? I think we should at least check if the data source you are trying to split by is present and print a warning if not. To go further, one could automatically read the necessary data in order to enable immediate splitting. What do you think about that?

2021-05-25 07:28 UTC, bockthom commented
> When trying to find the many bugs I created, I just stumbled upon an interesting question.

If you got stuck during bug fixing, we can have a closer look at the bugs together in our next meeting and have a joint.

> Long story short: My question is, what should happen in this case? I think we should at least check if the data source you are trying to split by is present and print a warning if not. To go further, one could automatically read the necessary data in order to enable immediate splitting. What do you think about that?

We should automatically get the data that is needed for splitting. So, for example, when we split by commits, we should call the getter for the commit data within the splitting function before the actual splitting is performed. I guess this should fix the problem in general.

Anyway, it can still be the case that the commit data actually is empty. In such a case, we could think about printing a warning but I am not sure what happens in such a case. If it leads to an error, we maybe should throw an error instead of warning. But we can discuss this on Thursday in detail.

2021-05-25 09:50 UTC, nlschn commented
> If you got stuck during bug fixing, we can have a closer look at the bugs together in our next meeting and have a joint debugging session.

At the moment the number of rows in the data of RangeData objects does not match with the expected data. I will try to find the reason for this until friday, but if I don't succeed, I would gladly take your offer.

> We should automatically get the data that is needed for splitting. So, for example, when we split by commits, we should call the getter for the commit data within the splitting function before the actual splitting is performed. I guess this should fix the problem in general.

This shouldn't be that big of a problem.

2021-07-08 15:48 UTC, nlschn commented
At last, this PR is now ready to be reviewed. All tests in all versions finally run and I brought README and NEWS up to date with the latest changes and additions.

2021-07-12 11:04 UTC, hechtlC requested changes
Thank you for the nice enhancements and fixes @nlschn! 
I have just found some minor issues. But these need fixing nevertheless. Some of these are not of your making but since you are already touching the lines you can fix them as well :)

2021-07-12 11:04 UTC, hechtlC commented on util-misc.R
> +#' Get a single bin from a range
Please add a .

2021-07-12 11:04 UTC, hechtlC commented on util-read.R
> +        ## fix all dates to be after the creation date.
could you please remove the dot here?

2021-07-12 13:32 UTC, bockthom requested changes
I like this PR @nlschn, really nice improvements to data and splitting functionality of coronet. Good things come to those who wait!

I only found one actual bug and a couple of minor issues regarding documentation and consistency. Please see my comments below.

In addition, if I have seen it correctly, your copyright header is missing in "test-networks-covariates.R". Please don't forget to update that.

2021-07-12 13:32 UTC, bockthom commented on NEWS.md
> +- Change the internal representation of empty data from `NULL` to empty data frames and adapt function `get.cached.data.sources()` of ProjectData which returns a vector of all data sources that are c
Please update the outdated hashes...

2021-07-12 14:14 UTC, nlschn commented on tests/codeface-data/results/testing/test_empty_feature/feature/authors.list
> +4944;"Max";"max@example.org"
I tried this at first, the read fails with "Error: Stopped due to missing authors."

2021-07-12 14:31 UTC, bockthom commented on tests/codeface-data/results/testing/test_empty_feature/feature/authors.list
> +4944;"Max";"max@example.org"
Ah, now I understand the problem here. Thanks for posting the error message. That's indeed not that easy to deal with:

On the one hand, why should there be authors if nobody has committed anything or mailed anything? We, indeed, have a function `create.empty.authors.list()` which would be useless if we wouldn't allow empty authors lists...

However, on the other hand, I know what the reason for this check was: If we have at least some data, we should always have author data: The author data are the only data source which we can use to check whether anything is wrong with the data, assuming that there are data in at least one of the different data sources, resulting also in author data being non-empty.

@hechtlC: We have two options: (1) Keep the check as it is and disallow empty author data as there always must be author data. Or (2) enable empty author data (which would make the empty test data consistent and also increases the value of function `create.empty.authors.list()` but may lead to a problem when author data is not present where it should be present. Let's postpone this discussion to our next meeting.

2021-07-12 15:58 UTC, bockthom commented on tests/test-data.R
> +    proj.conf = ProjectConf$new(CF.DATA, CF.SELECTION.PROCESS, CASESTUDY, ARTIFACT)
Just a quick question: Is the new test on non-empty data a duplication of the test on empty data with just using `CASESTUDY` instead of `CASESTUDY_EMPTY` and adding some configuration updates regarding locking? If these are the only differences, I would like to use a parameterized test instead of having two tests which are almost duplicates.

For parameterized tests, we use `patrick::with_parameters_test_that` and specify different cases afterwards via `patrick::cases(...)` and specifying a list of variables and their values in the respective case. In our test, we should have two different cases: For the one case, we set `test.casestudy` to `CASESTUDY`, and for the other case, we set `test.casestudy` to `CASESTUDY_EMPTY` and use parameter `test.casestudy` in the test. In addition, we need a second parameter `test.locking` which is `TRUE` for the non-empty casestudy and could be either true or false in the empty-case study –– thus, we can easily have a third case to test locking on empty data... –– and we just need to put all the locking-related Conf updates into an `if (test.locking) {...}`. With that, we should be able to reduce the amount of duplicated test code. (For an example on how to use `patrick`, you can have a look at [`test-networks-equal-constructions.R` (lines 90 and 140)](https://github.com/se-sic/coronet/blob/a7f4123dcb86a7a0f76adf791b66a7d9c24f7647/tests/test-networks-equal-constructions.R#L90-L140), I'd guess that should help).

2021-07-12 16:16 UTC, bockthom requested changes

2021-07-12 16:16 UTC, bockthom commented on NEWS.md
> +- Add new configuration parameters `commits.locked`, `mails.locked` and `issues.locked` to ProjectConf which, when set to `TRUE`, prevent the respective getters from triggering the read of the data i
Just a few additions: Commit 364b3a2 still is outdated.
And commit eed45ac is, to the best of my knowledge, not related to the locking stuff. Please update them correctly...

2021-07-12 16:16 UTC, bockthom commented on NEWS.md
> +- Change the internal representation of empty data from `NULL` to empty data frames and adapt function `get.cached.data.sources()` of ProjectData which returns a vector of all data sources that are c
When talking about `is.data.source.cached`, please not only reference the commit in which the usages are introduced (b49cc5df), but please also add the commit in which the function itself was added:
491e70c44dd71e4d51b40ee83bc8eb598d413bc0

2021-07-12 16:22 UTC, nlschn commented on NEWS.md
> +- Add new configuration parameters `commits.locked`, `mails.locked` and `issues.locked` to ProjectConf which, when set to `TRUE`, prevent the respective getters from triggering the read of the data i
Must have pasted the hash at the wrong location. So many hashes...

2021-07-13 09:12 UTC, nlschn commented on tests/test-data.R
> +    proj.conf = ProjectConf$new(CF.DATA, CF.SELECTION.PROCESS, CASESTUDY, ARTIFACT)
> Just a quick question: Is the new test on non-empty data a duplication of the test on empty data with just using CASESTUDY instead of CASESTUDY_EMPTY and adding some configuration updates regarding locking?

No, some of the checks were changed from expect_true to expect_false

2021-07-13 09:18 UTC, bockthom commented on tests/test-data.R
> +    proj.conf = ProjectConf$new(CF.DATA, CF.SELECTION.PROCESS, CASESTUDY, ARTIFACT)
Ok, but then the info "Two identical ProjectData objects." seems to be wrong for some of the checks...

2021-07-13 09:20 UTC, bockthom commented on tests/test-data.R
> +    proj.conf = ProjectConf$new(CF.DATA, CF.SELECTION.PROCESS, CASESTUDY, ARTIFACT)
And also the comment in line 120 "It is always equal" needs to be adjusted then, too.

2021-07-15 09:27 UTC, bockthom requested changes
Almost done: Just some minor adjustments in the new test-README and the adjustment of one test left :smile:

2021-07-15 09:27 UTC, bockthom commented on tests/README.md
> +![coronet](./logo/5.coronet_with_font_radiused_rectangle.png)
This (line 3) does, on the one hand, not work, and on the other hand, is not necessary:

It is enough to have the favicon, we don't need to have the coronet logo displayed at the beginning of this test-README. Instead, I would suggest to have a title:

`# Overview of the Test Projects`

2021-07-15 09:27 UTC, bockthom commented on tests/README.md
> +Please note, that there cannot be a project without author data as in this case, coronet stops when reading the data. Everything else can be empty.
Please highlight `coronet` :wink:

2021-07-15 09:27 UTC, bockthom commented on tests/test-data.R
> +    expect_false(proj.data.one$equals(proj.data.two), "Two identical ProjectData objects.")
Shouldn't this be "non-identical" ?

2021-07-15 09:27 UTC, bockthom commented on tests/test-data.R
> +    expect_false(proj.data.one$equals(proj.data.two), "Two identical ProjectData objects.")
Shouldn't this be "non-identical" ?

2021-07-15 09:27 UTC, bockthom commented on tests/test-data.R
>      expect_true(proj.data.one$equals(proj.data.two), "Two identical ProjectData objects.")
Hm, this confuses me a bit..., I'm not sure if this tests what it is intended to test...
Either let's just state in the comments that both "synchronicity" and "commit messages" are not configured (and therefore we always expect identical objects here), or let's add additional checks actually using synchronicity data and commit messages (then we would need to configure "synchronicity", "synchronicity.time.window", and "commit.messages" in the ProjectConf right before adding such additional checks...)

2021-07-15 11:59 UTC, nlschn commented on tests/test-data.R
>      expect_true(proj.data.one$equals(proj.data.two), "Two identical ProjectData objects.")
I fixed that in both equality tests. This caused the `read.synchronicity` function to be called in the empty data test. Turns out that loading an empty file with `load(file = file)` throws an error, so I added an emptyness check besides the one checking if the file exists in the first place. 
All other functions use some try-catch-like construct that, I think, circumvents this issue, I don't know, why `read.synchronicity` doesn't use that.

2021-07-15 13:07 UTC, bockthom commented on tests/test-data.R
>      expect_true(proj.data.one$equals(proj.data.two), "Two identical ProjectData objects.")
Thanks for adjusting the test descriptions. Unfortunately, I have spotted two minor inconsistencies:
- In line 45, you also should mention "(clone)" as you added it also to the corresponding line in the second test.
- In line 149, the closing bracket is missing "(authors".

In addition, could you try to add further checks to ensure that the data objects are different, for instance, when using another type of "commit.messages"? Currently you use "message", but what happens when using anything else than that? (Sorry that I did not think about that before, but let's try out what happens when "message" is changed to something else – I am not sure what happens then with the commit data or commit message data... Same for changing the synchronicity time window...We don't need to have all of these changes in the test, but we should try it out though manually).

Last but not least: The synchronicity data is a binary R file, so we cannot read a csv file there, but need to load a binary file containing R data frames instead. This is why this is the only situation where we call the `load` function. As loading could fail anyway when the loaded binary does not contain the expected content, we did not have checks for emptiness. But it is good have such a check now.

2021-07-15 13:31 UTC, nlschn commented on tests/test-data.R
>      expect_true(proj.data.one$equals(proj.data.two), "Two identical ProjectData objects.")
`set.commits()` will not trigger `update.commit.messages()` if `commit.messages` are cached, meaning that changing the config parameter does, at the moment, not affect the commits, even when calling `get.commits()` even after changing the config. Is this intended or should I call the update function every time the setter is called (given the parameter is not set to `none`)?

2021-07-15 13:48 UTC, bockthom commented on tests/test-data.R
>      expect_true(proj.data.one$equals(proj.data.two), "Two identical ProjectData objects.")
Hm, good question. We somehow need to handle that, but I don't know how...
Should we automatically take care of that whenever we update the ProjConf? That is, whenever we update the "commit.message" option, then the corresponding update function should be triggered (and also for the other conf parameters) - but we need to make sure that updating only affects the cached data but does not read new data...

@hechtlC Any ideas? Would you agree with calling the update functions when the corresponding parameters are changed?

2021-07-15 13:50 UTC, nlschn commented on tests/test-data.R
>      expect_true(proj.data.one$equals(proj.data.two), "Two identical ProjectData objects.")
I have accidentally deleted the question, sorry
But how I handled it now, is, I reset the commits of one data object manually and re-get the commits

2021-07-15 13:58 UTC, hechtlC commented on tests/test-data.R
>      expect_true(proj.data.one$equals(proj.data.two), "Two identical ProjectData objects.")
Hmm that's a tricky one. But I suppose that since you want to work with the additional data if you configure it later, we could call the update functions immediately. But like @bockthom said, I would not want to change the already cached commit (etc.) data, as it could be that it is modified already and you would not want to change the modification. That is except the adding of the new data source. So yes I agree @bockthom.

2021-07-15 13:58 UTC, bockthom commented on tests/test-data.R
>      expect_true(proj.data.one$equals(proj.data.two), "Two identical ProjectData objects.")
> I have accidentally deleted the question, sorry.

Thanks to e-mails, I can re-post your question again, here it is:

> `set.commits()` will not trigger `update.commit.messages()` if commit.messages are cached, meaning that changing the config parameter does, at the moment, not affect the commits, even when calling `get.commits()` even after changing the config. Is this intended or should I call the update function every time the setter is called (given the parameter is not set to `none)?

So, this was the question to which I responded with "Hm good question..." above...

2021-07-15 16:16 UTC, bockthom commented on tests/test-data.R
>      expect_true(proj.data.one$equals(proj.data.two), "Two identical ProjectData objects.")
I just had a quick look at your most recent commit on that. Let me add one more comment on that:
We should also make sure that the update function is only called once (or, at least, as less frequent as possible), for performance reasons. For instance, in 67e11f4 you adjust the setter function `set.commits` to always call the update function. I am not sure whether we really need to adjust the setter, but, anyway, as the setter might call `get.commit.messages`, which in turn might call the update function, the update function would be called twice from the setter in some of the cases. I would like to avoid that.
But I also have seen now that this problem is not trivial :cry: So what we actually need is (1) to find out in which cases the update function really needs to be called and (2) optimize such that we omit repeated update calls and though get correct results in every situation...

2021-07-15 16:21 UTC, nlschn commented on tests/test-data.R
>      expect_true(proj.data.one$equals(proj.data.two), "Two identical ProjectData objects.")
I think I just forgot to turn it back, but I don't think calling the update function in the setter everytime is not necessarry _anymore_ since I added a call in `set.project.conf.entry` if the parameter is changed.

2021-07-17 12:20 UTC, bockthom commented on util-data.R
>                  if(c("commit.messages") %in% params) {
Missing space after `if`.

2021-07-17 12:20 UTC, bockthom commented on util-data.R
> +            }
First of all, don't worry about the failing test-pipeline in R version 3.3: It seems that package `sqldf` has stopped supporting R version 3.3. (I'll check that in detail later, but I'd assume that we will also need to stop supporting R 3.3 then...)

But let me add a few other thoughts:
- "synhronicity" contains a typo (also below at the other line where you call the update function) (and also the word "mergee" is misspelled in both comments :wink:)
- I am not sure if the update function for pasta and synchronicity works correctly when setting the corresponding parameters `FALSE`. (Remember, for the commit messages, you remove the columns if the parameter is changed, but what do you do when pasta or synchronicity are set to `FALSE`? Do you also remove the columns then, or what else happens in the update function then?
- I'd only call the update functions if the environment was *not* reset (otherwise there is nothing to update). You already implemented it that way in the `update.project.conf` function below, but not in the `set.project.conf.entry` function.

Please make sure that everything mentioned above works as expected. If so, then we either merge although the pipeline fails for R 3.3. or I will send you a patch which you can apply before merging (depends on what I find out regarding sqldf in R 3.3.).

2021-07-17 13:37 UTC, nlschn commented on util-data.R
> +            }
> First of all, don't worry

Okay, thanks for taht information, I thought I broke something again...

> Do you also remove the columns then, or what else happens in the update function then?

I assumed that would be the case, but I can implement this

> You already implemented it that way in the update.project.conf function below, but not in the set.project.conf.entry function.

Yes, I meant to implement it the same way, thanks for pointing that out.

2021-07-17 13:41 UTC, nlschn commented on util-data.R
> +            }
> I am not sure if the update function for pasta and synchronicity works correctly when setting the corresponding parameters `FALSE`

When looking at the `update.commit.messages` function, I believe setting it to `none` doesn't work either. An additional check is needed there as well

2021-07-17 14:28 UTC, bockthom commented on util-data.R
> +            }
Good point! Thanks for also checking that!

I had a quick look at your changes, and, unfortunately, identified to further issues in your last commit:
(1) Please don't use `== TRUE` checks! Just remove `== TRUE` and everything should be fine. You have added several of these checks...
(2) When changing the synchronicity time window, new data has to be read, since we have separate input data for different synchronicity time windows. However, our current implementation just resets the corresponding columns in the commit data, but the private field `synchronicity` is still the old one. Hence, when one changes the synchronicity time window from 5 to 10, one would get still the values from 5. The easiest way would be to reset the environment when the synchronicity time window parameter is changed. However, maybe you find also a way to just remove and trigger re-reading the synchronicity data in such a case? Could you please check for a couple of minutes whether this is possible to achieve? If not, I would go for resetting the environment (to just come to an end here is synchronicity data is not used that often...)

I'm really sorry for spotting new issues again and again :see_no_evil: (I'm not blaming on you, it is just my fault to not think about these issues earlier) I'm really hoping that this synchronicity related issue is the last one I've spotted, maybe I just should stop thinking about this PR after this one is fixed...

2021-07-17 14:35 UTC, bockthom commented on util-data.R
> +            }
And, luckily, even the pipeline for R 3.3 seems to work again :partying_face: There may have been a problem with the availability of certain package versions. Hopefully this does not happen again until this PR will be merged so that I don't have to deal with this problem any more...

2021-07-17 14:46 UTC, bockthom commented on util-data.R
> +            }
> However, maybe you find also a way to just remove and trigger re-reading the synchronicity data in such a case?

Additional comment: This should only happen if the synchronicity data is already cached. If one changes the time window but has not read the synchronicity data yet, we should definitively not read it.

2021-07-17 15:09 UTC, nlschn commented on util-data.R
> +            }
I added another check to the functions that change config parameters (they have gotten a bit lengthy...) that resets and reloads only the synchronicity if 1. the time window changed and 2. synchronicity data is alreay cached.

2021-07-17 15:43 UTC, bockthom approved these changes

2021-07-18 10:46 UTC, hechtlC approved these changes

2021-07-19 06:16 UTC, merged