WIP: Implement Read bot data and filter bots
se-sic/coronet pull request #206
Opened 2021-06-10 03:02 UTC by JoJoDeveloping

- [x] I adhere to the coding conventions (described [here](https://github.com/se-passau/coronet/blob/master/CONTRIBUTING.md)) in my code.
- [X] I have updated the copyright headers of the files I have modified.
- [X] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [X] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](https://github.com/se-passau/coronet/blob/master/NEWS.md) appropriately.
- [X] The pull request is opened against the branch `dev`.

### Description

Aims to implement #202

### Changelog

* Added dummy test file
* Added code to read bot data and merge it into the authors data
* Implement filtering for issues and commits

Yet to do:

* Resolve the actual format of the bot input file as listed in #202 - we currently still include the removed intermediary data
* What are the config options? Do we want commit filtering at all
* Write tests

2021-07-30 17:21 UTC, bockthom requested changes
Hey, nice work @JoJoDeveloping. Looks already good, but I also have a few comments on that (see also my detailed comments below).

Independent from that, I would like to mention a few major issues which need some further investigations or discussions:
- What happens to unfiltered data when adding data from additional data sources? For example: If I enable PaStA, will the PaStA data be merged to just the filtered commit/mail data or also the unfiltered data? (It looks like that the current implementation in this PR only adds it to the filtered data, but I am actually not sure and unfortunately I don't have the time any more to check that. Please also then have a look at the update functions for all the additional data sources and check whether everything works well for both filtered and unfiltered cached data...)
- Can we add an example on how to filter bots manually by calling the corresponding function in the showcase file?
- Shouldn't we add a test case to test `read.bot.info`? It is already tested within the test for reading the author data. But a separate test might be useful just in the case that the procedure on how reading author calls reading the bot information will change. Then it would be useful to test reading the bot information also separately.
- I am not sure whether the default for bot filtering should be `TRUE` or `FALSE`. Please discuss with @hechtlC.

2021-07-30 17:21 UTC, bockthom commented on util-read.R
> +#' Read the bot classification from the 'TODO-bots.list' file.
Please don't forget to update the name.

2021-07-30 17:21 UTC, bockthom commented on util-read.R
> +    file = file.path(data.path, "TODO-bots.list")
Update file name.

2021-07-30 17:21 UTC, bockthom commented on util-read.R
> +    ## read the file with the commit messages
No, we don't read commit messages here...

2021-07-30 17:21 UTC, bockthom commented on util-read.R
> +        logging::logwarn("There is no bot clarification available for the current environment.")
What do you mean by "bot clarification" ? I don't get that. Maybe you find a noun that suits a little bit better.

2021-07-30 17:21 UTC, bockthom commented on util-read.R
> +    ## handle the case that the list of commits is empty
Nope. We don't care if the list of commits is empty here :wink:

2021-07-30 17:21 UTC, bockthom commented on util-read.R
> +    bot.data = bot.data[, c("author.name", "author.email", "is.bot")]
Maybe this is not necessary any more after the update of the bots.list. Please check. If you think it is still useful, we can also keep it.

2021-07-30 17:21 UTC, bockthom commented on util-read.R
> +    return(bot.data)
Why do we have so much blank lines here? One blank line before the logging statement should be enough...

2021-07-30 17:21 UTC, bockthom commented on util-read.R
> +        row.names(authors.df) = 1:nrow(authors.df)
Please address this TODO, (even if I don't know what the TODO comment actually means...)

2021-07-30 17:21 UTC, bockthom commented on util-read.R
>  AUTHORS.LIST.COLUMNS = c(
Shouldn't we add the `is.bot` column here? I am not sure about that, please check. Maybe there are cases where this column is not existent, then we may not need it? 
@hechtlC Please have a closer look at this and how we treat that at other column lists...

2021-07-30 17:21 UTC, bockthom commented on util-read.R
> +    authors.df = authors.df[,c("author.id", "author.name", "author.email", "is.bot")]
Do we really need this?

2021-07-30 17:21 UTC, bockthom commented on util-conf.R
> +            ),
Please don't forget to add this one in the list of configuration options in the README.md file.

2021-08-04 13:53 UTC, hechtlC submitted a review, later dismissed
Nice work @JoJoDeveloping 
I have only found a couple more things in addition to the comments by @bockthom.

One thing I am not really sure about is: In the function `update.pasta.data()`, we check if mails/commits are in the cached data sources. But the functions `update.pasta.commit.data()` and `update.pasta.mail.data` are then working with the filtered data sources. So should this check not rather check for the filtered mail and commit data to be there? Or am I missing something?

Please also don't forget to add you copyright header in `util-networks.R`.

And also please don't forget to rebase your PR to the current dev branch as there are changes.

2021-08-04 13:53 UTC, hechtlC commented on util-data.R
If we only do this for the filtered mails (which I am not quite sure if we decided to do this can you remind me if we decided so?) then you have to change the comment of the function in line 528 from \code{mails} to \code{mails.filtered}

2021-08-04 13:53 UTC, hechtlC commented on util-data.R
> +        #' @param filter.bots flag commits by bots should be removed
There is also a 'whether' missing here

2021-08-04 13:53 UTC, hechtlC commented on util-data.R
> +            )
And if not then please align at the equals sign.

2021-08-04 13:53 UTC, hechtlC commented on util-read.R
>  AUTHORS.LIST.COLUMNS = c(
I guess that really depends on whether we always read the bot data in addition to the author data and merge them or not. If so then yes we should add it. If not then leave it out (just like we do with the pasta columns in mail and commit data)

2021-08-06 09:42 UTC, hechtlC commented on util-data.R
> +        #' @param filter.bots flag commits by bots should be removed
So we discussed this and we think (even though the base artifact filtering is always TRUE as default) that it would be best to have FALSE as default for the bot filtering.
But we can discuss this further after our vacation @bockthom

2021-08-14 02:25 UTC, JoJoDeveloping commented on util-read.R
>  AUTHORS.LIST.COLUMNS = c(
We do not, since this global list describes the file format, and the bot data is not part of the `authors.list` file

2021-08-14 12:09 UTC, JoJoDeveloping commented
The latest commits should have adressed all comments, change request, remainibg TODOs.

2021-08-16 15:28 UTC, bockthom requested changes
Thanks @JoJoDeveloping  for addressing our reviews.
@hechtlC and I today had a joint look over your PR again, and––unfortunately––we spotted a bunch of problems that need to be fixed before we can merge this PR.

First of all, here are some general issues to be fixed:
- [x] Copy `test_feature/feature/bots.list` in the test data also to `test_proximity/proximity/bots.list`
- [ ] Copy `test_feature/feature/issues-github.list` also to `test_proximity/proximity/issues-github.list`
- [ ] Add an example of using the function `filter.bots(...)` to the `showcase.R` (Here we explicitly mean the function `filter.bots(...)`, not the parameter (for the parameter, see the individual comments below.)
- [ ] In the `README.md`, there is a section "Folder structure of the input data". In this section, there is an overview of all `.list` files in alphabetical order. Please add the `bots.list` file there.
- [ ] Add `"is.bot"` to `AUTHOR.LIST.COLUMN` in `util-read.R` (see more details in separate comment)

In addition, please also have a look at the comments below. Don't hesitate to ask or step by in case of questions.

2021-08-16 15:28 UTC, bockthom commented on util-data.R
> +                                                   by = "message.id", all.x = TRUE, sort = FALSE)
Wrong indentation. Previously it was correct.

2021-08-16 15:28 UTC, bockthom commented on util-data.R
> +            if (self$is.data.source.cached("mails.unfiltered")) {
We actually need to do this twice: Once for "mails.unfiltered" and once for "mails". The content of this if-block contains the "mails" variant (as opposed to your change here). So please copy the whole block and adjust it correctly for the other variant.
For consistency reasons, the first one should be "mails.unfiltered" and the second one "mails.filtered".
This comment may sound unintuitive. In case of questions, don't hesitate to ask or step by.

2021-08-16 15:28 UTC, bockthom commented on util-data.R
> +        extract.timestamps = function(name, source) {
The new "name" parameter is not documented.
When adjusting the documentation, please clearly state what the difference between "name" and "source" is and which of the two parameters is used for what

2021-08-16 15:28 UTC, bockthom commented on util-data.R
> +            private$issues.unfiltered = create.empty.issues.list()
Please swap these two lines for consistency reasons.

2021-08-16 15:28 UTC, bockthom commented on util-data.R
> +        get.mails = function() {
This is just copy-paste from the unfiltered getter. Please add some information that this gets the filtered mail data (in a similar way as for the getter of unifiltered and filtered commits...)

2021-08-16 15:28 UTC, bockthom commented on util-read.R
> +    authors.df = authors.df[,c("author.id", "author.name", "author.email", "is.bot")]
Please add a comment to this line that states that we need this line to sort columns correctly :smile: 
And: Missing space in front of and after the comma

2021-08-16 15:28 UTC, bockthom commented on util-read.R
> +        authors.df = authors.df[order(authors.df[["author.id"]]),] # re-order after read
Missing space after the comma

2021-08-16 15:32 UTC, bockthom commented on util-read.R
>  AUTHORS.LIST.COLUMNS = c(
> We do not, since this global list describes the file format, and the bot data is not part of the `authors.list` file

No, that is wrong. For issue data, there is an "event.id" in this global list whereas the event id is not part of the `issues.list` file. Or in the mail data, we have an "artefact.type" column mentioned in the global list, but the "artefact.type" is not part of the "emails.list". For that reason, we should also add the `is.bot` column to the `AUTHORS.LIST.COLUMNS` as this column is always present (regardless of having a `bots.list` file or not). This is different to pasta related columns in the commit or mail data, which are only present when configured. So, lets add `is.bot` as it is always present and also for consistency reasons. @hechtlC also agreed on this.

2021-08-16 15:52 UTC, JoJoDeveloping commented on util-data.R
> +
This one has indeed be tricky.

In my opinion, `get.cached.data.sources` should be private. It is highly dependant on the names of private fields and thus its behavior should not be relied on by other, external functions. The reason it is not private is that it is invoked on the "`other`" argument of `ProjectData::equals`. In sane object-oriented languages, this would not be an issue since one is usually able to invoke private member functions on other objects of one's own type. In R, however, this is not the case, hence this function is public.

There have been a few other places where this function was used, which led to issues during the field renaming process, because again, this function exposes the names of private fields to classes that should not concern themselves with that. (This functionality, however, is useful inside the class since a lot of other methods in `util-data` rely on this duality and I dod not want to rename them all). Thus I added these helper functions, which can be used to ensure external behavior stays consistent when one changes implementation details (which is why I explicitly spell out the possible values, so that future programmers are able to quickly find and fix issues).

Your proposed changes would affect all callsites of `is.data.source.cached`, and I would rather avoid going over all of them.

Ideally, we should mark this function as "Do Not Use".

2021-08-24 14:33 UTC, bockthom reviewed
Good work @JoJoDeveloping. Almost done. I just spotted a few very minor issues you may have overlooked in my previous comments and some newly introduced issues. But no worries, I have added them below again.

And please don't forget to apply the patch @hechtlC has sent you via e-mail.

When these issues are fixed, I will merge this PR right away :smile:

2021-08-24 14:33 UTC, bockthom commented on tests/codeface-data/results/testing/test_feature/feature/bots.list
> +"CLAassistant";"nomail";Bot
Can you please put the last column into quotation marks? e.g. "Bot"
Holds for both "bots.list" files (feature and proximity).

2021-08-24 14:33 UTC, bockthom commented on NEWS.md
> +- Ignore the "deleted user" as wel as the author having an empty name "" (1a08140884f30366995352af315218cfd315b958, 24c222a21238cf0d21dfa750d8c951f39b4d0500)
There is a typo, should be as we**ll** as

2021-08-24 14:33 UTC, bockthom commented on util-read.R
>  AUTHORS.LIST.COLUMNS = c(
The "is.bot" column still is missing in `AUTHORS.LIST.COLUMNS`...

2021-08-24 14:33 UTC, bockthom commented on util-read.R
> +    authors.df = authors.df[,c("author.id", "author.name", "author.email", "is.bot")]
Here still the space after the first comma is missing

2021-08-24 14:33 UTC, bockthom commented on util-read.R
> +        row.names(authors.df) = 1:nrow(authors.df)
Please use `seq_len(nrow(authors.df)` instead of `1:nrow(authors.df)`

2021-08-24 14:33 UTC, bockthom commented on util-data.R
> +            private$issues.unfiltered = create.empty.issues.list()
Please swap these two lines for consistency reasons: For commits and mails, you first mention the unfiltered data and then the main data. Please also adjust the order similarly in lines 153–163, where the fields are defined, to have a consistent order fields everywhere.

2021-08-24 14:33 UTC, bockthom commented on util-data.R
>          #' the earliest and latest date of one data source.
Does this comment regard "data.timestamps" still make sense for the new function? Please check.

2021-08-24 14:33 UTC, bockthom commented on util-data.R
> +        #'                    [default: "all"]
There is no "all" here, so how can "all" be the default?

2021-08-25 09:56 UTC, bockthom approved these changes
Looks good now. And CI pipeline also succeeds. So, I will merge right away.
Thanks for your endurance and your great work @JoJoDeveloping. We are glad to be able to use the new features of coronet soon :smile:

2021-08-25 10:03 UTC, merged