Add check to get.first.activity.data to look for missing activity types
se-sic/coronet pull request #220
Opened 2022-02-02 17:24 UTC by nlschn

Adresses issue #217

Signed-off-by: Niklas Schneider <s8nlschn@stud.uni-saarland.de>

### Prerequisites

- [x] I adhere to the coding conventions (described [here](../CONTRIBUTING.md)) in my code.
- [ ] I have updated the copyright headers of the files I have modified.
- [x] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [x] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](../NEWS.md) appropriately.
- [x] I have checked whether I need to adjust the showcase file `showcase.R` with respect to my changes.
- [x] The pull request is opened against the branch `dev`.

### Description

Add check to `get.first.activity.data` function in `util-networks-covariates.R` to check whether there are activity types that configured but not present in the given data.

If there are no activities at all, print a warning and return an empty list immediately. If there are activity types missing but also some present, copy an entry from a present key, replace its elements with `NA`, and add that list for each missing key (This is referred to as the "quick and dirty solution" in #217...). Also print a warning in this case.

This pull request addresses #217.

2022-02-03 10:15 UTC, nlschn commented
There seems to be a problem when `present.keys` has no elements. In these test cases the result (returning an empty list as there is no data for the configured activity types) does not match the expected result.

2022-02-03 16:35 UTC, bockthom commented
> There seems to be a problem when `present.keys` has no elements. In these test cases the result (returning an empty list as there is no data for the configured activity types) does not match the expected result.

How can it happen that `present.keys` has no elements? This could only happen when there is no data available, as far as I understand. The failing tests call the function `get.network.covariates.test.networks`, which returns a list containing a `networks` and a `project.data` element. Within this function, there also is a variable [`input.data`](https://github.com/se-sic/coronet/blob/a65602663efbe208e201e39418a42d8151903bbb/tests/test-networks-covariates.R#L84) which contains the data for separate ranges. It could be the case, that some of the data of interest (e.g. "mails") may be empty in one the ranges, which could cause the data to be empty when we choose `activity.by.type = "mails"`. This might be a case in which no `present.keys` are available, but I am not sure how this case was handled before. Therefore, we need to find out what happens now and what we have expected.

To find out where exactly this problem actually occurs, I suggest to debug one of the failing tests, e.g., line 1028 in `test-networks-covariates.R`:
https://github.com/se-sic/coronet/blob/a65602663efbe208e201e39418a42d8151903bbb/tests/test-networks-covariates.R#L1028-L1037
As we are iterating over several lists in this test, it is not that easy to find out where exactly the problem occurs. In a first step, we need to find out for which `AGGREGATION.LEVELS` it happens and then for which list element of the attributes list.
At the moment, I only  have two ideas in mind, how to come to an end fast: (1) Print the `level` to see in which level we get the (first) error, and (2) print the actual and expected attributes list to see where exactly there is a difference in the list (maybe using a diff-tool to be able to spot the difference in the string representations of the two lists...)

2022-02-04 12:29 UTC, nlschn commented
> How can it happen that present.keys has no elements? This could only happen when there is no data available, as far as I understand.

It is also possible if there is data available, but not for the types given in the parameter `activity types`.

2022-02-04 12:31 UTC, bockthom commented
> It is also possible if there is data available, but not for the types given in the parameter `activity types`.
This is true. So with "no data" I meant "no data for the chosen activity types".

2022-02-11 09:49 UTC, bockthom requested changes
Thanks for this PR @nlschn. During my review I identified that the change we have applied together yesterday (namely, adding `names(activity.by.type) = activity.types`) breaks the rest of the implementation as the identification of missing keys does not work any more since we have added the names before... Sorry for my wrong suggestion yesterday, yesterday I did not check what we do afterwards...
However, I have a suggestion which might circumvent this problem; please see my comments below. (In addition, there are also just a few formatting inconsistencies.)

As soon as you have changed your implementation such that it works again, I will try whether the implementation also works in the situation in which I spotted the bug, just to make sure that everything works as expected then.

2022-02-11 09:49 UTC, bockthom commented on util-networks-covariates.R
> +    ## if activity.by.type is null or the list is empty, print a warning and return an empty list
Could you please use `'` around variable names in comments? So here it should be `'activity.by.type'`.

2022-02-11 09:49 UTC, bockthom commented on util-networks-covariates.R
> +    present.keys = intersect(names(activity.by.type), activity.types)
Does this part of the implementation still make sense? As we set `names(activity.by.type) = activity.types` a view lines above, the `setdiff` will always be empty by construction and `intersect` will always end up in `activity.types`.

So, what I see from now is that we do not even need to to set  `names(activity.by.type) = activity.types` as we don't need the names. Instead of `present.keys`, we could just use `activity.types` in the statement below:

```R
present.keys = present.keys[!is.na(activity.by.type[present.keys]) & length(activity.by.type[present.keys]) > 0]
append(missing.keys,
        present.keys[is.na(activity.by.type[present.keys]) | length(activity.by.type[present.keys]) == 0])
```
In addition, you append the missing keys after removing some present keys from `present.keys` here. The order of these statements should be switched, shouldn't it?
This should work then (if I don't have overlooked anything...)

2022-02-11 09:49 UTC, bockthom commented on util-networks-covariates.R
> +    ## missing
Could you please use just one line for the comment? We allow 120 characters per line, so it should fit into one line, I guess. (And don't forget to update the comment if "present keys" will not exist any more...)

2022-02-11 09:49 UTC, bockthom commented on util-networks-covariates.R
> +        return(list(NA))
What is the reason for returning `list(NA)` here? A few lines above, you return just `list()` after the null check. Is this difference intended? If so, please explain somewhere in the comments and also update the function documention `@return` as there you only mentioned returning an empty list.

2022-02-11 09:49 UTC, bockthom commented on util-networks-covariates.R
> +    ## can work it out
This comment should also fit into one line, I guess (but my guess can also be wrong :wink:)

2022-02-11 09:49 UTC, bockthom commented on util-networks-covariates.R
> +    na.list = lapply(activity.by.type[present.keys[[1]]], function (x) NA)
Could you please remove the space between `function` and the opening parenthesis? 

In addition, according to our contribution guide, we "always use the function `return()` to return a value from a function", so please use `return(NA)` here :wink:

2022-02-11 09:49 UTC, bockthom commented on util-networks-covariates.R
> +                                 "activities of that type"), sep = " "))
I guess we can also put this into two lines instead of three :wink:

2022-02-16 13:14 UTC, nlschn commented on util-networks-covariates.R
> +    ## can work it out
No, it has 133 chars. 😂

2022-02-16 13:21 UTC, nlschn commented on util-networks-covariates.R
> +    present.keys = intersect(names(activity.by.type), activity.types)
I need the `present.keys` to find the candidates I can copy the list from, if I remember correctly. But apart from that, you're right.
Did I understand you correctly that new assignment of the names `names(activity.by.type) = activity.types` should be kept?

2022-02-16 13:31 UTC, bockthom commented on util-networks-covariates.R
> +    ## can work it out
Damn! Then my visual estimation was far off.
Maybe it would be a better idea if I abstain from such visual estimations in the future...:joy:

2022-02-16 13:35 UTC, bockthom commented on util-networks-covariates.R
> +    present.keys = intersect(names(activity.by.type), activity.types)
Right. We don't need the names, so we could remove them. But it may help for future debugging to keep the names... Remember that we've struggled with the example in the comments above as there we had names but did not have the names in the resulting list. So, to prevent struggling with the names again, we can just keep it.

2022-02-16 20:33 UTC, bockthom commented on util-networks-covariates.R
> +                                      length(activity.by.type[activity.types]) == 0]
Please spell `NA` in the comment with upper case letters.
And please fix the indentation in the second line such that the `l` of length and the `i` of is.na align.

The rest looks good so far. That's all for today. I will think about the correctness of the new implementation tomorrow with a fresh mind :wink:

2022-02-17 08:04 UTC, bockthom commented on util-networks-covariates.R
> +                                      length(activity.by.type[activity.types]) == 0]
I had a closer look at the new implementation again, and I take the view that it now should work as intended :partying_face: 

The only issue I spotted targets the comment again: "check for keys whose member lists are not empty or NA" - but aren't you looking for empty keys here? So the "not" in the comment is wrong, isn't it?

Before merging, I will check out the new implementation and apply it to to the cases where the previous implementation failed. Let's see if it solves the issue, but I am pretty confident in that. Though, I cannot predict when I will find time to try it out, but @hechtlC can already start reviewing this PR.

2022-02-17 20:05 UTC, bockthom requested changes
I am very very sorry, but I have bad news :astonished: :speak_no_evil: 

After spending more than an hour on figuring out in which project the problem this PR deals with occurs, I had to notice that the new implementation still does not prevent the error that it should fix...

I identified two lines in the implementation which make the new fix ineffective:  (1) The check for missing keys does not cover the missing keys in the situation in which the bug occurs. (2) The replacement with `NA` replaces a complete list by `NA` instead of replacing each element by `NA`. See details on that below.

I have to admit that I did not spot these problems in the code and, moreover, that I did not remember all details of the problematic behavior. It would have been better to store a error dump containing the whole environment in which the bug occurs when creating issue #217 to have some test data available for easily dealing with the situation. :see_no_evil:  Next time, I'll do better, hopefully...

@nlschn I will try to derive real input data from the real situation in which the bug occurs and provide it to you, such that you can use the provided data to play around with and fix the currently ineffective statements. (I don't know why didn't I do this earlier...) However, I am not sure whether I can do this tomorrow, but I'll get back to you next week at latest. But there is no rush, you might also be busy with other, more important, tasks at the moment anyway.

2022-03-03 13:05 UTC, bockthom requested changes
Thanks for the fix @nlschn. 

Fortunately, determining the missing keys works as expected now. Since `missing.keys` are determined correctly now, the corresponding warning is printed correctly, but I spotted a formatting issue when the warning is to be printed. Please see my suggestion on how to prevent this below.

Unfortunately, computing the `na.list` still does not work, ending up in wrong results and an error when accessing the result afterwards. Please see the details below.

2022-03-03 13:05 UTC, bockthom commented on util-networks-covariates.R
> +    na.list = lapply(activity.by.type[present.keys[[1]]], function(x) return(NA))
Unfortunately, `na.list` still is wrongly. This ends up in a completely weird result:
If mails and commits are empty, we expect something like 
```R
list(
    authorA = list(commits = NA, mails = NA, issues = <date-retrieved-from-issues>),
    authorB = list(commits = NA, mails = NA, issues = <date-retrieved-from-issues>), 
    ...
)
```
However, what we currently get is the following:
```R
list(
    authorA = list(commits = <date-retrieved-from-issues>, mails = NA),
    authorB = list(commits = <date-retrieved-from-issues>, mails = NA, 
    ...
)
```
I don't know how this can happen, but the result is ill-formated (issues are missing) and wrong (the `issue` date occurs at `commits` although there should be an `NA`). Although no error is thrown during the function call, accessing the returned data afterwards still ends up in an error...

So, the problem still seems to be the creation of the `na.list`: Currently when setting `activity.by.type[missing.key] = na.list` we get `list(mails=NA)`, but what we need is `list(authorA = list(mails = NA), authorB = list(mails = NA))`. So, when creating `na.list`, we need to create a `list(mails = NA)` for every author entry...

2022-03-28 12:00 UTC, bockthom requested changes
Thanks for the new test @nlschn. The test looks good and correct, but it does not test the corner cases we need to test. So, I would like to keep this test and add another one addressing the corner case. See the details in the comments below (beside some comments addressing formatting issues).

2022-03-28 12:00 UTC, bockthom commented on tests/test-networks-covariates.R
> +#' Test addition of attributes despite of non-captured vertices
Could you please add a blank line between `## Unit tests for ...` and `#' Test addition...` as one comment describes the section and the other comment describes the test function.
In addition, both @hechtlC and I don't understand the description of the test function "Test addition of attributes despite of non-captured vertices". So, fist of all, there are no vertices in this test as it does not test networks but just data aggregation. Hence, the second part of this sentence could be something like "without creating networks". And please also rephrase the beginning "Test addition of attributes". There is no need to say that this is a test addition, it actually is a stand-alone test. So, please just describe what is tested here.

2022-03-28 12:00 UTC, bockthom commented on tests/test-networks-covariates.R
> +    ## lists
Please re-format this comment. As it is a multi-sentence comment, please add periods to mark the end of the sentences.
In addition, the single word in the last line looks a bit lost. Please adjust that. And also remember to add single quotation marks when using variable names, so it should be `'proj.data.base'`.

2022-03-28 12:00 UTC, bockthom commented on tests/test-networks-covariates.R
> +                                                c(timestamps[["start"]][[1]], timestamps[["end"]][[1]]))[[1]]
Please adjust the indentation of the second line to the ( of the function call.

2022-03-28 12:00 UTC, bockthom commented on tests/test-networks-covariates.R
> +                     issues = get.date.from.string("2013-05-05 21:46:30")),
Please adjust the indentation.

2022-03-28 12:00 UTC, bockthom commented on tests/test-networks-covariates.R
> +                    issues = get.date.from.string("2013-05-25 03:25:06")),
Please adjust the indentation

2022-03-28 12:00 UTC, bockthom commented on tests/test-networks-covariates.R
> +             mails = get.date.from.string(" 2016-07-12 15:58.50"),
Please remove the space at the beginning of the character string and also replace the dot which is separating minute and second by a colon :wink:

2022-03-28 12:00 UTC, bockthom commented on tests/test-networks-covariates.R
> +                                      "udo", "Karl", "Max")
Could we even put the names directly in the list above? For instance, as follows:
```R
"Björn" = list(commits = ...
```
This would make understanding the test easier.

2022-03-28 12:00 UTC, bockthom commented on tests/test-networks-covariates.R
> +    expect_equal(first.activity.data, expected.activity.data)
This test is correct and very useful, but it does not yet test the corner case for which we have fixed the bug in the function `get.first.activity.data`.
So, please add a second test case below, for which one or even two of the data sources need to be empty for every developer. So, for instance, call `set.issues(create.empty.issues.list())` and `set.mails(create.empty.mails.list())` before calling `get.first.activity.data`. Only in these cases we test the new behavior. The test above would also have worked before the bug fix yet.

2022-03-28 15:10 UTC, nlschn commented on tests/test-networks-covariates.R
> +    expect_warning(first.activity.data <- get.first.activity.data(range.data))
But why does the test still pass instead of output the result "Warning"?

2022-03-28 15:14 UTC, bockthom commented on tests/test-networks-covariates.R
> +    expect_warning(first.activity.data <- get.first.activity.data(range.data))
Unfortunately, the test does not pass (at least, in the CI pipeline). The test ends up in an error as no warning is thrown. So, I don't really understand your question.

2022-03-28 15:21 UTC, nlschn commented on tests/test-networks-covariates.R
> +    expect_warning(first.activity.data <- get.first.activity.data(range.data))
This is strange as it passes on my computer with the `expect_warning` line and without it I get
```
Warning (test-networks-covariates.R:1490:5): Test get.first.activity.data with missing commits and mails for all authors
one argument not used by format 'The type mails was configured but the RangeData did not cotain any activities of that type'
```
and another one similar to this for the second warning.

2022-03-28 15:33 UTC, bockthom commented on tests/test-networks-covariates.R
> +    expect_warning(first.activity.data <- get.first.activity.data(range.data))
Hm, strange. Let me try this out also on my computer to see what happens there, but I don't know when I will find some time to do that, maybe tonight, but I cannot promise that. Anyway, I'd assume that we will end up removing this check as it won't work. But still let's give it a try.

As all the other (really important) issues seem to be fixed now, I will request a review for this PR from @hechtlC now.

2022-03-28 15:42 UTC, bockthom commented
@nlschn  As PR #221 has been merged to `dev` in the meanwhile, please rebase your branch onto the current `dev` branch, and don't forget to update your already added commit hashes in the `NEWS.md`.

2022-03-28 16:03 UTC, bockthom commented on NEWS.md
> +- Add check to `get.first.activity.data` to look for missing activity types. If no activities are in the RangeData, the function will print a warning and return an empty list (PR #220, #217, 57075176
It looks like that you have omitted to replace the third hash, as it is still the same as before.

In addition, please add the following two commits (which you have authored after your previous update to the changelog):
ca8a1b4c628261dcb471e1da3603439e75e4cc56
f6553c6106e5fec3837c6edb906a4d0960c5c5fb

2022-03-30 08:48 UTC, hechtlC approved these changes
The pull request looks good now. I just found one typo. Please fix that and then apply the patch that I will send you. Then it can be merged.

2022-03-30 08:48 UTC, hechtlC commented on util-networks-covariates.R
> +        logging::logwarn(paste("The type", missing.key, "was configured but the RangeData did not cotain any",
contain not cotain :)

2022-03-30 12:22 UTC, bockthom commented on tests/test-networks-covariates.R
> +    expect_warning(first.activity.data <- get.first.activity.data(range.data))
Just a final note on this discussion about warnings: I debugged and researched on that. There actually seems to be no way to handle warnings as expected by 'testthat'.
- First of all, the `expect_warning` call only is supposed to work on `warning` calls but not on any warning logs such as `logging::logwarn`.
- Second, there is no possibility to prevent `testthat` from counting and reporting warnings. So, warnings cannot be ignored. The only way for warnings not being reported by `testthat` would be a `suppressWarnings(...)` call around each statement that is expected to print a warning. However, this has two drawbacks: When calling `suppressWarnings`, the warnings will also be removed from the log. And `suppressWarnings` also breakes the `CheckReporter` of `testthat`, resulting in not reporting any information about failed and successful tests. Hence, if we want the test results to be properly reported, we must not used `suppressWarnings`.

Summary: We neither can check for warnings printed via `logwarn`, nor can we `testthat` make ignore the warnings in the report. Consequently, we have to stick to the current implementation (although I would have liked to find another solution).

2022-03-30 12:30 UTC, bockthom approved these changes
Everything looks good now. Thanks again @nlschn for your efforts.
I have also run the current implementation on the projects for which calling `get.first.activity.data` formerly broke, and now it runs successfully!

So, I will merge this PR soon, as the CI test runs are successful (even though the CI pipeline, for most R versions, fails - but it fails for three different reasons which I had debugged last night. I will probably fix these CI issues on various R versions next week, after this PR has been merged, hopefully, such that we will see the green check mark soon again :smile: )

2022-04-06 16:11 UTC, merged