Draft: Test PaSta + Synchronicity, (planned: equality of different network constructions)
se-sic/coronet pull request #226
Opened 2022-05-30 17:46 UTC by joba00002

### Prerequisites

- [x] I adhere to the coding conventions (described [here](../CONTRIBUTING.md)) in my code.
- [ ] I have updated the copyright headers of the files I have modified.
- [x] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [x] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](../NEWS.md) appropriately.
- [ ] I have checked whether I need to adjust the showcase file `showcase.R` with respect to my changes.
- [x] The pull request is opened against the branch `dev`.

### Description

### Changelog

2022-06-05 15:15 UTC, joba00002 commented
As it turns out, despite three existing tests asserting just that, `split.networks.time.based` and splitting a multinetwork and extracting the author and bipartite network out of that do not generally result in the same networks.

This can be seen in the sample data by choosing author.relation = 'cochange' and artifact.relation = 'mail'.

The difference is in how isolated nodes are treated.
I suspect that the existing tests only worked because with our sample data, there were no isolated nodes.

2022-06-05 15:20 UTC, joba00002 commented
It might still make sense to assert that networks are equal when setting `remove.isolates = FALSE`. Unfortunately, this currently does not work as `extract.bipartite.network` has no such option.

2022-06-05 17:17 UTC, joba00002 commented
> It might still make sense to assert that networks are equal when setting `remove.isolates = FALSE`. Unfortunately, this currently does not work as `extract.bipartite.network` has no such option.

I have added this option and changed the tests to use it.

2022-06-07 07:10 UTC, bockthom commented
> As it turns out, despite three existing tests asserting just that, `split.networks.time.based` and splitting a multinetwork and extracting the author and bipartite network out of that do not generally result in the same networks.
> 
> This can be seen in the sample data by choosing author.relation = 'cochange' and artifact.relation = 'mail'.
> 
> The difference is in how isolated nodes are treated. I suspect that the existing tests only worked because with our sample data, there were no isolated nodes.

First of all, sorry for the late reply. Our mail servers have not been available and are (still!) not available. So, I might not directly notice when there are new postings.

Thanks for spotting all these inconsistencies and bugs, also thanks for adding a `remove.isolates` parameter for bipartite networks, sounds good!

I will probably have a look at your changes today or tomorrow, but can you please briefly explain what exactly the difference is in how "isolated nodes are treated"? Knowing that would be helpful for understanding and reviewing your changes.

2022-06-08 09:15 UTC, joba00002 commented
The difference is whether, or rather when, isolated nodes are removed.

Removing isolated nodes first and then splitting may lead to a different result than splitting first and then removing isolated nodes.

2022-06-22 13:20 UTC, hechtlC approved these changes
Looks good to me thank you @joba00002! I have just identified a couple small things that can be addressed quickly and after you have done that I am fine with merging this. @bockthom will also review so maybe wait with these changes until you have the notes from him.

2022-06-22 15:31 UTC, bockthom reviewed
Looks also good to me @joba00002.

I have only two aesthetic comments:
- Removing the row names using two nested lapply calls occurs multiple times in the adjusted tests. Might be worth to extract a helper function for that, as this would increase the readability and understandability of the tests.
- In the tests, where you needed to adjust the expected data (as row names have changed), I would like to keep the previous row name as a comment at the end of the line, as the previously used row names map to the row names in the *.list files (if I remember correctly), which would ease manual debugging with the test data.

Please see my comments below, most of them deal with the two aesthetic problems mentioned above.

2022-06-22 15:31 UTC, bockthom commented on tests/test-split-data-time-based.R
> +            "2016-07-12 16:04:59-2016-07-12 16:06:33" = data$mails[16, ]
Same as above.

2022-06-22 15:31 UTC, bockthom commented on tests/test-split-data-time-based.R
> +    }))
Same as above.

2022-06-22 15:31 UTC, bockthom commented on tests/test-split-data-time-based.R
> +            "2013-10-10 00:38:13-2016-07-12 16:05:38" = data$mails[13:16, ]
Same as above.

2022-06-22 15:31 UTC, bockthom commented on tests/test-split-data-time-based.R
> +    }))
Same as above.

2022-06-22 15:31 UTC, bockthom commented on tests/test-split-data-time-based.R
> +            "2016-04-21 17:52:09-2017-05-23 12:32:40" = data$mails[13:16, ]
Same as above.

2022-06-22 15:31 UTC, bockthom commented on tests/test-split-data-time-based.R
> +    }))
Same as above.

2022-06-22 15:31 UTC, bockthom commented on tests/test-split-data-time-based.R
> +            "2016-01-12 00:19:09-2017-05-23 12:32:40" = data$mails[13:16, ]
Same as above.

2022-06-22 19:36 UTC, joba00002 commented on tests/test-split-data-time-based.R
> +    }))
I thought the same thing, so `testing-utils.R` is where they are for now.
If we find a use for them outside of testing, it is easy to move them to `util-misc.R`.

I'm also not completely happy with the names, as they are very long. I couldn't think of anything shorter that describes what they do, though.

2022-06-22 20:49 UTC, bockthom requested changes

2022-06-22 20:49 UTC, bockthom commented on tests/testing-utils.R
> +#' @returns the list of range data objects, but without row names
To be more precise: ...but without row names for their dataframes

2022-06-22 20:52 UTC, bockthom commented on tests/test-split-data-time-based.R
> +    }))
It is always a big hassle to find proper function names that are precise and short. So, for me, the names are ok. @hechtlC What's your opinion on that?

2022-06-29 09:18 UTC, hechtlC commented on tests/test-split-data-time-based.R
> +    }))
How about `remove.row.names.from.inner.list.of.dfs`?

2022-06-29 09:19 UTC, hechtlC commented on tests/testing-utils.R
> +#' @returns the list of dataframes, but without row names
Please remove the s from returns.
Same for the next function.

2022-07-04 07:06 UTC, bockthom reviewed
Almost done :wink: I just spotted two sentences in the function documentation of the function we have renamed. Please fix them and then I will merge right away.

2022-07-04 07:06 UTC, bockthom commented on tests/testing-utils.R
> +#' Remove the row names in a list of lists of dataframes, for example a list of range data objects.
Could you please describe more precise from where the names are removed:
"Remove the row names from the dataframes in a list of ...."

2022-07-04 07:06 UTC, bockthom commented on tests/testing-utils.R
>  #' @return the list of range data objects, but without row names for their data frames
The description of the return value needs to be updated as it still talks ab out "range data objects".

2022-07-04 13:45 UTC, bockthom approved these changes
Looks good!

2022-07-04 13:46 UTC, merged