Support arbitrarily defined revision ranges
se-sic/coronet pull request #227
Opened 2022-06-28 09:06 UTC by joba00002

Addresses #36

### Prerequisites

- [x] I adhere to the coding conventions (described [here](../CONTRIBUTING.md)) in my code.
- [x] I have updated the copyright headers of the files I have modified.
- [x] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [x] I have put signed-off tags in *all* commits.
- [x] I have updated the changelog file [NEWS.md](../NEWS.md) appropriately.
- [x] I have checked whether I need to adjust the showcase file `showcase.R` with respect to my changes.
- [x] The pull request is opened against the branch `dev`.

### Description

### Changelog

2022-07-04 10:20 UTC, bockthom requested changes
This PR looks good so far. I have had a look at all the changes (except for the splitting test, for which I need to have a bit more time). Please see my minor comments attached.

2022-07-04 10:20 UTC, bockthom commented on util-data.R
> +        custom.event.timestamps = list(),
Please add the comment "# list" to be consistent with the other lines (even if this is obvious here that this is a list)

2022-07-04 10:20 UTC, bockthom commented on tests/test-data.R
> +})
Can we also test afterwards whether clearing the timestamps works correctly? So just updating the conf in such a way that the timestamps are cleared?

2022-07-12 13:39 UTC, joba00002 commented on tests/README.md
> +     * Custom event timestamps in `custom-events.list`
It does fail when "revisions.list" is empty, as an empty file also produces a `try-error`.

2022-07-20 08:16 UTC, bockthom requested changes
Looks good, I just spotted a few minor issues; please see my comments below.

2022-07-20 08:16 UTC, bockthom commented on README.md
> +    * **Note** It might make sense to keep several lists of timestamps for different purposes. Therefore, this is the only data source where the file name can be configured.
Maybe add another note that there is no default value for this parameter?

2022-07-20 08:16 UTC, bockthom commented on util-split.R
> -#'                       [default: FALSE]
Could you please not only remove parameter documentation, but also the parameter itself from the function and its implementation?

2022-07-20 08:16 UTC, bockthom commented on util-split.R
> +#' @param project.data the *Data object from which the data is retrieved
Why does the "*" come from?

2022-07-20 08:16 UTC, bockthom commented on util-split.R
> +#'             [default: NULL]
Could you please move the default value to the end of the previous line?

2022-07-20 08:17 UTC, bockthom commented on util-split.R
> +#' If timestamps are not provided, the custom timestamps in \code{project.data} are
custom timestamps --> custom event timestamps

2022-07-20 08:18 UTC, bockthom commented on tests/test-split-data-time-based.R
> +    results = split.data.time.based.by.timestamps(project.data)
Maybe adjust the comment to "split data by custom event timestamps" to make more obvious what is tested here.

2022-07-20 08:32 UTC, joba00002 commented on util-split.R
> +#' @param project.data the *Data object from which the data is retrieved
I'm not sure either, but this is consistent with the other splitting functions.

2022-07-26 13:42 UTC, hechtlC requested changes
Looks good so far thanks @joba00002!
I just have some minor issues with line length that have to be addressed. Please do that and then we can talk tomorrow.

2022-07-26 13:42 UTC, hechtlC commented on util-data.R
> +            if (!self$is.data.source.cached("custom.event.timestamps") && !private$project.conf$get.value("custom.event.timestamps.locked")) {
This line is too long as well.

2022-07-27 12:23 UTC, hechtlC submitted a review, later dismissed

2022-07-27 13:36 UTC, bockthom commented on NEWS.md
> +- Add function `split.data.time.based.by.timestamps` to allow using custom event timestamps for splitting. Alternatively, timestamps can be specified manually (PR #227, 051db9a5b81bf0d77805355611ef9f
I just checked the commit hashes mentioned here (prior to merging) and have two suggestions:
(1) Why do you mention commit 051db9a5b81bf0d77805355611ef9f1a61f15b18 at all? This behavior which is not present in any release and never was active as you have completely removed this afterwards. Therefore, I would suggest to just omit this commit hash in the news.
(2) Commit hash c5f5403430d55ceff6b6d5acbbca1ae9c5c231e2 is mentioned in both bullet points – this commit just changes the README. I understand why you have added the hash for "incorporate custom event timestamps", but I don't get why you mention this also in the bullet point regarding splitting – there is no change regarding splitting in the README, or do I miss something?

2022-07-27 16:14 UTC, bockthom approved these changes
Looks good. Approved now :smile:

2022-07-27 16:15 UTC, merged