Tests for multi-artifact networks
se-sic/coronet pull request #228
Opened 2022-07-25 11:27 UTC by joba00002

Addresses #122.

### Prerequisites

- [x] I adhere to the coding conventions (described [here](../CONTRIBUTING.md)) in my code.
- [x] I have updated the copyright headers of the files I have modified.
- [x] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [x] I have put signed-off tags in *all* commits.
- [x] I have updated the changelog file [NEWS.md](../NEWS.md) appropriately.
- [x] I have checked whether I need to adjust the showcase file `showcase.R` with respect to my changes.
- [x] The pull request is opened against the branch `dev`.

### Description

### Changelog

2022-07-27 16:18 UTC, bockthom requested changes
In general, this PR looks good, I just spotted two minor issues (under the condition that the expected edges and vertices in the tests are correct. However, I did not yet check the expected edge and vertex data yet...

2022-07-28 12:25 UTC, hechtlC requested changes
Thanks @joba00002 looks good so far. @bockthom and I just went through one of the tests in detail and think that it does what it should :).
We have just identified one consistency issue (see comment). Once this and the other open comments are addressed, this can be merged.

2022-07-28 12:25 UTC, hechtlC commented on tests/test-networks-multi-relation.R
> +           weight = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
Please use `rep()` for all these repeating things in all of the following tests, just like you did in the first test.

2022-08-05 18:53 UTC, bockthom approved these changes

2022-08-05 18:56 UTC, merged