Add input validation for setter and read functions
se-sic/coronet pull request #231
Opened 2023-01-10 13:00 UTC by MaLoefUDS

### Prerequisites

- [ ] I adhere to the coding conventions (described [here](../CONTRIBUTING.md)) in my code.
- [ ] I have updated the copyright headers of the files I have modified.
- [ ] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [ ] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](../NEWS.md) appropriately.
- [ ] I have checked whether I need to adjust the showcase file `showcase.R` with respect to my changes.
- [ ] The pull request is opened against the branch `dev`.

### Description

### Changelog

2023-01-12 16:19 UTC, bockthom reviewed
Thanks @MaLoefUDS, this PR looks really good so far! I only spotted a few inconsistencies in comments that should be fixed, please see my individual comments below.

In addition, there is one data source we have not talked about yet: The custom event timestamps. We also should validate the inputs for its setter and read functions, although it is a little bit different than the other data sources:

`read.custom.event.timestamps`: This function reads a data.frame with two columns – one is of type character, the other one of type POSIXct. We should check this directly after reading it. However, there are no constants and no column names, as this data format is not used outside of the read function. So there should be only hardcoded checks within this function. Because at the end, the read data.frame is transferred to a named list prior to returning.

`set.custom.event.timestamps`: This function just takes a list as parameter. So we should just check whether the input is a list.

So, could you please add the validation for these two special cases?

And please don't forget to add the description for this PR (you don't need to add a changelog there).

2023-01-12 16:19 UTC, bockthom commented on tests/test-misc.R
> +## Copyright 2023 by Maximilian Löffler <s8maloef@stud.uni-saarland.de>
Please write `2022-2023` as you have already started to work on that in 2022. (Also holds for the other files on which you have worked in 2022 already.)

2023-01-16 12:41 UTC, bockthom requested changes
I just spotted two issues regarding the new checks for the custom event timestamps. Please fix them, everything else looks good to me.

(And don't worry about the failing CI pipeline on GitHub. There are some temporary problems at our CI provider that let the CI pipeline always run into a timeout before starting the tests. Just ignore the pipeline for the moment and just make sure that the tests run successfully on your end.)

2023-01-16 12:41 UTC, bockthom commented on util-read.R
> +    }
At this stage, the character check is superfluous: `names` always returns a character vector. And when the names are set, whatever the input is, `names` transfers it to characters. 

Therefore, we either remove this particular check (as it is always a character, we don't need to check here) - or we perform the check before calling `names` for the first time. But it could also be that the names are integers at the time of reading it, so we would also have to cast it to characters in this case. So, maybe is a better option to not check the names column at all.

2023-01-16 12:41 UTC, bockthom commented on util-read.R
> +            })
We have a function that covers the conversion to POSIXct already and does all the error handling and handling of special cases etc. 
Therefore, this `sapply` call is not necessary, as the function `get.date.from.string` does this already and is already called below when sorting the timestamps.

So, it should be enough to check at the end of this function (right after the sorting, within the if-block) whether `class(unlist(timestamps))` is `"POSIXct"` (only if the list is not empty).

2023-01-17 11:38 UTC, hechtlC approved these changes
Looks good, thanks @MaLoefUDS . I just found one line that has more than 120 characters. Once this is fixed and the annotations by @bockthom are processed, we can merge this.

2023-01-17 11:38 UTC, hechtlC commented on util-misc.R
> +        error.message = sprintf("If specified, the length of the two given vectors 'columns' and 'data.types' must match.")
This line has more than 120 allowed characters. Please split the line

2023-01-18 11:35 UTC, MaLoefUDS commented on util-read.R
> +            })
As discussed I will replace the original check by a check for `NA` as `get.date.from.string` will return a `NA`  on a wrongly formatted string :).

2023-01-18 12:34 UTC, bockthom reviewed
Looks good, thanks!

(I only spotted one minor indentation inconsistency)

2023-01-18 12:35 UTC, MaLoefUDS commented on util-misc.R
> +        "'columns' and 'data.types' must match."))
Will do directly!

2023-01-18 12:39 UTC, bockthom commented on NEWS.md
> +- Fix check for empty input-files in utility read functions. Compared to unpresent files, empty files do not throw an error when reading them, a check for `nrow(commit.data) < 1` is therefore require
I just noticed that the PR number is 231 and not 208. Please fix that in the news.md (and add a comma after the PR number).

2023-01-18 12:41 UTC, MaLoefUDS commented on NEWS.md
> +- Fix check for empty input-files in utility read functions. Compared to unpresent files, empty files do not throw an error when reading them, a check for `nrow(commit.data) < 1` is therefore require
Oh I mistook it for the issue number, my bad.

2023-01-18 12:47 UTC, bockthom submitted a review, later dismissed

2023-01-18 13:12 UTC, hechtlC requested changes
I have just tried to run the test suite on my machine since the CI is still stuck. And I noticed that you are using an experimental feature of testthat in `tests-misc.R`. See my comment.
Once this is fixed for all four occurences, I will merge the PR. Thanks again for the great work!

2023-01-18 13:12 UTC, hechtlC commented on tests/test-misc.R
> +    expect_no_error(verify.data.frame.columns(
Please change this to `expect_error(..., NA, message(...))`.
The `expect_no_error` function is a new feature from testthat but is still experimental. So for now we want to stay at the "old" version. Also please put a comment behind the check with `Expect no error`.

2023-01-18 13:58 UTC, MaLoefUDS commented on tests/test-misc.R
> +    expect_no_error(verify.data.frame.columns(
I didn't know about this, I will do the replacement 😇

2023-01-18 14:19 UTC, hechtlC approved these changes

2023-01-18 14:20 UTC, merged