Make removal of empty/deleted users consistent
se-sic/coronet pull request #235
Opened 2023-01-24 14:47 UTC by nlschn

The function in util-read.R now uses a vector containing the columns to check for deleted and ampty users. This is important for commits, because there, the column "committer.name" is also relevant.

Also use the function in the setter methods of util.data for mails, issues, commits, and authors right after input validation.

This addresses #213.

### Prerequisites

- [x] I adhere to the coding conventions (described [here](../CONTRIBUTING.md)) in my code.
- [x] I have updated the copyright headers of the files I have modified.
- [x] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [x] I have put signed-off tags in *all* commits.
- [x] I have updated the changelog file [NEWS.md](../NEWS.md) appropriately.
- [x] I have checked whether I need to adjust the showcase file `showcase.R` with respect to my changes.
- [x] The pull request is opened against the branch `dev`.

### Description

### Changelog

2023-01-25 14:37 UTC, hechtlC requested changes
Thanks for the good work @nlschn !
I just have a few small remarks. Also could you please add a commit entry in the commits.list file in the test data (proximity and feature alike) where you have a "normal" user name as the author and the empty user as the committer.name? This way, if the tests still run we implicitly test that the empty user and the committer.name are filtered correctly. So no need to write a new test.

2023-01-25 14:37 UTC, hechtlC commented on util-read.R
> +    df = data.frame(data)
Why exactly are you doing this instead of just working on `data` as it was in the old function?

2023-01-25 14:37 UTC, hechtlC commented on util-read.R
> +    for (column in columns) {
Could you please add a check whether the column names in `columns` actually exist in the data?

2023-01-25 14:37 UTC, hechtlC commented on util-read.R
> +#' @param columns the columns in which to search for the "deleted user" and author with empty name.
Please change the description of the default value. We do this by adding [default: "author.name"] ath the end of the description. As a reference take a look at the function `set.project.conf` in util-data.R.

2023-01-25 14:37 UTC, hechtlC commented on NEWS.md
> +- Include removal of empty and deleted users in the setters of mails, commits, issues, and authors (PR #235, 08fbd3e11e33d060f42cbc6f729eaf60b48a6de7)
Please add the information, that we now also check the `committer.name` for the empty and deleted users.

2023-01-25 15:00 UTC, nlschn commented on util-read.R
> +    df = data.frame(data)
Because the function now takes a vector that can hold mulitple column names and I have not found any other way than to loop through the column names and check them seperately. On the other hand, the function is called with two arguments at max right now. The check itself has remained the same.

2023-01-25 15:05 UTC, hechtlC commented on util-read.R
> +    df = data.frame(data)
This should not matter in this case. You can safely remove this line and just work on `data`. That should be fine.

2023-01-25 15:14 UTC, hechtlC commented on util-read.R
> +    if (!all(columns %in% names(data))) {
Please use `colnames` instead of `names` here for clarity reasons.

2023-01-25 15:23 UTC, hechtlC submitted a review, later dismissed

2023-01-26 11:04 UTC, bockthom requested changes
Looks also good to me.
I just have spotted one mistake in the newly added test data, and I've added one more comment regarding another inconsistency with regard to removing the empty/deleted user that is still present, please see them below.

2023-01-26 11:04 UTC, bockthom commented on util-data.R
> +            data = remove.deleted.and.empty.user(data)
This only affects the active users that are the author of an issue event, but not passive users that are mentioned/subscribed/(un)assigned/review_requested/review_request_removed to an issue and named in the event info columns of the issue data.

@hechtlC and I have discussed about this whether we also should remove the empty/deleted user from the event info columns in issue data. However, for the moment, we come to the conclusion, that we should not remove it from there, for the following two reasons:
(1) If a commit is referenced in an issue, we also don't check whether the commit hash exists in our data, so why should we check if a referenced user does exist?
(2) It would make the current remove function more complex, as the `event.info.1` column contains different data, depending on the `event.type`. Therefore, we cannot just run the removement on the complete column, but would need to select only the lines which belong to a mentioned/subscribed/(un)assigned/review_requested/review_request_removed the event.

However, as not removing the empty/deleted user in this column introduces some kind of inconsistency, we should document this in the code, to be aware of that the empty/deleted user can still appear in the event info columns.

So, @nlschn could you please add a comment here in the setter function as well as also in the corresponding read function, which makes clear that the empty/deleted user is not removed from the event info columns, or to be more precise, the corresponding event is not removed even if the user in the event info column is empty or deleted.

2023-01-26 15:08 UTC, bockthom commented on tests/codeface-data/results/testing/test_feature/feature/commits.list
> +30711;"2016-07-12 16:06:34";"Thomas";"thomas@example.org";"2016-07-12 16:06:34";"deleted user";"thomas@example.org";"0a1a5c523d835459c41f33e863623138555e2526";1;1;0;1;"test2.c";"foo";"Feature";1
Unfortunately, just changing the commit id is not enough, as also the commit hash should be unique. So, please also generate a new commit hash for these two new commits. Thanks!

2023-01-26 15:12 UTC, bockthom commented on tests/codeface-data/results/testing/test_feature/feature/commits.list
> +30711;"2016-07-12 16:06:34";"Thomas";"thomas@example.org";"2016-07-12 16:06:34";"deleted user";"thomas@example.org";"0a1a5c523d835459c41f33e863623138555e2526";1;1;0;1;"test2.c";"foo";"Feature";1
And please also keep in mind: The commit ids differ between "feature" and "proximity" data (as you did correctly), but both "feature" and "proximity" use the same commit hash :wink: 
Even if it may not be intuitive, there is a reason: the commit id directly comes from the database, where one commit (having a specific commit hash) is stored in both "feature" and "proximity" data.

2023-01-26 15:26 UTC, bockthom approved these changes
Looks good now!

2023-01-26 15:33 UTC, merged