Remove 'artifact' attribute from edges of artifact networks, append 'author.name' instead
se-sic/coronet pull request #238
Opened 2023-03-23 15:32 UTC by MaLoefUDS

### Prerequisites

- [ ] I adhere to the coding conventions (described [here](../CONTRIBUTING.md)) in my code.
- [ ] I have updated the copyright headers of the files I have modified.
- [ ] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [ ] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](../NEWS.md) appropriately.
- [ ] I have checked whether I need to adjust the showcase file `showcase.R` with respect to my changes.
- [ ] The pull request is opened against the branch `dev`.

### Description

As artifacts should not be able to create edges between artifacts there should not be a `artifact` attribute on edges in artifact networks. Authors can cause edges in artifact networks so `author.name` is the replacement for `artifact` in that case.

### Changelog

Add argument to `construct.edge.list.from.key.value.list` function which differentiates if constructed edges are supposed to be artifact edges, in which case we check if the `artifact` attribute is present for edges and replace it by `author.name`.

Fix tests accordingly.

2023-03-24 19:17 UTC, bockthom requested changes
Thanks @MaLoefUDS. Looks good, I only have a view minor remarks. Could you please fix them?

---
In addition, I wonder whether we have similar problems for other kinds of artifacts (there are not only artifact networks using cochange relation, but also artifact networks using other relations, see functions `get.artifact.network.*` and, hopefully, corresponding tests). Could you please check whether we have similar problems (duplicated edges or meaningless "artifact" attributes) also for these networks? Then we can discuss in our next meeting whether we need to fix this also or whether this is not necessary for the other relations.

2023-03-24 19:17 UTC, bockthom commented on tests/README.html
Where does this file come from and why did you push it? I would like to remove it completely from the history, so maybe rebase the last commit such that this file does not appear in this PR any more.

2023-03-27 08:18 UTC, MaLoefUDS commented on tests/test-networks-multi-relation.R
> +                                 "test2.c",                                                                             # artifact cochange
Oh, I inserted whitespace to keep the `# artifact cochange` somewhat aligned to the other descriptors in the lines above and below ^^

2023-03-27 08:49 UTC, bockthom commented on tests/test-networks-multi-relation.R
> +                                 "test2.c",                                                                             # artifact cochange
Ah, I see. I did not recognize from the diff view in GitHub. (It looked like the white spaces where at the end of the line.) So, then it is fine to keep the white spaces here.

2023-03-27 08:51 UTC, MaLoefUDS commented on util-networks.R
> +    if (respect.temporal.order || artifact.edges) {
It's certainly possible to move the. `artifact` - `author.name` replacement before the selection of algorithms. I've just tried it and still, all tests seem to be running. I've additionally checked if now maybe we could use the other algorithm again, but this was not possible.

2023-03-29 13:49 UTC, bockthom commented
Just to document our thoughts regarding the other types of artifact networks: The artifact networks that coronet creates based on relation `mail` or `issue` don't have edges, at the moment. Callgraph networks are not related to the other edge-construction algorithms at all. Hence, in this PR, we only need to adjust the construction of the `cochange` artifact networks.

@MaLoefUDS Could you please update the README.md and add a note on the artifact networks on `issues`, stating that we don't have edges there (same note as for `mail`)? Thanks!

2023-03-30 14:07 UTC, MaLoefUDS commented on tests/README.html
Despite some efforts I was not able to delete the file completely. I tried:
```
$ git rebase <commit-before-by-pr>
... put an 'edit' to the commit which introduced README.html ...
$ git rm README.html
$ git commit --amend
$ git rebase --continue
$ git pull
``` 
After these steps the file did still exist in my git history and im not sure how to continue.

2023-03-30 14:21 UTC, MaLoefUDS commented on tests/README.html
Oh I pulled because it told me I was commits behind 😅. I’m not very familiar with rebasing in general, I‘ll try force pushing 👍

2023-03-30 14:25 UTC, bockthom commented on tests/README.html
By pulling, you "re-added" the old commits you had already pushed before. So there might be some duplicated commits in your history now and maybe also a merge commit. Please make sure to fix this and push a linear commit history. This way, you will get even more experience with rebases :wink:

2023-03-30 14:28 UTC, MaLoefUDS commented on tests/README.html
I think I just did that ^^. However I think one commit hash in NEWS needs to be updated.

2023-03-30 14:34 UTC, bockthom commented on tests/README.html
Seems to be true^^. When you update the NEWS, please also fix the typo your introduced in your statement regarding the README.

2023-04-03 14:24 UTC, bockthom commented
I finally managed to fix the issues regarding the failing test pipeline that were caused by igraph version 1.4.0 (see PR #240).

@MaLoefUDS: Could you please check whether your changes still work with the changes I made in #240? (Please try it only locally, on a separate local branch; there will probably some rebases before everything is merged into dev)

2023-04-14 08:40 UTC, bockthom approved these changes

2023-04-14 13:36 UTC, hechtlC approved these changes
Looks good thanks @MaLoefUDS ! I will merge it now.

2023-04-14 13:37 UTC, merged