Dev
se-sic/coronet pull request #244
Opened 2023-09-05 09:39 UTC by MaLoefUDS

### Prerequisites

- [x] I adhere to the coding conventions (described [here](../CONTRIBUTING.md)) in my code.
- [x] I have updated the copyright headers of the files I have modified.
- [x] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [x] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](../NEWS.md) appropriately.
- [x] I have checked whether I need to adjust the showcase file `showcase.R` with respect to my changes.
- [x] The pull request is opened against the branch `dev`.

### Description

#### Add
* Creation of issue-based artifacts networks by connecting issues by their corresponding 'add_link' and 'referenced_by' issue-events (from the same author, at the same time)
* Corresponding tests to ensure feature is implemented correctly, including new 'add_link' and 'referenced_by' issue-events 
* New method of splitting data by activity bins ('split.data.by.bins.vector'). This method was necessary as splitting time-based was not sufficient to be used in 'split.data.activity.based'. As this method shared a lot of code with 'split.data.time.based' I renamed the method to 'split.data.by.time.or.bins', intermingled the functionality of splitting by bins into it and created wrapper functions 'split.data.time.based' and 'split.data.by.bins.vector' to just call the bigger method

#### Change
* Adjust other tests to work with changed testing data
* If one issue-event refers to another one in its 'event.info.1' column change the format of the reference from e.g., '3' to '<issue-github-3>' to ensure for easier implementation of the edge creation for issue-based artifact networks
* Allow to obtain activity-bins in the 'split.get.bins.activity.based' method which are scoped for all events of a certain 'split.basis', not only the ones with unique ids. 

#### Fix
* Changed vertex attribute 'IssueEvent' in multi-networks to 'Issue' to make it consistent with vertex attributes set in the creation of bipartite networks
* Fix the calculation of 'offset.end' in 'split.data.activity.based' as it could overlap the borders of the last window into the second last which would then produce incorrect sliding windows (the very last sliding window, covering only the few elements of the last real window, was missing)

### Changelog

See above :)

2023-09-09 21:21 UTC, bockthom requested changes
Thanks @MaLoefUDS for your work on this PR and fixing all the bugs you encountered during adjusting all the test data. Your changes look good to me, I only have a couple of questions regarding some implementation details, some of which need further investigations prior to discussing it - some my comments below.

Notice: I did not have a look at the adjusted tests yet, and I also will need another pass on the changes to the splitting functionality to be able to completely understand all of them...

2023-09-09 21:21 UTC, bockthom commented on util-split.R
> +#' @param project.data the *Data object from which the data is retrieved
Please write " project data" instead of "*Data" - RangeData is a subclass of ProjectData, and what we want here is any object of type ProjectData, regardless of being a subclass of it or not.

2023-09-09 21:21 UTC, bockthom commented on util-split.R
> +#'             [default: NULL]
This default value does not occur in the function declaration.

2023-09-09 21:21 UTC, bockthom commented on util-split.R
> +#'                         or \code{splitting.length} from\code{split.data.by.bins.vector}
`split.data.by.bins.vector` does not have a parameter `splitting.length`. Do you mean `activity.amount` instead, or something else?

2023-09-09 21:21 UTC, bockthom commented on util-split.R
> +#' @param split.by.time logical indicating whether splitting is done time-based or by activity-bins-based,
Please remove the "by" in the description and the comma at the end of the parameter description

2023-09-09 21:21 UTC, bockthom commented on util-split.R
> +    if (split.by.time && (length(bins.ranges) <= 1) && sliding.window) {
Why does this warning only hold for `split.by.time`? Shouldn't it be the same warning for activity-bin-based splitting?

2023-09-09 21:21 UTC, bockthom commented on util-split.R
> +            df.bins = if (!split.by.time && (df.name == split.basis))
What does the check `df.name == split.basis` do? I am a little bit confused here. Maybe a comment would be helpful here.

2023-09-09 21:21 UTC, bockthom commented on util-split.R
> +#'         'activity.amount' many unique items; each item in the vector indicates
You fixed one typo and added one - please remove the "q" here.

2023-09-11 10:31 UTC, MaLoefUDS commented on util-networks.R
> +            ## connect the current item to all previous ones
The comment was taken from the `construct.edge.list.from.key.value.list` method line 1094 which this edge construction was based on. Should I make it more descriptive in both?

2023-09-11 10:33 UTC, MaLoefUDS commented on util-networks.R
> +                    combination = list("Var1" = from[["issue.id"]], "Var2" = to[["issue.id"]])
Because that's the internal names for the elements in the I presume igraph data structures I found while debugging. Its more or less arbitrary

2023-09-11 10:34 UTC, MaLoefUDS commented on util-split.R
> +#'                         or \code{splitting.length} from\code{split.data.by.bins.vector}
Yes, my bad!

2023-09-11 10:39 UTC, MaLoefUDS commented on util-split.R
> +    if (split.by.time && (length(bins.ranges) <= 1) && sliding.window) {
Oh yeah this is most likely the result of me mechanically adding the `split.by.time` bool to every condition which was in the original function but which I removed for simplicity from the activity-vector based splitting.

2023-09-11 10:40 UTC, bockthom commented on util-networks.R
> +            ## connect the current item to all previous ones
In line 1094 the comment is fine, as there we actually have a temporal order of activities where it is clear what "current" and "previous" means. However, here we don't have a temporal order, we just link to issues. Therefore "current" and "previous" does not really apply here.

2023-09-11 10:42 UTC, MaLoefUDS commented on util-networks.R
> +            ## connect the current item to all previous ones
I just assumed it was meant for a previously assigned and a currently assigned variable, I did not pay attention to the temporal order. In this case, sure I will replace the comment

2023-09-11 10:47 UTC, bockthom commented on util-networks.R
> +                    combination = list("Var1" = from[["issue.id"]], "Var2" = to[["issue.id"]])
Thanks for the explanation. If this are exactly the names that are used in the other network-construction functions, then it is fine, to stay consistent. Otherwise, it would be more readable to use appropriate names here.
@hechtlC What do you think?

2023-09-11 10:53 UTC, MaLoefUDS commented on util-networks.R
> +                if (!all(is.na(to))) {
Regarding your first paragraph: I could take an arbitrary `add_link` or `referenced_by` event and look in the `event.info.1` column to see the issue which is linked, but for the edge construction im not connecting directly to an issue but to an issue-event, this is how its done for the other artifact networks as well. So I take the corresponding other event to connect to. If there is none the input data is probably malformated.

I could add an epsilon time in which these events still connect like 1 second

2023-09-11 10:59 UTC, MaLoefUDS commented on util-networks.R
> +                directed = FALSE,
I think we can take the parameter from the config, and it will not change anything. I think we decided on the order of `add_link` -> `referenced_by` for edges and that's the way I implemented it, so it should not matter indeed.

2023-09-11 11:19 UTC, bockthom commented on util-networks.R
> +                if (!all(is.na(to))) {
> If there is none the input data is probably malformated.
> 
> I could add an epsilon time in which these events still connect like 1 second

Let's perform some empirical investigations on real-world data before we decide on each of these two concerns. I don't trust in the completeness of the data in such a way as you do :wink: You will receive an e-mail with real-world data soon...

2023-09-11 11:21 UTC, bockthom commented on util-networks.R
> +                directed = FALSE,
Great, that sounds good. Nevertheless, let's also wait for the outcomes of our investigations on real-world data mentioned above.

2023-09-11 11:41 UTC, MaLoefUDS commented on util-split.R
> +            df.bins = if (!split.by.time && (df.name == split.basis))
So you do the splitting based on one specific activity, like mails for example. So you compute bins based on the mails data and a corresponding bins vector (e.g., 1 1 1 2 2 2 3 telling you that the first 3 elements of mail data should go in bin 1, then the next 3 into bin 2 and the last into bin 3). But you can only use this vector for the mail data now, not for all the other data. That is why you need to have a distinction here

2023-09-11 11:48 UTC, bockthom commented on util-split.R
> +            df.bins = if (!split.by.time && (df.name == split.basis))
Thanks for the explanation. Now I understand what's going on there. I think we don't need a comment there then. But I will do another review on the splitting changes anyway. So, let's wait whether there are additional questions when I try to comprehend the other changes.

2023-09-11 11:55 UTC, MaLoefUDS commented on tests/test-networks-artifact.R
> +        from = character(), to = character(), date = as.POSIXct(character(0), tz = "UTC"), artifact.type = character(),
Your suggested change does not break any tests, so I suppose it suffices.

2023-09-11 13:26 UTC, MaLoefUDS commented on util-networks.R
> +            for (issue.no in seq_len(nrow(add.links))) {
I could make it work like this:

```
edge.list.raw = parallel::mclapply(split(add.links, 1:nrow(add.links)), function(from) {
...
})
edge.list = do.call(rbind, edge.list.raw)
```

Is this better performance wise?

2023-09-12 08:01 UTC, bockthom commented on util-networks.R
> +            for (issue.no in seq_len(nrow(add.links))) {
This should already be a performance improvement, yes. But if you use `plyr::rbind.fill` instead of `do.call`, the performance improvement would be even bigger :wink: And you also don't need to use two variables, you can just rbind the elements in-place.

And I suggest to use `seq_along` instead of `1:nrow`, as `seq_along` is fail-safe.

2023-09-20 13:43 UTC, bockthom commented on util-networks.R
> +                if (!all(is.na(to))) {
It turned out that we automatically add the `referenced.by` events for all `add.link` events that have `event.info.2 == "issue"` during in the codeface-extraction:
https://github.com/se-sic/codeface-extraction/blob/7bd8d0080055ed7266177fac0a28e3aeec4cac6e/issue_processing/issue_processing.py#L331-L339 

Therefore, also the dates are also exactly the same, so we can assume for sure that the corresponding `add.link` and `referenced.by` events are always present and have the same date.

To make this consistent for GitHub and JIRA issues, we also need to automatically add the `referenced_by` events for the JIRA issue extraction in https://github.com/se-sic/codeface-extraction/blob/master/issue_processing/jira_issue_processing.py" 
If we do so, the implementation here in this PR should work without any changes.

2023-09-20 13:45 UTC, bockthom commented on util-networks.R
> +                directed = FALSE,
When we take the `directed` option from the network configuration, we also should have a test for the directed issue artifact network.

2023-09-20 13:46 UTC, bockthom commented on util-read.R
> +    formatted.matches = sprintf("<issue-%s-%s>", matches[["issue.source"]], matches[["event.info.1"]])
Just a reminder for later: Fixing the format of `event.info.1` when it contains issue ids should also be mentioned in the changelog.

2023-10-09 21:42 UTC, bockthom reviewed
As promised, I had a closer look at the changed splitting functionality, and I also started to have a look at the tests (these were the two parts that were still missing from my last review.)

For the splitting functionality, I have a couple of questions that I would like to discuss in our next meeting to get a better understanding of what's going on there. Please have a look at my individual comments (most of them address just comments, but we should discuss them though). In general, the new functionality looks good to me, but I would like to make sure that I understand everything correctly and that we consider special corner cases correctly.

For the tests, I decided to skip reviewing the tests for now as I identified an unexpected change in the test data - we should discuss this in our next meeting before I will have a closer look at the tests themselves. Again, see my detailed comments below.

2023-10-09 21:42 UTC, bockthom commented on util-split.R
> +        }
Why is `split.by.bins` not set to `TRUE` in the `else` case? If this is not a bug, then we should comment on this - either here - or maybe also already in the comment `initiate variable` as it is not completely clear what the variable `split.by.bins` is used for in this method.

2023-10-09 21:42 UTC, bockthom commented on util-split.R
>          ## perform different steps for sliding-window approach
The comment here seems to be outdated. Shouldn't it be "for sliding-window approach of time-based splitting" ? Because sliding-window for activity-based splitting should already be covered by the previous if-case...

2023-10-09 21:42 UTC, bockthom commented on util-split.R
> +        type = if (split.by.time) "time-based" else "activity-based",
(Not related to this PR, but still interesting): Do we set the type for the splitting info also in other functions? Maybe it would be an idea to introduce string constants for the types, if there are just these two. (Does not need to be done in this PR, we can open another issue for that in take of this later. So just having a look whether these types appear also somewhere else be enough for now....

2023-10-09 21:42 UTC, bockthom commented on util-split.R
> +#' @param split.basis the data name to use as the basis for split bins, either 'commits', 'mails', or 'issues'
"data name" --> "data source"
Maybe we can also add a reference to "activity.amount" for activity-based splitting. This is also what I would like to briefly discuss in the next meeting, to make the initial sentence of this function description a little bit more precise.

2023-10-09 21:42 UTC, bockthom commented on util-split.R
> +        last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
Wait. If I am not mistaken, the comment specifies another scenario than the code here.

What the comment describes (each number represents one activity in the respective range):
regular: 444455
sliding:  334444
Then regular range 5 can be removed.

What the new code describes (each number represents one activity in the respective range):
regular: 445555
sliding:  333344
Then sliding range 4 can be removed.

Don't we actually need to handle both cases? Maybe the implementation below takes care of both scenarios (I did not check for that), but currently code and comment seem to be contradicting...

2023-10-09 21:42 UTC, bockthom commented on util-split.R
> +            bins.activity.padded = c(bins.activity.padded, current.bin)
Can we add an example (as comment) describing in which situation this is/could be necessary? Currently I understand what's going on, but don't completely get in which situation this was a problem in the previous implementation?
Maybe let's discuss this first. I would also like to know in which situations of the same method call we don't need this padding and in which we do.

2023-10-11 14:51 UTC, MaLoefUDS commented on util-split.R
> +            bins.activity.padded = c(bins.activity.padded, current.bin)
I have a small problem with what we discussed in our most recent meeting. There we mentioned to include a comment which explains why we need the padded bin vector here. 
I reviewed the code again and the place where the padding is performed is inside a helper function so it would be strange to mention the use case for a function calling this helper function inside the helper function I think. I think we could add the comment where the helper function is called with the padding (as specified in the function parameters) as this is the only place where the padding is needed as of now 🤷‍♂️.

2023-10-11 15:11 UTC, bockthom commented on util-split.R
> +            bins.activity.padded = c(bins.activity.padded, current.bin)
Agreed. Please add the comment where the function is called with the respective parameter.

2023-10-11 16:04 UTC, MaLoefUDS commented on util-split.R
> +        last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
I have reviewed this case again and as I suspected both edge cases are already covered. 

1) This case can be achieved if we have 18 elements and an activity amount of 4. In this case we calculate offset.start as floor(activity.amount / 2) = 2, offset end as (items.unique.count - offset.start) %% activity.amount = 0 and realize that the data will not be cut off from the end. This means that the last sliding range will end really at the end of the 334444 and the last regular range really ends at the end of 444455 anyways. Now the endpoints are equal and we run into the case which you highlighted here in the PR and remove the last regular range (the 55).

2) Now we have 20 elements and an activity amount of 4. offset.start is still 2 and offset.end = (items.unique.count - offset.start) %% activity.amount = 2. This means that the last 2 elements will be cut off before calculating sliding windows, and the 55 will be removed :).

2023-10-11 16:17 UTC, bockthom commented on util-split.R
> +        last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
Sounds good, thanks a lot for checking that. But then we should think about adjusting the comments:

Shouldn't we move the comments in lines 497-499 without any changes down to line 504/507?
And in addition keep a copy of the comments in lines 497-499 in lines 497-499 in which we replace all occurrences of "regular" and "sliding window" by each other?

2023-10-12 08:21 UTC, MaLoefUDS commented on util-split.R
> +        last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
About moving the comments I dont have any complaints because line 504-507 really are more fitting. Im wondering why we should leave a copy of the comment with sliding window and regular changed there as line 500-501 have nothing to do with removing the last sliding window (as suggested).

2023-10-12 08:26 UTC, MaLoefUDS commented on util-split.R
> +        type = if (split.by.time) "time-based" else "activity-based",
They are only set in one place (except in tests where expected results are built). I dont think its worth creating constants for them *yet*.

2023-10-12 11:47 UTC, bockthom commented on util-split.R
> +        last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
> Im wondering why we should leave a copy of the comment with sliding window and regular changed there as line 500-501 have nothing to do with removing the last sliding window (as suggested).

What does this line do then?
```R
last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
```
It extracts the second-last sliding range as "last sliding range". This means, the actual last one is not considered to be the last one. So the last one is kind of "removed" here. I agree that here no actual removement takes place, as no element is removed from the list, but something similar happens there...

So, I would like to have a comment describing what the cited line is used for (when not removing the last sliding range). And I would like to describe somewhere in the code where the following scenario is handled (for which the previous comment in 497-499 with changed sliding/regular ranges would fit best):

    regular: 444455
    sliding: 334444
    Then regular range 5 can be removed.

2023-10-12 11:50 UTC, bockthom commented on util-split.R
> +        type = if (split.by.time) "time-based" else "activity-based",
Ok. Then let's ignore that _for now_.

2023-10-12 14:24 UTC, MaLoefUDS commented on util-split.R
> +        last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
Lets just say I have discovered a funny series of bugs previously unnoticed when debugging on the issue data with the readded events previously deleted and uh yeah its weird

2023-10-12 14:30 UTC, MaLoefUDS commented on util-split.R
> +        last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
Now im not sure anymore if we really should remove 5 in the case you mentioned in your most recent comment. Shouldn't regular ranges stay as they are?

2023-10-12 14:42 UTC, bockthom commented on util-split.R
> +        last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
Wait, I mixed the to examples up. The 444455 example is the one which is handled in lines 504-507, right? Which is why wanted the comment to be moved down.

So the other case which I was looking for is this example:

    regular: 445555
    sliding: 444455
    Then sliding range 5 can be removed.

Maybe this is already cut correctly by default when calculating offsets etc.?

2023-10-12 14:44 UTC, MaLoefUDS commented on util-split.R
> +        last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
The main problem is that I dont have an idea why the code even works with taking the second last element of the sliding windows, the subsequent if always is false therefore and debuggin it yields more bugs, oops.

2023-10-12 15:09 UTC, MaLoefUDS commented on util-split.R
> +        last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
I think a simplification to decide which ranges to drop is to drop the last incomplete range. I did some sketches and think this should work out fine.

2023-10-12 15:14 UTC, bockthom commented on util-split.R
> +        last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
I am not sure about whether removing the last incomplete range is always correct. If the last range is incomplete and contains data that is not already part of the previous regular or sliding range, then we want to keep the incomplete range. Only if everything is already contained in a previous range, we want to remove the incomplete range.

2023-10-12 16:24 UTC, bockthom commented on util-split.R
> +        last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
Your explanations sound reasonable. However, the mandatory condition for this approach is: You only remove incomplete ranges after having reached x. Otherwise, this would not work, as the following two examples show:

    (I)
            __
    .....__|xx|........x
        |xx|xx|
        |xx|xx|
        |xx|__|
        |xx|  |
        |__|  |
        |RR|SS|

    (II)
            __
    .......|xx|........x
        |__|xx|
        |xx|xx|
        |xx|xx|
        |xx|__|
        |xx|  |
        |__|  |
        |RR|SS|

In these examples, the last range (SS) is incomplete but has to be kept as the last element (in I) or the last two elements (in II) are missing in RR. So, you cannot remove the last range. But if you use an additional constraint to check whether you have included the number of total activities, this might work. But I am not sure how complicated it is to determine x...

2023-10-12 16:32 UTC, MaLoefUDS commented on util-split.R
> +        last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
* As I see it in (I) the last sliding range can be removed as x has been reached by the last regular range as well, or am I wrong?
* In (II) the last regular block which starts below x would be the highest / last and therefore removed leaving the last S range intact. S and R ranges alternate.
* The total number of elements x is already present as an integer inside the function ^^ (`items.unique.count`). I think this refactoring can greatly simplify the code (even if its not that easy to "understand" why its valid)

2023-10-12 17:20 UTC, bockthom commented on util-split.R
> +        last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
> * As I see it in (I) the last sliding range can be removed as x has been reached by the last regular range as well, or am I wrong?

I was not sure about the concrete syntax, whether xx and ...x need to be in the same line to reach x or whether __ and ...x need to be in the same line to reach x. In my examples, ....|xx| ....x means that we reach the total number of x exactly in this line. What I might have misunderstood in your syntax is the meaning of "xx". So in my example "xx" means that a value is present and an empty lines means that it is not present in this range - which might be opposed to how you have used the syntax. Sorry for the confusion. So in (I), the last range of SS has three elements but is incomplete as it should have four. However, one of the three elements (namely the last one) is not included in RR, so the last range of SS cannot be removed although it is incomplete.

> * In (II) the last regular block which starts below x would be the highest / last and therefore removed leaving the last S range intact. S and R ranges alternate.

The last S range is later than the last R range. As in (I), also in (II) the last S range is incomplete but cannot be removed, as the last value of R is below x.

> * The total number of elements x is already present as an integer inside the function ^^ (`items.unique.count`). I think this refactoring can greatly simplify the code (even if its not that easy to "understand" why its valid)

Great. Then it might actually work to check for x and remove an incomplete range if x has already been reached by another range that has started earlier (interpreting earlier in terms of number of reached elements, such that it also works for activity-based splitting where multiples ranges can have the same time stamps).

2023-10-12 19:50 UTC, MaLoefUDS commented on util-split.R
> +        last.sliding.range = cf.data.sliding[[length(cf.data.sliding) - 1]]
I've done a poc implementation and it seems to work however as we recently decided that the last regular range can be dropped as well if totally included in the last sliding window range, which was not clear before, I have to adapt some tests yet again 😂

2023-11-08 17:00 UTC, bockthom commented on util-split.R
> +        }
Please allow me to be forgetful. We already have discussed about these lines of code some weeks ago, but when I look at them again, I again don't understand what's going on here:

This "else" case handles the case that we want to split data activity-based by given bins, right?
How does this work? How can we split activity-based by bins? I could imagine that we can count the activities between two bins and use this activity amount for activity-based splitting. but what do we do when we have more than two bins given? This confuses me. And then the comment also states that we can have sliding windows in addition - how could this work if I cannot even imagine it without sliding windows. Maybe I am too tired now to be able to understand this little piece of code, but I am really confused now. 

Can you enlighten me in this matter @MaLoefUDS ?

2023-11-08 18:08 UTC, bockthom requested changes
Sorry for the delay. I still haven't managed to look at the tests. But I have had a look at the new changes of the main implementation. In general, the new changes look good. I only spotted a few comments that are still hard to understand and one implementation detail which I don't understand, making it hard for me to judge its validity. See my individual comments below.

 I will have a look at the tests in the next iteration.

2023-11-08 18:08 UTC, bockthom commented on util-split.R
> +        if (((items.unique.count - 1) %% (activity.amount)) >= (offset.start)) {
I am wondering whether this is off by one or not. Why do you subtract 1 form the unique item count? This might be correct in combination with `>=` (I am not sure). I am just wondering why you get the number of the second last time...

2023-11-08 18:53 UTC, bockthom commented on util-split.R
> +        if (((items.unique.count - 1) %% (activity.amount)) >= (offset.start)) {
The longer I think about this, the more I think that it is correct. Your statement 
```R
if (((items.unique.count - 1) %% (activity.amount)) >= (offset.start)) {
```
can be transferred to the following equivalent one (which is more in line with your comments and looks more intuitive to me):
```R
if ((items.unique.count %% activity.amount) > offset.start) {
```
And if I understand the cropping at the beginning correctly, the offset.start-th element is still cropped, meaning that the offset.start+1st element is the first element of the sliding range. Please correct me if I am wrong.
If my argumentation is correct, then I would like you to replace your condition with the shorter condition that I proposed -- if you agree that it is easier to understand.

2023-11-09 09:45 UTC, MaLoefUDS commented on util-split.R
> +        }
Sure I think I can explain it.

Your first assumption is correct. When doing activity based splitting, we split all our data by a given `split.basis`, like `issue`, into sections with n unique entries. Now we expand the vectors to include all entries with duplicate ids as well. This means that the bins are now not all the same size. Those bins are then passed into the referenced `split.data.by.time.or.bins` method. This method then just splits the data by the given bins (not only the data of the given `split.basis` but *all* data. 

The role of `sliding.window` in this function when used for activity based splitting is a bit odd. The parameter does in this case **not** decide the splitting algorithm or similar, so the splitting stays the same whether this parameter is true or false however this method can be called with bins representing regular bins or representing sliding window bins and depending on this the splitting info in the end needs to be adjusted to fit. The comment actually refers to a change you requested. As in the then case of the if we set `sliding.window` to false because we cannot have given bins in time-based splitting and use sliding windows at the same time. In the case of activity based splitting these two do not contradict, in fact the parameter is not allowed to be overwritten there as we need it in the end for the splitting info. 

Hope that explains it :)

2023-11-09 10:22 UTC, MaLoefUDS commented on util-split.R
> +#'             or as the \code{bins} parameter of \code{split.data.by.bins}
As I have just learned, the format differs. I copy pasted the description to both methods, I think it needs an update overall on the side of the activity bin based splitting 😅

2023-11-09 10:29 UTC, MaLoefUDS commented on util-split.R
> +        if (((items.unique.count - 1) %% (activity.amount)) >= (offset.start)) {
Your argumentation is solid, I also think it is easier to read so I will just exchange it ^^

2023-11-09 11:13 UTC, bockthom commented on util-split.R
> +        }
Ah, I get it. Thanks for the detailed explanations. Then everything is fine. I just did not question where the bins come from in this case. But if they are already given as function parameter correctly, then everything makes sense.
Can we maybe add an additional comment at the beginning of the else block? Something like
"the activity-based bins are already passed to this function in the correct format"
But as we do not make sure that the parameter is in the correct format, maybe "are" is wrong - this is just an assumption which may not hold when someone would use this function incorrectly. So maybe we should go with "should be" instead?

Should we check whether format is correct and print a warning if not? What is your opinion on that?

2023-11-09 11:57 UTC, MaLoefUDS commented on util-split.R
> +#'             \code{project.data} to bins, as produced by \code{split.get.bins.activity.based}.
```R
$vector
[1] 1 1 1 2 2 2 3 3

$bins
[1] "2016-07-12 15:58:59" "2016-07-12 16:06:10" "2016-07-12 16:06:32" "2016-07-12 16:06:33"
```

This is the format of the `bins` variable. Here is my suggestion of a descriptive comment:

```
@param bins the bins by which data should be split. Comprises of two components:
            \code{vector}: Assigns elements of the \code{split.basis} column of \code{project.data} to bins.
            \code{bins}: Dates defining the start of bins (the last date defines the end of the last bin, in an 
            *exclusive* manner).
            The expected format of \code{bins} is produced by  \code{split.get.bins.activity.based}.
            
...
@seealso split.get.bins.activity.based
```

What is your opinion on that?

2023-11-09 12:36 UTC, bockthom commented on util-split.R
> +#'             \code{project.data} to bins, as produced by \code{split.get.bins.activity.based}.
Sounds good! 
I've only spotted a doubled whitespace, everything else looks good to me.

2023-11-10 11:38 UTC, MaLoefUDS commented on util-split.R
> +        }
The method, which was the base of the new `split.data.by.time.or.bins` method, did no checks on the format of the bins either, even though the multiple notations of bins used here was not introduced by me. Other parameters are not checked consequently for their format either, and lastely, the method is only called by the two new wrapper methods, so if we want to introduce the format checks, I think we should do it there :).

2023-11-10 13:02 UTC, bockthom commented on util-split.R
> +        }
Ok, thanks for your reply. I am of two minds. Some time ago, we started to do input validation in some of the methods of the Conf and Data classes. I am not sure if we also should do it for other functions, such as the splitting functions, or if we should just let it fail if the format is wrong.

@hechtlC What is your opinion on that?

2023-11-15 09:55 UTC, MaLoefUDS commented
There is now only one point open (excluding the NEWS.md). @hechtlC What is your opinion on adding input validation for the `bins` variable in the splitting function (as mentioned in an earlier comment)?

2023-11-15 09:59 UTC, bockthom commented on util-split.R
> +#' @param number.windows see \code{number.windows} from \code{split.data.time.based}
Really? Shouldn't this be just `split.data.by.bins`? Please check again.

2023-11-15 10:00 UTC, bockthom commented on util-split.R
> +        if ((items.unique.count %% activity.amount) > (offset.start)) {
Could you please remove the unnecessary brackets around `offset.start`?

2023-11-15 10:04 UTC, MaLoefUDS commented on util-split.R
> +#' @param number.windows see \code{number.windows} from \code{split.data.time.based}
No, this parameter comes from the `split.data.time.based` function

2023-11-15 10:19 UTC, bockthom commented
> There is now only one point open (excluding the NEWS.md). @hechtlC What is your opinion on adding input validation for the `bins` variable in the splitting function (as mentioned in an earlier comment)?

@MaLoefUDS There is still one other point open: 

"When we take the directed option from the network configuration, we also should have a test for the directed issue artifact network." 

As far as I can see, the tests in [tests/test-networks-artifact.R](https://github.com/se-sic/coronet/pull/244/files#diff-9fa163c01b5f6ca153b2b0b043c5b694deeabfcaee1acc56dbaf304752ef9c12) only test undirected networks.
Maybe it is possible to use the existing tests and just make parameterized tests out of it, using `packrat` - then you just need to pass directed as a parameter and use it everywhere you need it in the test

2023-11-20 03:11 UTC, bockthom requested changes
Almost done with the implementation ;) I only spotted a few potential issues with the input validation. I am not sure whether all the spotted issues are actual issues or not, please check.

2023-11-20 03:11 UTC, bockthom commented on util-split.R
> +    if (class(bins[["vector"]]) != "numeric") {
Hm, I am not sure if this strict check is necessary or even correct. In R, every variable can have multiple classes.
Maybe you can use `!inherits(bins[["vector"]], "numeric")` here?

2023-11-20 03:11 UTC, bockthom commented on util-split.R
> +                                        sliding.window = sliding.window, split.basis = split.basis)
The indentation of the second line is wrong here (needs to be shifted by one to the left).

2023-11-20 16:13 UTC, MaLoefUDS commented on util-split.R
> +    if (class(bins[["vector"]]) != "numeric") {
I can change it if you want, it does not break our tests to have it like this, but I agree your version is probably more correct (does not break any tests either)

2023-11-20 16:16 UTC, MaLoefUDS commented on util-split.R
> +            logging::logerror("The bins parameter, if present, needs to be a character representing a date")
The `dates` variable is defined above as `dates = parallel::mclapply(bins[["bins"]], function(bin) lubridate::ymd_hms(bin, truncated = 3))`. lubridate::ymd_hms returns NA ist the string given as input does not match the time format.

So in the case where one entry of `dates` is NA, this means that we don't have a valid time stamp here.

2023-11-20 16:23 UTC, MaLoefUDS commented on util-split.R
> +        dates = parallel::mclapply(bins, function(bin) lubridate::ymd_hms(bin, truncated = 3))
If we are *only* talking about the line below the conditional, I can change it to `dates = parallel::mclapply(bins, function(bin) get.date.from.string(bin))` without a problem :)

2023-11-20 16:23 UTC, bockthom commented on util-split.R
> +    if (class(bins[["vector"]]) != "numeric") {
Yeah, please change it. I'd feel better if we are less restrictive, maybe there are some cases in which multiple classes occur. In addition, a less restrictive check should also be more robust to future changes in R and (hopefully) reduces the change effort for us then.

2023-11-20 16:27 UTC, bockthom commented on util-split.R
> +            logging::logerror("The bins parameter, if present, needs to be a character representing a date")
That's clear. The question I had in mind is the following, though (sorry for being unprecise in my first comment): What happens in all the splitting functions etc. when one of the elements in `NA`. Would be interesting to know if our splitting methods just ignore the `NA` or whether this leads to errors or unwanted behavior (ranges that start and end differently than expected)

2023-11-20 16:30 UTC, bockthom commented on util-split.R
> +        dates = parallel::mclapply(bins, function(bin) lubridate::ymd_hms(bin, truncated = 3))
This should be enough, I guess. If I am not mistaken, we use the `isPOSIXct` check at different places in coronet (we could also think about defining our own wrapper for it, but I guess it's not worth yet). 
But the actual date conversion should only be done at one single place - and that's what's `get.date.from.string` is doing.

2023-11-20 16:37 UTC, bockthom commented on util-split.R
> +        logging::logerror("The 'bins' component of the bins parameter needs to be a character representing a date")
Wait. What happens if there is no "bins" element or no "vector" element (below). In such cases, the "mclapply" could throw errors. Maybe adjust the check above to check for the existence of "bins" and "vector" first...

2023-11-20 16:51 UTC, MaLoefUDS commented on util-split.R
> +            logging::logerror("The bins parameter, if present, needs to be a character representing a date")
1) I do not even validate that the bins do not contain NAs (maybe I should, because...)
2) Having an NA inside as a bin entry does break the code when calling `findInterval` in `split.data.by.timeor.bins`(`stop("'vec' must be sorted non-decreasingly and not contain NAs")`)

2023-11-20 16:56 UTC, bockthom commented on util-split.R
> +            logging::logerror("The bins parameter, if present, needs to be a character representing a date")
Thanks for checking what happens in this case. Then we should definitively check for `NA`s here :+1:

2023-11-20 17:00 UTC, MaLoefUDS commented on util-split.R
> +        logging::logerror("The 'bins' component of the bins parameter needs to be a character representing a date")
In this case the dates object will be an empty `list()`. As this will not trigger the conditional `any(is.na(dates))` I will add a check for it. As for the case where `vector` is missing, this will mean that `bins[["vector"]]` returns `NULL` which triggers the conditional `!inherits(bins[["vector"]], "numeric")`. There is no check needed in this case

2023-11-20 17:05 UTC, bockthom commented on util-split.R
> +        logging::logerror("The 'bins' component of the bins parameter needs to be a character representing a date")
Agreed!

2023-11-20 17:10 UTC, MaLoefUDS commented on util-split.R
> +            logging::logerror("The bins parameter, if present, needs to be a character representing a date")
Nevermind, in the case where a bin is `NA` the `dates` object will contain an `NA` which will trigger a `stop`, no need for a check

2023-11-20 17:52 UTC, bockthom reviewed
The current implementation looks good to me. 
I have two suggestions for better code readability.
This is my last comment on the implementation in this PR, looks really good to me now.

Let's see when I find some time to have a look at some of the tests...

2023-11-20 17:52 UTC, bockthom commented on util-split.R
> +        dates = parallel::mclapply(bins, function(bin) get.date.from.string(bin))
Could be simplified to: `dates = parallel::mclapply(bins, get.date.from.string)` (also below in the second occurrence of this line)

2023-11-20 17:52 UTC, bockthom commented on util-split.R
> +    if (!"bins" %in% names(bins)) {
Please add parentheses for better readability: `(!("bins" %in% names(bins)))`

2023-11-21 14:08 UTC, bockthom commented on util-split.R
> +    dates = parallel::mclapply(bins, get.date.from.string)
Shouldn't that be `bins[["bins"]]` here instead of just `bins`, as it was before?

Interestingly, this did apparently not lead to a test failure in our CI pipeline, and I am wondering why. If I try to call  `as.POSIXct(list(vector=c(1,2,3), bins=list("2020-02-02","2020-02-03", "2020-02-04"))`, which should be the format of how `bins` looks like, I get an error. So, I would expect a similar error in our tests, as this function call should always produce an error if `bins` consists of elements `bins` and `vector` as expected... 

So, now I am confused. Can you please find out why this did not lead to an error in our tests?

2023-11-21 14:10 UTC, MaLoefUDS commented on util-split.R
> +    dates = parallel::mclapply(bins, get.date.from.string)
Oh this was a copy paste error 💀 but still interesting outcome, I will investigate until tomorrow ^^

2023-11-21 14:30 UTC, MaLoefUDS commented on util-split.R
> +    dates = parallel::mclapply(bins, get.date.from.string)
Okay I got it done quicker than I thought:

1) What it does is, it sets all values in the `bins[["vector"]]` to `NA` and all the values in the``bins[["bins"]]`` to the dates they were before (as intended). Then it goes over all elements in bins (which are `vector` and `bins`) and says, none of those are `NA`, this is why it does not go into the error case.

2) It does also not do false positives because none of our tests test against this input validation yet (so no tests have `NA` in the bins parameter) and therefore the error case should not be triggered by any test and is factually not being triggered because of 1).

2023-11-21 14:32 UTC, bockthom commented on util-split.R
> +    dates = parallel::mclapply(bins, get.date.from.string)
Nevermind, I forgot to add the `lapply` in an exemplary call. If I add the `lapply`, I don't get any errors:

`lapply(list(x=c(1,2,3), y=c("2020-02-02","2020-02-03", "2020-02-04")), as.POSIXct)`

Thus, there also will be no error when we execute our tests. So, it should be fine to just fix the `bins[["bins"]]` part here.

2023-11-21 14:53 UTC, bockthom commented on util-split.R
> +    dates = parallel::mclapply(bins, get.date.from.string)
>  none of our tests test against this input validation yet

That's a valid argument and actually a good idea to add some negative tests.
Could you please add some negative tests? What I have in mind is something like this:

Add one test case that tests invalid inputs for the two functions for which we have added input validation and call either of them with the format that would be expected by the respective other function. And we can also try to pass totally invalid `bins` that are not integers to them. This should be enough negative testing.

I am sorry to ask for something new again :see_no_evil:

2023-11-22 18:17 UTC, MaLoefUDS commented on util-split.R
> +    dates = parallel::mclapply(bins, get.date.from.string)
When testing whether the more complex format of `bins` from `split.data.by.bins` produce issues in the input validation of `split.data.time.based` I encountered this issue again from https://github.com/se-sic/coronet/pull/244#discussion_r1400689507: 

(For context, the comment is talking about the conversion by `get.date.from.string` of the more complex type of `bins`, which is applied in the input validation of `split.data.time.based`)

> 1. What it does is, it sets all values in the `bins[["vector"]]` to `NA` and all the values in the`bins[["bins"]]` to the dates they were before (as intended). Then it goes over all elements in bins (which are `vector` and `bins`) and says, none of those are `NA`, this is why it does not go into the error case.

In this case this will still produce an error in the execution of the splitting logic later on, but I think it would be better to check for this case in the input validation and early exit. 

Is it fine if I amend it to [Improve input validation](https://github.com/se-sic/coronet/pull/244/commits/bb5aeb242b69c0e5b242b3a347e7f3b7462adb43) or does it need a separate commit?

2023-11-22 18:27 UTC, bockthom commented on util-split.R
> +    dates = parallel::mclapply(bins, get.date.from.string)
First of all, it is good that we already get an error in this case - better than nothing :smile: 
But I agree with you: If we can check it earlier and, thus, we receive a more appropriate error message, it would be better.

And yes, of course, you can amend the last commit. As long as this PR is not merged yet and as long as it does make sense to amend the last commit because the changes are somehow related, I am fine with amending. But keep in mind that you can also adjust the commit message while amending...

2023-11-22 19:33 UTC, bockthom commented on util-split.R
> +    dates = parallel::mclapply(bins, get.date.from.string)
I am a little bit confused by your commit message.
"Disallowing non-unlisted named lists" means what? :confused: 

Why not saying something like "disallow lists that contain elements that are not representing a date, as they do not comply with the expected format of bins for 'split.data.by.time.or.bins'."?


---


Btw, I just noticed that the error message is a little bit imprecise: 

```R
dates = parallel::mclapply(unlist(bins), get.date.from.string)
if (any(is.na(dates))) {
    logging::logerror("The bins parameter, if present, needs to be a character representing a date")
```
The bins parameter usually is not a character representing a date, but usally a _character vector_ representing _multiple dates_, right?

2023-11-22 19:36 UTC, bockthom commented on tests/test-split-data-activity-based.R
> +test_that("Split a data object time-based with invalid bins parameter.", {
Shouldn't the test have a different name than the other test? I miss a "by bins" after time-based here...

2023-11-23 12:02 UTC, MaLoefUDS commented on tests/test-split-data-activity-based.R
> +test_that("Split a data object time-based with invalid bins parameter.", {
I can add that, surely

2023-11-23 12:07 UTC, MaLoefUDS commented on util-split.R
> +    dates = parallel::mclapply(bins, get.date.from.string)
The problem I encountered was that there are named lists and named lists. One of the format
```R
$a
[1] 1 2 3

$b
[1] 2 3 4
```
and one of the format
```R
a1 a2 a3 b1 b2 b3 
 1  2  3  2  3  4 
```

Both are named lists, however `list1[1]` yields
```R
$a
[1] 1 2 3
```
(which is an issue),
and `list2[1]` yields
```R
a1 
 1
```
(which is not an issue).

Sorry for my confusing comment, I will change it 👍

2023-11-23 12:08 UTC, MaLoefUDS commented on util-split.R
> +    dates = parallel::mclapply(bins, get.date.from.string)
Yes, about the error message im with you!

2023-11-28 09:28 UTC, MaLoefUDS commented
(I just found out that I used paste0 is not what I want here so I needed to amend once more 💀)

2023-11-28 09:54 UTC, bockthom requested changes

2023-11-28 09:54 UTC, bockthom commented on tests/test-split-data-time-based.R
> +test_that("Split a data object time-based by bins with invalid bins parameter.", {
Please correct me if I am wrong, but did you add "by bins" to wrong test?

2023-11-28 09:54 UTC, bockthom commented on tests/test-split-data-activity-based.R
> +test_that("Split a data object time-based with invalid bins parameter.", {
I am not sure if this is the right position for the test here. As the test handles bins, it belongs rather to time based splitting than to activity-based splitting. So, I would suggest to move this test to test-split-data-time-based.R.

2023-11-28 09:54 UTC, bockthom commented on util-split.R
> +                                "whose elements represent dates"))
needs to be **a** vector

2023-11-28 09:54 UTC, bockthom commented on util-split.R
> +            logging::logerror(paste("The bins parameter, if present, needs to be vector",
needs to be **a** vector

2023-11-29 07:19 UTC, MaLoefUDS commented on tests/test-split-data-time-based.R
> +test_that("Split a data object time-based by bins with invalid bins parameter.", {
Hmm to me it looks like it’s the right test, I only added two, one for time based and one for activity based splitting, and this is the time based one

2023-11-29 07:20 UTC, MaLoefUDS commented on tests/test-split-data-activity-based.R
> +test_that("Split a data object time-based with invalid bins parameter.", {
Yeah I was not sure about the position either 😅 should I just move it to the other test I added?

2023-11-29 07:31 UTC, bockthom commented on tests/test-split-data-time-based.R
> +test_that("Split a data object time-based by bins with invalid bins parameter.", {
I am confused now. What I meant was the following:
The test that starts in line 1805 of test-split-data-activity-based.R tests `split.data.by.bins`, but the test name says `Split a data object time-based`. So, there, in line 1805, it should be `Split a data object by bins`, if I am not mistaken.

But here, starting in line 968 in test-split-data-time-based.R, `split.data.time.based` is tested (**not** `split.data.by.bins`). So, I think that the "by bins" that you have add here in line 968 is wrong, as it should be added to line 1805 in the other test file instead.

2023-11-29 07:37 UTC, bockthom commented on tests/test-split-data-activity-based.R
> +test_that("Split a data object time-based with invalid bins parameter.", {
Yeah, I also have talked about the test position together with @hechtlC and he also voted for moving it to test-split-data-time-based.R.

So I would suggest to move it directly below the other test that you already have added to test-split-data-time-based.R.

2023-11-29 11:18 UTC, MaLoefUDS commented on tests/test-split-data-time-based.R
> +test_that("Split a data object time-based by bins with invalid bins parameter.", {
Ohhh yeah you're right, I got the wrong test.

Actually the other test does not perform splitting by time but just splitting by given bins (which come from activity based splitting [which is why I moved it into the activity test file]) so the test caption is wrong altogether and I will update both when I get to it :)

2023-11-29 11:41 UTC, bockthom commented on tests/test-split-data-time-based.R
> +test_that("Split a data object time-based by bins with invalid bins parameter.", {
[even if splitting by bins is called by activity-based splitting, the splitting by bins per se is time based as the bins denote time stamps]

2023-12-02 14:36 UTC, MaLoefUDS commented on tests/test-split-data-time-based.R
> +test_that("Split a data object time-based by bins with invalid bins parameter.", {
Actually not. The relevant information after which is being split in this case in the bins vector (which is activity based). The dates in the bins are used as labels and attributes and whatnot but not for splitting itself.

2023-12-05 12:11 UTC, hechtlC commented on tests/test-split-data-time-based.R
> +test_that("Split a data object time-based by bins with invalid bins parameter.", {
I would prefer to have the test in `test-split-misc.R`.

2023-12-06 09:26 UTC, bockthom requested changes

2023-12-06 09:26 UTC, bockthom commented on tests/test-split-misc.R
> +##
@MaLoefUDS  Could you please add your copyright header at the beginning of this file `test-split-misc.R` ?

2023-12-10 17:39 UTC, bockthom commented
Thanks @MaLoefUDS for addressing my last comment. Now, everything I've spotted seems to be fixed now.
I will do my best to have a look at the changed tests until our meeting on Wednesday, because I would like to merge this PR before Christmas. 

So, given that I don't spot anything problematic in the changed tests (but we'll see), the only thing missing is the update of the `NEWS.md`. Could you please already collect the different changes from this PR and sort them into the different categories (fixed, added, changed/improved), so that we can discuss them on Wednesday? (Not every single change needs to be listed separately, many of them can be combined into one single item, I guess.) Also don't forget about this one here: https://github.com/se-sic/coronet/pull/244#discussion_r1331663005

2023-12-11 21:38 UTC, bockthom requested changes
I found some time to have a look at the tests on a sample basis. 
In general, the tests (at which I had a look at) look good. I spotted a few minor inconsistencies and a few changes that we should double-check and document.

In addition, I spotted one inconsistency in the test data :see_no_evil: 

Moreover, after everything is fixed in the test data, we need to copy 
`test_feature/feature/issues-github.list` to `test_proximity/proximity/issues-github.list`, and the same also for `issues-jira.list`, as our basic assumption is that the issue data for feature and proximity are the same.

2023-12-11 21:38 UTC, bockthom commented on tests/test-networks-artifact.R
> +                                   "<issue-github-6>"),
The order looks a little bit weird. As in the test directly above, I would start with 328, followed by 332...

2023-12-12 10:44 UTC, MaLoefUDS commented on tests/test-split-data-activity-based.R
> +        split.sliding.window = FALSE,
To be honest, I cannot find the reason why it has not been like this before and it had to be changed. But I remember, that I fixed something and this was also a consequence from it (from the timestamps, it was most likely something about removing the last range debate we had). 

The code which sets the `sliding.window` to false can be found in util-split line 980 and was not introduced by me:
```R
if ((length(bins.ranges) <= 1) && sliding.window) {
    logging::logwarn("Sliding-window approach does not apply for one range or less.")
    sliding.window = FALSE
}
```

This test here checks the splitting info set for each individual split returning from `split.data.activity.based` (compared to the splitting info set for the "global config") and therefore I think its fair to say that `sliding.window` is false. But I would need to dive in deeper to find the reason for the change.

2023-12-12 10:46 UTC, MaLoefUDS commented on tests/codeface-data/results/testing/test_feature/feature/issues-jira.list
> +"ZEPPELIN-332";"[ZEPPELIN-332] CNFE when running SQL query against Cassandra temp table";"[""issue"", ""bug""]";"open";"[""unresolved""]";"2016-07-12 16:01:30";"";"[""Interpreters""]";"referenced_by"
Oh god, this sounds like fun 😂

2023-12-12 11:30 UTC, bockthom commented on tests/codeface-data/results/testing/test_feature/feature/issues-jira.list
> +"ZEPPELIN-332";"[ZEPPELIN-332] CNFE when running SQL query against Cassandra temp table";"[""issue"", ""bug""]";"open";"[""unresolved""]";"2016-07-12 16:01:30";"";"[""Interpreters""]";"referenced_by"
I know. And I am sorry for that. But the change I suggested should be the least expensive one - just flipping "referenced_by" and "add_link" and changing two dates. I know, changing the dates will affect many of splitting test, but not all.

2023-12-12 11:34 UTC, bockthom commented on tests/test-split-data-activity-based.R
> +        split.sliding.window = FALSE,
Ok, but then I would like to add the information from the warning message also as a comment in the tests.
But still it is important to check that this behavior is idententical for the different splitting methods. So, activity-based, time-based, what ever splitting all need to set the splitting information to false in such a case - otherwise it would be inconsistent. Could you please check that?

2023-12-19 13:38 UTC, MaLoefUDS commented on tests/test-networks-artifact.R
> +                                   "<issue-github-6>"),
Unfortunately the order cannot be freely chosen, since both `igraph::identical_graphs` as well as `compare.networks` also test for the order of elements in the vertices column 🫠.

2023-12-19 14:16 UTC, bockthom commented on tests/test-networks-artifact.R
> +                                   "<issue-github-6>"),
Ok, but this is weird. Why would one order the vertices in this crazy order? It is neither ordered lexicographically, nor by occurrence in the data.
But if igraph wants to use exactly this order, then we don't have another choice, I guess...

2023-12-19 22:33 UTC, bockthom commented on tests/test-data.R
> +    ## there are now 42 issue events remaining, since 11 issue events have been removed during filtering
@MaLoefUDS Did you forget about this one? I could not spot this change in your today's commits...

2023-12-20 08:52 UTC, MaLoefUDS commented on tests/test-data.R
> +    ## there are now 42 issue events remaining, since 11 issue events have been removed during filtering
No I just wanted to commit the other changes before leaving work for the day, and for this change I wanted to wait for your answer on the comment with the weird vertices order. I will commit this fix soon

2023-12-20 11:53 UTC, bockthom requested changes
Thanks for updating the NEWS.md. There is one major issue: You have added the changes to the v4.3 version, which has already been released. This is not a good idea, we will not change a past release. So, please move all your changes to a new section and just call it `## unversioned`. We will add a version number when the next release will be scheduled. Also make sure that we have two empty lines when the version section ends, to be consistent with the previous versions.

I agree with the commits you have referenced, but sometimes I would like to add another commit in addition, if a change is not fully implemented in one commit (and here I only speak of real implementation commits that affect the behavior, not only tiny changes). I added suggestions for these commits below.

2023-12-20 11:53 UTC, bockthom commented on NEWS.md
> +- Enhance testing data by adding 'add_link' and 'referenced_by' issue events which connect issues to form edges in issue-based artifact-networks (PR #244, 9f840c040d552e8639aa82c3dd537c189679b348)
Please add another commit hash here in addition: ea4fe8d3c84f948af6147cf0137e80181ebb7a1e

2023-12-20 11:53 UTC, bockthom commented on NEWS.md
> +- Add issue-based artifact-networks (PR #244, 98a93ee721a293410623aafe46890cfba9d81e72)
Please add this commit hash in addition: 771bcc8d961d419b53a1e891e9dc536371f1143b

2023-12-20 11:53 UTC, bockthom commented on NEWS.md
> +- Add input validation for the 'bins' parameter in time-, and bin-based splitting (PR #244, ed0a5302ea8c8934d7200b95be7ac1446305af07)
Please name all the affected functions instead of just saying "time- and bin-based splitting". This makes it easier to grep the NEWS.md for specific function names to find out if there has changed something :)

And also add this commit hash here in addition: 5e5ecbac44d07927b953ae9d4330a616f8224ba7

2023-12-20 11:53 UTC, bockthom commented on NEWS.md
> +- (Re)add 'split.data.by.bins' function which splits data based on given activity-based bins (PR #244, ece569ceaf557bb38cd0cfad437b69b30fe8a698)
Instead of "(Re)add" I would prefer to write "Add a new ... function (not to be confused with a previously existing function that had the same name and was renamed in this context)"

As this function was renamed after the referenced commits, we should also add the commit hash of the commit that does the renaming: ed5feb214a123b605c9513262f187cfd72b9e1f4

2023-12-20 11:53 UTC, bockthom commented on NEWS.md
> +- Replace time-based splitting as a helper inside activity-based splitting, because of its imprecision, by pure bin-based splitting (see 'split.data.by.bins'). Previously activity-based splitting par
That sounds very complex. Can we put the spotlight on the actual fix instead of discussing implementation details?
That is, it does not matter whether time-based splitting was used as a helper inside activity-based splitting. Instead, we should start with the problem that has been fixed here. Speaking of time-based splitting sounds confusing, as this change should not affect time-based splitting at all. So, for me, it is more important to state what has been fixed and why than explaining how this has been fixed, if it is just an implementation detail that is not relevant to the user. So, the "how" part could be placed at the end of the item, if it makes sense, but I would not put it at the beginning...

2023-12-20 11:53 UTC, bockthom commented on NEWS.md
> +- Remove last range when using a sliding-window approach and the last ranges elements are fully contained in the second last range (PR #244, 48ef4fa685adf6e5d85281e5b90a8ed8f6aeb197)
the last ranges elements :arrow_right: the last range's elements

2023-12-20 11:53 UTC, bockthom commented on NEWS.md
> +- Rename vertex attribute from 'IssueEvent' to 'Issue' in multi-networks to be consistent with bipartite-networks (PR #244, 26d7b7e9fd6d33d1c0a8a08f19c5c2e30346a3d9)
Not sure about the wording, what about "Rename vertex attribute 'IssueEvent' to 'Issue' in multi-networks, to be..."

2023-12-20 12:01 UTC, bockthom reviewed
And one more comment: Please use backticks  around function names and strings such as `referenced_by` or `IssueEvent`  instead of ', such that it is properly highlighted by markdown.

2023-12-20 13:19 UTC, hechtlC approved these changes

2023-12-20 15:35 UTC, bockthom approved these changes
Finally, everything seems to be fine with this PR.
Many thanks @MaLoefUDS for your commitment and endurance in this PR. This was a really tough one, also due to plenty of necessary changes to the test data and splitting tests. But we also spotted bugs along this way and improved the splitting functionality  substantially, which is a good result for a long PR that was supposed to "just" introduce issue-based artifact networks :smile:

2023-12-20 15:38 UTC, merged