Tests and Fixes for utils-networks-misc.R
se-sic/coronet pull request #248
Opened 2024-01-09 15:42 UTC by Leo-Send

### Prerequisites

- [ ] I adhere to the coding conventions (described [here](../CONTRIBUTING.md)) in my code.
- [ ] I have updated the copyright headers of the files I have modified.
- [ ] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [ ] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](../NEWS.md) appropriately.
- [ ] I have checked whether I need to adjust the showcase file `showcase.R` with respect to my changes.
- [ ] The pull request is opened against the branch `dev`.

### Description

### Changelog

2024-01-17 15:15 UTC, hechtlC requested changes
The pull request looks good. Thanks for the new tests and the fixes @Leo-Send !
I have just found some small issues that need to be fixed. After they have been fixed and @bockthom is fine with the changes, we can merge the PR.

2024-01-17 15:15 UTC, hechtlC commented on util-networks-misc.R
> +                if(length(matrices.cumulated[[m]]@i) > 0) {
space after if

2024-01-17 15:15 UTC, hechtlC commented on util-networks-misc.R
> +    ## Check if all matrices have equal colomn- and rownames
column

2024-01-17 15:15 UTC, hechtlC commented on util-networks-misc.R
> +                error.string = sprintf("The matrix at position %d has a different col or rownames from the first!", i)
rowname nicht im plural

2024-01-17 15:15 UTC, hechtlC commented on tests/test-util-networks-misc.R
> +    second.network = igraph::graph.data.frame(second.edges, directed = FALSE, vertices = second.vertices)
Add a new line before the Act as you do in all other tests please

2024-01-17 15:15 UTC, hechtlC commented on tests/test-util-networks-misc.R
> +    second.network = igraph::graph.data.frame(second.edges, directed = FALSE, vertices = second.vertices)
same here

2024-01-24 15:35 UTC, bockthom requested changes
Looks good to me @Leo-Send, I only found "a few" indentation or formatting issues :wink: 
I am not sure if you use tabs or spaces during implementation - it might be that the wrong indentation comes from using tabs instead of spaces - if so, please configure your IDE in such a way that it does not use tabs.

And there is one line where the code should be made fail save (but nothing critical, so **no** need to adjust the NEWS), and sometimes an additional comment would be helpful. See my detailed comments below.

2024-01-24 15:35 UTC, bockthom commented on util-tensor.R
> +            private$authors = get.author.names.from.networks(networks)[[1]]
Is this always correct?

2024-01-24 15:35 UTC, bockthom commented on tests/test-util-networks-misc.R
> +                    "Karl", "Olaf", "Thomas", "udo"))
Indentation: "Karl" belongs to the vector, it should start below Björn.

2024-01-24 15:35 UTC, bockthom commented on tests/test-util-networks-misc.R
> +                    "Karl", "Olaf", "Thomas", "udo"))
Indentation again.

2024-01-24 15:35 UTC, bockthom commented on tests/test-util-networks-misc.R
> +                                                            data.sources = "issues", globally = FALSE)
Indentation: `data.sources` should align with `data.ranges`.

2024-01-24 15:35 UTC, bockthom commented on tests/test-util-networks-misc.R
> +                                                            data.sources = "commits", globally = FALSE)
Indentation: `data.sources` should align with `data.ranges`.

2024-01-24 15:35 UTC, bockthom commented on tests/test-util-networks-misc.R
> +                                            repr = "T")
Indentation: `dims` and `repr` should align with `i`

2024-01-24 15:35 UTC, bockthom commented on tests/test-util-networks-misc.R
> +                                            repr = "T")
Indentation, see above.

2024-01-24 15:35 UTC, bockthom commented on tests/test-util-networks-misc.R
> +    result = get.expanded.adjacency(network =network.in, authors = authors.in)
Missing space after `=`

2024-01-24 15:35 UTC, bockthom commented on tests/test-util-networks-misc.R
> +                                            repr = "T")
Indentation.

2024-01-25 12:22 UTC, Leo-Send commented on util-networks-misc.R
> +                    col = matrices.cumulated[[m]]@j[[1]] + 1
I wrote 
'the first non-zero entry of a sparse matrix is at the first position pointed to by the lists @i and @j of the matrix. Since these lists store the position 0-based, but the list access we use them for is 1-based, we need to add 1 to both values'

is that okay? I do not really know how to explain it better than this.

2024-01-25 12:28 UTC, Leo-Send commented on util-tensor.R
> +            private$authors = get.author.names.from.networks(networks)[[1]]
Yes. If the 'globally' flag in the function call for 'get.author.names.from.networks' or 'get.author.names.from.data' is set, which is the default, the returned value is a list with a single entry, namely a vector with all the author names. Previous to my change to the return type of these functions, the returned value was that same vector without a list around it.

2024-01-25 12:29 UTC, bockthom commented on util-networks-misc.R
> +                    col = matrices.cumulated[[m]]@j[[1]] + 1
Sounds good! This is exactly the piece of information that is not easily extractable from the code itself. So, with this comment, it is understandable what's going on there.

Btw, please don't use the "@" symbol at the beginning of a word in comment on GitHub - this leads to automatically linking your comment to the GitHub users - so, by your comment, the users "i" and "j" were mentioned and subscribed to this PR. I guess we should avoid that if possible to not spam these users :wink: But no worries, I also did similar thinks some time ago, it just happens...

2024-01-25 12:31 UTC, bockthom commented on util-tensor.R
> +            private$authors = get.author.names.from.networks(networks)[[1]]
Ok, then it is fine. Thanks for the explanation. I just wanted to make sure that we don't overlook something here.

2024-01-25 12:45 UTC, Leo-Send commented on util-networks-misc.R
> +                    col = matrices.cumulated[[m]]@j[[1]] + 1
Right, I'll keep that in mind.

2024-01-25 12:48 UTC, bockthom commented on NEWS.md
> +- Fix `convert.adjacency.matrix.list.to.array` to throw an error if the function is called with wrong parameters (PR #248, ece2d38b4972745af3a83e06f32317a06465a345, 1a3e510df15f5fa4e920e9fce3e0e162c2
Please avoid the word "Fix" at beginning of an item if the item does not belong to the "Fixed" category, that would be confusing.
Instead, I would suggest to simply start as follows: "Throw an error in `convert.adjacency.matrix.list.to.array` if..."

2024-01-25 14:19 UTC, bockthom approved these changes

2024-01-25 14:31 UTC, hechtlC approved these changes

2024-01-25 14:32 UTC, merged