Adding commit-interactions
se-sic/coronet pull request #252
Opened 2024-02-12 13:15 UTC by Leo-Send

### Prerequisites

- [X] I adhere to the coding conventions (described [here](../CONTRIBUTING.md)) in my code.
- [X] I have updated the copyright headers of the files I have modified.
- [X] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [X] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](../NEWS.md) appropriately.
- [ ] I have checked whether I need to adjust the showcase file `showcase.R` with respect to my changes.
- [X] The pull request is opened against the branch `dev`.

### Description

### Changelog

2024-03-18 13:59 UTC, hechtlC requested changes
Thank you for the addition @Leo-Send ! Looks good apart from some minor points that I have marked in the review. Especially the test data need to be changed and all tests accordingly.

2024-03-18 13:59 UTC, hechtlC commented on util-data.R
> +        set.commit.interactions = function(data) {
Could you please add the check that the data is in the correct format here? You can see an example in `set.commits`.

2024-03-18 13:59 UTC, hechtlC commented on util-networks.R
> +              ## change the vertices to the functions from the commit-interaction data
files not functions

2024-03-18 13:59 UTC, hechtlC commented on util-networks.R
> +            logging::logwarn("when creating a commit-interaction artifact network,
Please start with an uppercase letter here as this is a complete sentence.

2024-03-18 13:59 UTC, hechtlC commented on tests/codeface-data/results/testing/test_proximity/proximity/commit-interactions.yaml
> +          function:       test.c
test.c is not the function but the file that the commits interact in. Here you need to change it to the function that is mentioned in the commit. If this function is File_Level, then you can just remove the function tag from the interaction altogether as then the GLOBAL tag will be added when reading.

2024-03-18 13:59 UTC, hechtlC commented on tests/test-networks-artifact.R
> +    ## build the expected nbetwork
Typo. Also in the author network test.

2024-03-21 16:09 UTC, bockthom requested changes
@Leo-Send thanks for this great work on commit-interaction data! Adding a completely new data source to coronet is always a hassle. Especially, as there are many small places one is not aware of if you haven't added a new data source to coronet yet. So, no worries, this is quite usual when adding huge new features like this one.

Therefore, I tried to spot these places that demand adjustment; I am pretty sure that there may still be additional places that I did not spot yet during my review... Anyway, in addition, I also spotted a couple of inconsistencies with regard to the behavior of corner cases of other data sources. And I also have some ideas on how to improve specific parts of the implementation.

Please see all my detailed comments below. Don't hesitate to comment on my comments if something is unclear. Also @hechtlC can provide some help on some of the comments, I guess :smile:

2024-03-21 16:14 UTC, bockthom commented
And one comment that I did forget in my review: There are some commits whose commit messages do not comply with the contribution policy of coronet: Commit messages have to be in present tense, as explained in our contribution guide. That is, commit messages starting with "Changed" or "Added", for example, are not allowed. Instead, please use "Change" or "Add". So, most of your commit messages are ok, but a few commit messages need to be reworded. (Notice that rewording will change the commit hash and also the commit hashes of all subsequent commits during a rebase. So, maybe you perform the rewording in the end when you perform the rebase onto the most recent dev version after our version release.)

2024-03-21 17:06 UTC, bockthom commented on tests/codeface-data/results/testing/test_proximity/proximity/commit-interactions.yaml
And since you have added new test data: Please also update the corresponding `tests/README.md` file.

2024-03-27 15:12 UTC, Leo-Send commented on util-data.R
> +            }
You are right. The reason why I did this was because I thought of the case where there is a deleted user in the commit data for the matching commit and this commit gets then removed, leading to the whole commit missing. I will update the comment to 'There are commits in the commit-interactions that are not in the commit data, possibly due to incomplete commit data or deleted users. This results in...'

2024-03-27 15:35 UTC, Leo-Send commented on util-networks.R
> +                available.edge.attributes = list(hash = "character")
You are right, I changed it to match the author network construction using different relations, meaning that in now uses 'available.edge.attributes = private$proj.data$get.data.columns.for.data.source("commit.interactions")'.

2024-03-27 15:43 UTC, Leo-Send commented on util-networks.R
> +                available.edge.attributes = list(hash = "character")
This however requires an update to the function 'get.data.columns.for.data.source'.

2024-03-27 16:38 UTC, Leo-Send commented on util-read.R
> +    list.names = names(result.map)
`## extract a mapping of functions to files to be able to determine what file the current interaction is
    ## based on
    ## 1) create an empty map
    file.name.map = fastmap::fastmap()
    ## 2) create a mapping between functions (first entries in 'result-map')
    ## and files (second entry of following dataframes) as a list
    function.file.list = purrr::map(result.map, 2)
    ## 3) set the map using the list
    file.name.map$mset(.list = function.file.list)
    list.names = names(result.map)`
    
    Is this clear enough or does it need more clarity?

2024-03-27 16:54 UTC, Leo-Send commented on util-read.R
> +                    return(data.frame(func = "GLOBAL", commit.hash = hash[["commit"]], file = "GLOBAL"))
To address the first point: if there is no function name in the current interaction, we can also not know the file since we use the mapping of functions to files created previously to figure out the file. Currently we are using 'GLOBAL' for both function and file name in that case, although renaming that is of course an option.

To address the second point: 'GLOBAL' is not treated differently than other function or file names anywhere.

2024-03-27 17:06 UTC, Leo-Send commented on util-read.R
> +                                      file = file.name.map$get(hash[["function"]])))
That happens in 'read.commits', in my code in line 171 in 'util-read'. We do not, however, use the file/function names from the commit data when creating commit interactions, since we are using the data contained in the commit interactions data directly. Do we want to make this more uniform? It is possible to write 'file_name::function_name' as the function name in the function column of non-GLOBAL functions without issues.

2024-03-29 23:57 UTC, bockthom commented on util-data.R
> +        update.commit.interactions = function() {
Sounds good to me.

2024-03-29 23:59 UTC, bockthom commented on util-data.R
> +            }
Good point that missing data can also originate from deleted users. I agree with your updated comment that contains both possible reasons.

2024-03-30 00:20 UTC, bockthom commented on util-networks.R
> +                available.edge.attributes = list(hash = "character")
I dislike the idea of hard-coding. I am not sure what the best option here is, but I have two different ideas now:

(1) Allow commit interactions in `get.data.columns.for.data.source`. Then a check within the function `get.data.columns.for.data.source` on whether `DATASOURCE.TO.ARTIFACT.FUNCTION[[data.source]]` exists would be necessary, and if it does not exist (what would be the case for all the additional data sources, such as commit interactions), `DATASOURCE.TO.ADDITIONAL.ARTIFACT.FUNCTION` would be used instead.
Advantage: Behavior of `get.data.columns.for.data.source` does what it should do, no interface changes necessary.
Drawback: `get.data.columns.for.data.source` would mix main and additional data sources, not sure if this can cause other problems.

(2) Provide a second version of the function called `get.data.columns.for.additional.data.source` which only works for additional data sources and uses the corresponding mapping.
Advantage: The already existing function `get.data.columns.for.data.source` remains unchanged, no mixture of main and additional data sources.
Drawback: Potential code duplication (in parts), and the caller needs to be sure to call the correct function. However, the latter should not be a problem as the function is private.

Maybe you can also come up with different variants of these ideas and also check other callers of the function `get.data.columns.for.data.source` whether there could be other problems with one of my ideas that I did not have in mind. To be honest, I am not sure what would be the best option for coronet in general, to allow extensibility and consistency with existing code. At the moment, _I tend towards option (1)_, as this seems to be the easiest solution to me that also allows for extensibility with regard to all the other additional data sources. Maybe you can discuss this in your next meeting and also ask for @hechtlC's opinion on that.

2024-03-30 00:28 UTC, bockthom commented on util-read.R
> +    list.names = names(result.map)
In general, it is clear enough. I like your suggestions, now it is easier to understand.
However, I am a little bit confused by the content within parenthesis: "first entries in 'result-map'" and "second entry of following dataframes" - what does "first/second" refer to? why is first in plural but second singular? and what is meant by "following dataframes"? And finally, how does the mapping "as a list" look like? Does this list contain pairs as vectors c(function, file) as its elements or something differently? Maybe providing an example of how the list looks like would also be an option if it is more complicated than I understand....

2024-03-30 00:44 UTC, bockthom commented on util-read.R
> +                    return(data.frame(func = "GLOBAL", commit.hash = hash[["commit"]], file = "GLOBAL"))
> To address the first point: if there is no function name in the current interaction, we can also not know the file since we use the mapping of functions to files created previously to figure out the file. Currently we are using 'GLOBAL' for both function and file name in that case, although renaming that is of course an option.

I see. As file information is not available, it is not necessary to rename everything. Nevertheless, one could still think about renaming just the `func` part. But I am not sure if this could lead to problems. So, given that file information is not available, I would be fine with keeping `GLOBAL` or with renaming it. In some cases it might be helpful to use different dummy names such as for files (`GLOBAL`) and functions (`File_Level`). However, I am not sure if there are different semantics for both values in this special case. So, I leave this decision to @hechtlC. 

> To address the second point: 'GLOBAL' is not treated differently than other function or file names anywhere.

Maybe not yet :wink If you would like to filter for `GLOBAL` later on, using a constant (or two different ones for files and functions) might help. However, I am not sure about the actual treatment of `GLOBAL`. So, I again leave this decision to @hechtlC.

Nevertheless, let me add a final question. I don't expect an answer to this question, but it might be interesting to check for some corner cases. What happens with `GLOBAL` during network construction? Do we get a `GLOBAL` artifact that acts like a hub as `GLOBAL` refers to everything and is connected to everything? If so, one idea would be to ignore `GLOBAL` during (artifact-)network construction or at all. Another idea would be to enable filtering mechanisms similar to the filtering of base artifacts (defined in `BASE.ARTIFACTS`). Maybe it is worth to think about such cases for longer...

2024-03-30 00:50 UTC, bockthom commented on util-read.R
> +                                      file = file.name.map$get(hash[["function"]])))
I would vote for 'file_name::function_name', as this would be more consistent with how we handle commit data, and as this would also avoid artifact networks merging to functions to one artifact although the artifact actually represents to different functions in two different files that share the same name. However, I have no clue what the file and function names in the commit-interaction data actually refer to; thus, I suggest to wait for @hechtlC's assessment of whether this makes sense or not.

2024-04-05 11:25 UTC, Leo-Send commented on util-networks.R
> +                available.edge.attributes = list(hash = "character")
We came to the conclusion that we should include commit interactions in 'get.data.columns.for.data.source'.

2024-04-05 11:28 UTC, Leo-Send commented on util-read.R
> +    list.names = names(result.map)
I simply removed the paranthesis... I was trying to explain why the function call has the arguments '(result.map, 2)'. As @hechtlC pointed out, it should be okay to be a bit more vague with the description instead of trying to explain what that function does exactly in a large paragraph. The new comment is

> create a mapping between functions and files as a named list which can be directly converted to a map

2024-04-05 11:44 UTC, Leo-Send commented on util-read.R
> +                                      file = file.name.map$get(hash[["function"]])))
After talking to @hechtlC I have done it in the way you suggested.

2024-04-05 11:58 UTC, Leo-Send commented on tests/test-networks-author.R
> +test_that("Network construction with commit-interactions as relation", {
Since it does not make a difference, I tested it using patrick.

2024-04-05 12:09 UTC, Leo-Send commented on util-read.R
> +                    return(data.frame(func = "GLOBAL", commit.hash = hash[["commit"]], file = "GLOBAL"))
I added a global variable called COMMIT.INTERACTION.GLOBAL.FILE.FUNCTION.NAME and plan on adding a filtering function as well. Should filtering happen when reading, getting or updating?

2024-04-08 09:53 UTC, bockthom commented on util-read.R
> +    list.names = names(result.map)
I like the short version of the comment. It is clearly understandable and precise enough.

Just one idea regarding the parameter `2`: Does `result.map` have names? If so, does `purrr::map` allow access via names instead of numbers? If so, we could replace the `2` by the actual name. But just an idea, I don't know how this map stuff works and what it is capable of. So, just forget about my idea if such an replacement does not work, then we need to stick to the `2`.

2024-04-08 10:06 UTC, bockthom commented on util-read.R
> +                    return(data.frame(func = "GLOBAL", commit.hash = hash[["commit"]], file = "GLOBAL"))
> Should filtering happen when reading, getting or updating?

It depends. If you assume that this information could never be used in a reasonable way, then it could be filtered already during reading (such as we do for the deleted user or the empty user). Otherwise, if `GLOBAL` contains some information on commit interactions that could potentially be used, such as the base artifact in commit data (i.e., the base feature for features, file-level information for functions, untracked files for files) or patchstack mails in the mail data, then I would prefer a similar mechanism as we use for filtering commit and mail data.

2024-04-08 10:35 UTC, bockthom reviewed
While looking at your new changes, I just spotted a few typos etc.

2024-04-08 10:35 UTC, bockthom commented on README.md
> +    * For artifact networks (configured via `artifact.relation` in the [`NetworkConf`](#networkconf)), artifacts are connected when there is a interacting between two commits that occur in the artifa
`a interacting` :arrow_right: `an interaction`

2024-04-08 10:35 UTC, bockthom commented on README.md
> +    * Alloow construction of author and artifact networks using commit interaction data
`Alloow` :arrow_right: `Allow`
`commit interaction data` :arrow_right: `commit-interaction data`

2024-04-08 10:35 UTC, bockthom commented on tests/README.md
> +     * Commit Interactions
lower-case "i" should be enough here, all the other data sources also only have the very first letter capitalized.

2024-04-08 10:35 UTC, bockthom commented on util-networks.R
> +                commit.interaction = private$proj.data$get.project.conf.entry("artifact.codeface")
Could you please adjust the indentation of the `=`  in this `switch` statement? (It previously the indentation was consistent, but after renaming it is not any more)

2024-04-08 10:35 UTC, bockthom commented on util-networks.R
> +              colnames(edges)[colnames(edges)=="commit.hash"] = "hash"
Missing spaces around `==`. (My bad, I did forget about the spaces in my code suggestion. Sorry for that.)

2024-04-08 10:35 UTC, bockthom commented on util-networks.R
> +             colnames(edges)[colnames(edges)=="commit.hash"] = "hash"
Missing spaces around `==`. (My bad, I did forget about the spaces in my code suggestion. Sorry for that.)

2024-04-08 10:35 UTC, bockthom commented on util-read.R
> +    ## which can be directly converted to a map
I'd prefer to indent the "which" with "create". (I'm picky, I know. Feel free to ignore this comment if you think I'm too picky here :wink:)

2024-04-10 10:30 UTC, Leo-Send commented on util-read.R
> +    list.names = names(result.map)
Your comment prompted me to try again to change all the numbers to names in the read method. I tried before and it didn't work, but now it seems I made a mistake (although i have no idea what went wrong before...). I changed all the numbers that were used to access a data frame to names.
It also works in the purrr::map call.

2024-04-18 15:29 UTC, bockthom requested changes
Thanks for your additions @Leo-Send. Almost done :wink: 
I only have a few comments, see them below.

2024-04-18 15:29 UTC, bockthom commented on tests/test-networks-author.R
> +    proj.conf$update.value("filter.commit.interactions", FALSE)
Would it make sense to also have a test that just uses the filtered data for network construction?
Not sure if it is worth the effort. For me it is not necessary, but what do you think @hechtlC?

2024-04-18 15:29 UTC, bockthom commented on util-read.R
> +#' Concatenation of function and file names, e.g. 'file::function'
Please phrase the function description as a complete sentence, such as "Concatenate function and file names, e.g., 'file::function'. Instead of "e.g.," I suggest "i.e.,", since the :: is not configurable and therefore it is not an example but just an explanation.

2024-04-18 15:29 UTC, bockthom commented on util-read.R
> +prefix.function.with.file.names = function(file.name, function.name) {
Shouldn't it be just "prefix.function.with.file.name", as there can be only one file name that is used as a prefix for a function name?

2024-04-18 15:29 UTC, bockthom commented on NEWS.md
> +- Add helper function for prefixing function names with file names in `util-read.R` (PR #252, f8ea987b138173cf0509c7910e0572d8ee1b3f1f)
Not sure if we should move this item regarding the helper function to "Changed/Improved", as previously existing functionality has been extracted to a new function, or whether we consider this as something new that can be globally used now. What do you think @hechtlC ?

2024-04-22 12:48 UTC, hechtlC commented on README.md
> +    * Filter out entries from commit interaction data that are not matched to a specific function or file
As these two go hand in hand, I am fine with this wording.

2024-04-22 12:50 UTC, hechtlC commented on NEWS.md
> +- Add helper function for prefixing function names with file names in `util-read.R` (PR #252, f8ea987b138173cf0509c7910e0572d8ee1b3f1f)
As this is new functionality (even though it has been implicitly used before) I am fine with keeping it in Added.

2024-04-23 10:29 UTC, bockthom requested changes
Looks good to me now! I only noticed that your copyright header is missing in two files that you have changed in this PR. Please add the copyright header there, then I am fine with this PR.

2024-04-23 10:29 UTC, bockthom commented on util-conf.R
Your copyright header in this file is missing.

2024-04-23 10:29 UTC, bockthom commented on install.R
Your copyright header in this file is missing.

2024-04-23 11:14 UTC, bockthom approved these changes

2024-04-23 11:20 UTC, hechtlC approved these changes
Looks good thanks @Leo-Send !
I will merge this.

2024-04-23 11:21 UTC, merged