Allow time-based data-splitting with multiple datasources as 'split.basis'
se-sic/coronet pull request #261
Opened 2024-04-27 09:45 UTC by MaLoefUDS

### Prerequisites

- [x] I adhere to the coding conventions (described [here](../CONTRIBUTING.md)) in my code.
- [x] I have updated the copyright headers of the files I have modified.
- [x] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [x] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](../NEWS.md) appropriately.
- [] I have checked whether I need to adjust the showcase file `showcase.R` with respect to my changes.
- [x] The pull request is opened against the branch `dev`.

### Description

Allow time-based data-splitting with multiple datasources as `split.basis`

### Changelog

#### Added
* Add test for new functionality

#### Changed
* Adjust handling of `split.basis` in `split.data.by.time.or.bins` and `split.data.time.based` to allow for splitting by multiple datasources

2024-04-30 12:04 UTC, bockthom requested changes
Thanks for this PR @MaLoefUDS.

Before I start with my actual review, just a general comment: Could you please reference the issue number somewhere in the PR? Either in the description of the PR or inside the commit messages of suitable commits, such that we have a connection between PR and issue? Thanks!

In general, this PR looks good. I just have a few comments.

2024-04-30 12:04 UTC, bockthom commented on tests/test-split-data-time-based.R
> +    expect_equal(max(attr(results, "bins")), max(c(issue.data$date, mail.data$date)) + 1)
Hm, I am not sure if it is enough to test for the minimum and maximum? Can it happen that something in between is wrong (i.e., the length of the first range) or is this already ensured by any other test? If so, then please add a comment why it is not necessary to test for the actual bins but just for minimum and maximum.

In addition, as also `split.data.by.bins` is affected by the changes of this PR, could you please also add a suitable test for that? Thanks!

2024-05-06 10:39 UTC, MaLoefUDS commented on tests/test-split-data-time-based.R
> +    expect_equal(max(attr(results, "bins")), max(c(issue.data$date, mail.data$date)) + 1)
Yes, these tests are not as broad as they could be. I did manually check the correctness of the bins, but I have not yet found a good way to unify the test with and without `sliding.windows`, since then we obtain additional (intermediary) bins. Do you have a good idea how to do that? I could do two tests, or just define two bins and decide based on `test.sliding.windows` which one to use?

2024-05-06 10:46 UTC, MaLoefUDS commented on util-split.R
> +    split.basis = match.arg(split.basis)
Well that is exactly what I intended. This PR and the issue that it stems from only describe splitting with multiple `split.basis` when splitting time based. Then, **when we create new bins**, we account for multiple datasources. 
When we split by **given bins**, I assumed we do not want to be able to provide bins as input that stem from multiple datasources. Therefore, I repositioned the check that was previously in place to check for that `split.basis` to only includes 1 datasource here in the one wrapper function, while in the other, I included the new check 😄.

2024-05-15 13:40 UTC, bockthom approved these changes
Looks good to me now.

2024-05-15 13:41 UTC, MaLoefUDS commented
I will update the `NEWS.md` later today 👍

2024-05-16 10:22 UTC, bockthom requested changes
Looks good to me. I just have two comments regarding comments.

2024-05-16 10:22 UTC, bockthom commented on NEWS.md
> +- Add the possibility to split data time-based by multiple data sources and according unit-tests (PR #261, d76aafad74cd9e83ebcc1368f28f77fe63ced7f4, 4d2ebd29f549453f9338116bde59dd327266dac3, b6e99f67
Please remove the part "and according unit-tests" - we generally assume that new functionality is properly tested.

2024-05-16 10:22 UTC, bockthom commented on showcase.R
> +cf.data = split.data.time.based(x.data, time.period = "18 month", split.basis = c("commits", "issues"))
Could you please add a short comment beforehand? (similar to the comment in line 309).
Maybe it would also make sense to add a comment to the previous splitting functionality above and to the activity-based below in line 318? Thus one line to highlight the differences of the different splitting variants.

2024-05-16 10:24 UTC, bockthom commented on NEWS.md
> +- Add the possibility to split data time-based by multiple data sources and according unit-tests (PR #261, d76aafad74cd9e83ebcc1368f28f77fe63ced7f4, 4d2ebd29f549453f9338116bde59dd327266dac3, b6e99f67
And one more comment: I'd prefer to merge this PR after the PR that introduces measuring code coverage. This way, we (1) get rid of the failing build pipeline for R 3.6, and (2) we can directly see whether the codecov functionality is properly working on this PR. Therefore, the commit hashes need to be updated after the corresponding rebase.

2024-05-17 09:07 UTC, MaLoefUDS commented on NEWS.md
> +- Add the possibility to split data time-based by multiple data sources and according unit-tests (PR #261, d76aafad74cd9e83ebcc1368f28f77fe63ced7f4, 4d2ebd29f549453f9338116bde59dd327266dac3, b6e99f67
I will therefore wait with fixing those issues in `NEWS.md` until #262 is merged 👍

2024-05-27 12:09 UTC, MaLoefUDS commented
🔔 Ping! Do not miss this PR :)

2024-05-27 12:12 UTC, bockthom commented
> 🔔 Ping! Do not miss this PR :)

Thanks for the ping. However, this time, the ping was not necessary :smile: Christian and I planned to have a look at this PR today anyway. So, I assume you will either receive comments later today or we will merge it later today.

2024-05-27 13:07 UTC, hechtlC submitted a review, later dismissed
Looks good to me thank you @MaLoefUDS !
I have one formatting comment that you have to address before merging but I approve the PR nonetheless. Please fix this and anything @bockthom might still find.

2024-05-27 13:07 UTC, hechtlC commented on util-split.R
> +    if(!hasArg("split.basis")) {
Space after if

2024-05-27 13:30 UTC, bockthom commented
> Please fix this and anything @bockthom might still find.

There is nothing else to find (at least, for me) :smile: 
So, I will merge right away after the missing space is fixed.

2024-05-27 13:55 UTC, bockthom approved these changes

2024-05-27 13:56 UTC, merged