Miscellaneous fixes and adjustments
se-sic/coronet pull request #274
Opened 2024-12-05 09:48 UTC by maxloeffler

### Prerequisites

- [x] I adhere to the coding conventions (described [here](../CONTRIBUTING.md)) in my code.
- [x] I have updated the copyright headers of the files I have modified.
- [x] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [x] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](../NEWS.md) appropriately.
- [ ] I have checked whether I need to adjust the showcase file `showcase.R` with respect to my changes.
- [x] The pull request is opened against the branch `dev`.

### Description

* Replace deprecated `igraph` functions by their more recent counterparts.
* Handle reading empty commit interaction data explicitly, to avoid crashing in that case.
* To make splitting networks by ranges more consistent with splitting time-based, also add range information to the return value.
* Convert certain edge attributes of networks to list type. This change is motivated by a more stricter type enforcement in `igraph` version 2.0 and up. When merging networks through `igraph::disjoint_union`, edge attributes that exist in both networks are now assumed to have identical types. But, when we simplify a network, its edge attributes convert to list type as they now need to store data that a vector in R cannot store anymore, i.e., one edge attribute now has to hold several *lists* of data of all the edges that got merged into one. Therefore, we need to convert edge attributes to list by default to be able to merge simplified and unsimplified networks.

### Changelog

#### Added

* Introduce `convert.edge.attributes.to.list` function.

#### Fixed

* Fix reading empty commit interaction data.

#### Changed / Improved

* Replace deprecated `igraph` functions.
* Add range information to the return value in `split.network.time.based.by.ranges`, to be consistent with `split.data.time.based`.
* Convert edge attributes to a list format to ensure compatibility with `igraph`.

2024-12-05 17:09 UTC, bockthom commented on util-split.R
> +    names(nets.split) = sapply(ranges.bounds, paste, collapse = "-")
A quick question here: Could we just use `ranges` instead of  reconstructing ranges from the range bounds that we have previously extracted from `ranges` ? Or am I missing something here?

2024-12-07 15:42 UTC, maxloeffler commented on util-split.R
> +    names(nets.split) = sapply(ranges.bounds, paste, collapse = "-")
That is not so easy to achieve as it may appear. The reason for this is that `ranges` does not always have the same format. Ranges constructed from `construct.ranges` are a named list in which the name of an entry is the range as `<time-A>-<time-B>` and the value associated with that name is then a vector as `chr[1:2] <time-A> <time-B>`. This means that to derive the valid range information from these ranges one would have to do `names(ranges)`. Other times, especially when called from `split.network.time.based`, `ranges` is just a vector in which all entries are of format `<time-A>-<time-B>` in which case you derive range information by just taking `ranges` as is.

After piping all of these through `get.range.bounds` earlier in the `split.network.time.based.by.ranges`, they follow the same format which allows for an easy reconstruction, so I thought it'll be an okayish solution to just do that. However, if you think otherwise, one could also check if `ranges` has names through `!(is.null(names(ranges)))` and depending on that select either the names or just the plain list.

2024-12-09 12:50 UTC, bockthom commented on util-split.R
> +    names(nets.split) = sapply(ranges.bounds, paste, collapse = "-")
I see. Thanks for the clarification. In general, I would like to get rid of unnecessary `sapply` calls.
I have seen that you have edited the respective line already, but I have two questions regarding your new implementation:

```R
names(nets.split) = if (is.null(names(nets.split))) ranges else names(nets.split)
```
(1) Doesn't this mean that your arguments from the previous comment is invalidated by your most recent change? Because now you assume that `ranges` always is in the correct format...
(2) Is it intended to replace the names by themselves if they are present? Why not just setting names if no names are present:
 ```R
if (is.null(names(nets.split)) { 
    names(nets.split) = ranges
} 
```
Anyway, we need to make sure that there are always the correct ranges added. So, could you please double-check if `ranges` always has the correct form in this case, and also that when names are present they also are in the correct form?

2024-12-09 13:02 UTC, bockthom commented on util-networks.R
> +            # }
Two questions regarding this change:
(1) Why did you do changes to the commented code? (`do.call(base::c` as well as `as.list(u.actual.edge.attribute.date)` are new). Is this necessary to make the commented code run with recent igraph versions, or did you just try something without reverting it?

(2) The comment above is outdated if we keep the code commented. "The following code block should be redundant as soon as igraph has fixed their bug" :right_arrow: "The following commented code block is redundant as of igraph version 2.1.1, in which igraph has fixed their bug." (or something similar)

2024-12-09 13:07 UTC, maxloeffler commented on util-networks.R
> +            # }
(1) The changes come from me experimenting with the fix before deciding that it must really be commented out all together to work with the new edge attributes. However, I did not yet delete it such that we can discuss here if we should try to make this whole changed edge attribute thing work with older `igraph` versions or if we can just drop support.

(2) That the comment is still there is just a symptom of (1).

2024-12-09 13:08 UTC, maxloeffler commented on util-split.R
> +    names(nets.split) = sapply(ranges.bounds, paste, collapse = "-")
Both conditions are covered by tests. That was the initial reason for why I needed to do a case distinction here.

2024-12-09 13:10 UTC, bockthom commented on util-split.R
> +    names(nets.split) = sapply(ranges.bounds, paste, collapse = "-")
But then I am waiting for an explanation why the tests did not fail with the "simpler" version proposed above that you consider to be faulty.

2024-12-09 13:14 UTC, bockthom commented on util-networks.R
> +            # }
It depends on (a) whether you already have a version of this code that already works with older `igraph` versions and on (b) how much time it would take to make it work if it is not working yet.

If it is already working and only two lines need to be changed, we can discuss whether we support older `igraph` versions. If it would take a couple of hours to experiment with this code until it works with older `igraph` versions, I would suggest to cease the support of older `igraph` versions.

2024-12-09 13:45 UTC, bockthom reviewed
While looking over the rest of this PR, I only found a couple of minor issues, please find the individual comments below.

Regarding the uncovered lines reported by codecov: I suggest to ignore them. 2 out of 4 missing lines are part of an untested module anyway. The other two lines refer to very special cases that have been previously untested too.

2024-12-09 13:45 UTC, bockthom commented on util-networks.R
> +        ## convert edge attributes to list similarely to 'convert.edge.attributes.to.list'
Could you please add a short reason why `convert.edge.attributes.to.list` cannot be used here? One line at max.
(and also fix the typo in "similarly" please)

2024-12-09 13:45 UTC, bockthom commented on util-split.R
> +    dates = do.call(base::c, igraph::edge_attr(network, "date"))
I am not sure if this change is correct. We still need to make sure that the date is in the correct format and not stored as a unix timestamp. I assume that the `do.call(base::c,` just makes the edge-attribute extraction work on lists, but it does not make sure that the timestamps are stored in the correct format.

(This also holds for the similar change in line 712 below).

2024-12-09 13:45 UTC, bockthom commented on tests/test-networks-equal-constructions.R
> +                         as.vector(edges.one[["date"]], "numeric"))
Could you please explain this change to me? I neither understand why the `is.vector` is needed here (how does this work with lists?), nor why the date should be `numeric` here? Maybe you can provide a very short example here (just here in the PR discussion)

2024-12-09 13:45 UTC, bockthom commented on util-networks.R
The commit that replaces the NULLs with NAs lacks a signed-off tag :wink:

2024-12-09 13:45 UTC, bockthom commented on tests/test-networks.R
> +patrick::with_parameters_test_that("Convert edge attributest to list", {
Typo: Even if this is a "test", attributes are not called "attributest" :wink:

2024-12-09 13:45 UTC, bockthom commented on tests/test-networks.R
> +        remain.as.is = names(EDGE.ATTR.HANDLING)
I also don't get this one. `Convert.edge.attributes.to.list` was already called beforehand.
And why is this an intersection? The actual edge attributes are not check for here.

2024-12-09 13:52 UTC, maxloeffler commented on util-split.R
> +    names(nets.split) = sapply(ranges.bounds, paste, collapse = "-")
I looked it up and the answer is quite more complex than I thought. 

So to refresh, `ranges` comes in two formats:

```R
## Format 1:
 chr [1:6] "<time-A>-<time-B>" "<time-C>-<time-D>" ...

## Format 2:
List of 2
 $ <time-A>-<time-B>: chr [1:2] "<time-A>" "<time-B>"
 $ <time-C>-<time-D>: chr [1:2] "<time-C>" "<time-D>"
```

In case 1: `ranges.bounds` is a `list(POSIXct)` with the bounds for each range.
In case 2: `ranges.bounds` is identical to `ranges`.

Therefore, in the loop over the range bounds, the `bounds` are sometimes of type `chr` and sometimes of type `POSIXct`. The `split.network.time.based` method tries to assign names to the splits already but only succeeds if the ranges are `chr` (in case 2).

So in case 1, the `split.network.time.based` method will not set names to the network splits, however in case 2 it does. The faulty version, therefore, worked since when the splits had not been assigned names yet (case 1), that means that `ranges` can be used right away as the names for the splits, while when the splits were already assigned names (case 2), that means that `ranges` has names and `names(ranges)` can be used again (although redundantly) to assign names.

2024-12-09 13:58 UTC, maxloeffler commented on util-split.R
> +    names(nets.split) = sapply(ranges.bounds, paste, collapse = "-")
That means that the names assignment can be simplified to 
```R
if (is.null(names(nets.split))) {
    names(nets.split) = ranges
}
```

2024-12-09 13:59 UTC, bockthom commented on util-split.R
> +    names(nets.split) = sapply(ranges.bounds, paste, collapse = "-")
I see. So, which version of the fix would you suggest to use eventually?

2024-12-09 14:00 UTC, bockthom commented on util-split.R
> +    names(nets.split) = sapply(ranges.bounds, paste, collapse = "-")
Agreed.

2024-12-09 14:12 UTC, maxloeffler commented on tests/test-networks.R
> +        remain.as.is = names(EDGE.ATTR.HANDLING)
Here, I set the `remain.as.is` value, so that I can later use it explicitly in the validation of edge attributes. 
The comment here is indeed outdated, previously I intersected `names(EDGE.ATTR.HANDLING)` and the attributes I use in this test, i.e., `edge.attributes` because it does not really matter whether I test edge attributes that I have not used at all or I don't. In the end I settled on not intersecting as it would not really portrait the default value of `convert.edge.attributes.to.list`, but forgot the remove the comment.

2024-12-09 14:22 UTC, bockthom commented on tests/test-networks.R
> +        remain.as.is = names(EDGE.ATTR.HANDLING)
Ok, then please adjust the comment, and I am fine with this.

2024-12-09 14:27 UTC, maxloeffler commented on tests/test-networks-equal-constructions.R
> +                         as.vector(edges.one[["date"]], "numeric"))
Why `as.vector`: Well, lists cannot be used in the `order` function, only vectors. Previously, we always had vectors here but now we have lists.

Why `"numeric"`: `as.vector` takes a second argument (`mode`). If we do not specify it, it is `"any"` and when using `"any"` it does not perform any conversion here, as `is.vector(list(...))` holds. If we specify `"numeric"` though, it converts the list to a vector of numerics. As we only use this vector for ordering the entries, it does not impact anything else.

2024-12-09 14:32 UTC, bockthom commented on tests/test-networks-equal-constructions.R
> +                         as.vector(edges.one[["date"]], "numeric"))
Thanks for the explanation, sounds good.

2024-12-09 14:32 UTC, maxloeffler commented on util-split.R
> +    dates = do.call(base::c, igraph::edge_attr(network, "date"))
You're right. Previously, the conversion was necessary to pass some tests I believe, now it is not anymore, so I thought it was only for that purpose.

2024-12-09 14:36 UTC, maxloeffler commented on util-networks.R
> +            # }
I don't have a working version for older `igraph` versions, but I will try to test a bit and see if it's feasible.

2024-12-09 15:06 UTC, maxloeffler commented on util-networks.R
> +            # }
After installing any `igraph` older version, I get errors because the `subgraph_from_edges` method (which I used to replace the deprecated `subgraph.edges` method) is not exported in these versions. Looking at the `rigraph` repo I found that the method has only been [exported recently](https://github.com/igraph/rigraph/commit/543cd9821d83b0a28fc0152eac8fb95eb54ee06d). I don't think would be good to still support older versions under this circumstance anyways.

2024-12-10 10:19 UTC, bockthom commented on util-networks.R
>          net = igraph::add_edges(net, unlist(vertex.sequence.for.edges), attr = extra.edge.attributes)
@maxloeffler Could you please report this `NULL` vs. `NA` problem to "rigraph" by replying to the issue that I have opened there a few weeks ago? Just a few sentences in which you relate to part (1), saying that the described problem not only applies to `disjoint_union`, but also to `add_edges`, should be enough, I guess.

(I don't mention the exact issue number here, as I don't want this entire PR be linked to the igraph issue)

2024-12-10 10:25 UTC, bockthom commented on util-networks.R
> +            # }
Indeed, `subgraph_from_edges` has been introduced recently. So, I guess, we should not support older igraph versions any more.
As we want to have a major release of coronet very soon, I guess it is ok to cease the support of older igraph versions. What we could think of is whether we want to provide a bug-fix branch for the previous release where we cherry-pick certain bug fixes to support older igraph versions - but I am not sure whether this is necessary and I am also not sure what's @hechtlC's opinion on that, so let's discuss this tomorrow in our meeting.

2024-12-16 22:25 UTC, bockthom requested changes
I've a few comments regarding the news. Please find them below.

2024-12-17 13:34 UTC, maxloeffler commented on NEWS.md
> +- Change the default representation of edge attributes from vectors to lists. This change is necessary for the interplay of coronet networks with certain igraph functionality since igraph version 2.1
How I see it is that coronet in itself is consistent. So every action you can perform with it should work just as it did before. While networks created with older coronet versions may not necessarily be compatible with networks created with this version, I don't know how this should ever happen, if not through serializing an old network and now deserializing it. Apart from that, there *should* be no incompatibilities.

2024-12-17 13:40 UTC, maxloeffler commented on NEWS.md
> +- Replace deprecated `igraph` functions by their preferred alternatives (PR #264, PR #268, PR #274 0df9d5bf6bafbb5d440f4c47db4ec901cf11f037, 7ac840d287a862eff61b1a84e194a4cba399f9e5, e3617b8c6b21fb42
Is that still the case if we deprecate support for `igraph` versions below 2.1? I should probably add that somewhere in the `NEWS.md` I just haven't found a good place for it.

2025-01-12 16:00 UTC, maxloeffler commented
Between the last and the second to last push I forgot to update the copyright headers of `util-networks.R` 😅.

2025-01-12 20:17 UTC, bockthom reviewed
I just found a few minor inconsistencies in the README, please find them below.
If also @hechtlC is fine with the new announcement, this PR is ready to be merged then.

2025-01-12 20:17 UTC, bockthom commented on NEWS.md
> +- **Breaking Change**: Change the default representation of edge attributes from vectors to lists. This change is necessary for the interplay of coronet networks with certain igraph functionality sin
Same as above, please use back ticks for `igraph` also here. And my be we should also use version 2.1.0 here, to be consistent with the announcement.

2025-01-12 20:17 UTC, bockthom commented on NEWS.md
> +- Adjust `metrics.scale.freeness` and `metrics.is.scale.free` functions be compatible with both older and newer igraph versions (PR #274, 4b0d5221dd56bb3c9ddf196f67719d4f503d9b61)
shouldn't it be "to be compatible with" instead of just "be compatible with" ?

2025-01-12 20:17 UTC, bockthom commented on NEWS.md
> +- Fix `read.commit.interactions` by explicitly considering non-existent commit interaction data (PR #274, f591528a0f1f11b1a4390949ab770f3f74a766f9)
Here it seems to me that you have only fixed the first part (replaced empty be non-existent), but this only makes sense if you also replace the following words as indicated in my previous review: commit interaction data :arrow_right: commit interactions.

(the commit interaction data are present, but no commit interactions are present).

2025-01-13 13:14 UTC, bockthom submitted a review, later dismissed

2025-01-14 15:23 UTC, bockthom approved these changes

2025-01-14 15:52 UTC, merged