Pullrequest
se-sic/coronet pull request #276
Opened 2024-12-11 13:54 UTC by Leo-Send

### Prerequisites

- [ X] I adhere to the coding conventions (described [here](../CONTRIBUTING.md)) in my code.
- [X ] I have updated the copyright headers of the files I have modified.
- [X ] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [ X] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](../NEWS.md) appropriately.
- [ ] I have checked whether I need to adjust the showcase file `showcase.R` with respect to my changes.
- [X ] The pull request is opened against the branch `dev`.

### Description

### Changelog

2024-12-13 16:05 UTC, bockthom requested changes
I had a quick look at the implementation (but not yet at the tests).
Please find my initial comments below.

2024-12-13 16:05 UTC, bockthom commented on util-core-peripheral.R
> +                                              restrict.classification.to.authors = NULL) {
Indentation wrong. (Also applies to some of the functions below.)

2024-12-13 16:05 UTC, bockthom commented on NEWS.md
> +- Add four new metric which can be used for the classification of authors into core and peripheral: Betweenness, Closeness, Pagerank and Eccentricity (PR #276, 65d5c9cc86708777ef458b0c2e744ab4b846bdd
metric :arrow_right: metrics
which :arrow_right: that
And there is no need to capitalize the metrics' names. But please put a comma before the final occurrence of "and".

2025-01-08 12:39 UTC, Leo-Send commented on util-core-peripheral.R
> +                                          centrality = as.vector(closeness.centrality.vec))
Intuitively, both "all" and "out" make sense to me, as they refer to how distance is measured within the graph, with "all" considering edges as undirected and "out" as directed. "in" would consider the edges as directed in the opposite direction.
In our context, I would probably use "all" as I believe it would lead to less isolated vertices.

2025-01-13 15:00 UTC, bockthom commented on README.md
> +    * closeness measures how close vertices are to each other by taking the inverse if the sum of all their shortest paths
if :arrow_right: of

and what is meant by "all their shortest paths"? Shortest paths to what? And what is the "inverse" in this case?

2025-01-13 15:03 UTC, bockthom commented on README.md
> +    * calculates scores based on the number of issues each created
each :arrow_right: each author

2025-01-13 15:04 UTC, bockthom commented on README.md
> +In this section, we provide descriptions of the different algorithms we provide for classifying authors into core or peripheral authors.
Could we split that into two subsections, namely count-based and network-based metrics? And I would put the count-based ones first as they are simpler and easier to understand.

2025-01-13 15:09 UTC, bockthom commented on README.md
> +Core/Peripheral classification descibes the process of dividing the authors of a project into either `core` or `peripheral` developers based on the principle that the core developers contribute 80% o
Hm, I am not sure whether we should put the 80/20 percent that prominently into our README. Coronet is flexible enough to also support other thresholds - either by using parameters or re-assigning the corresponding constant. This is why I would like to name the constant and omit the concrete numbers. It's the user's choice to set the value in accordance with their needs. If the constant is mentioned here, the user has the possibility to re-assign the needed value to this constant. However, we should say here what the default value is and why we 80/20 is the default threshold (just referring to literature in general, without citing a specific paper).

2025-01-13 15:13 UTC, bockthom commented on util-core-peripheral.R
> +        ## all entries with value zero are isolated vertices, so the value is already correct
Could you please add a period at the end of the first sentence - otherwise it is difficult to guess where the first sentence ends.
And what does it mean that "the value is already correct"? Instead of "correct" I would prefer another wording, maybe something like "the expected value" or something similar?

2025-01-13 15:15 UTC, bockthom commented on README.md
> +#### Core/Peripheral Classification
Please use upper-case characters in headings only at the beginning of the heading - this would be inconsistent with the other headings otherwise. (Not only here, but also in the table of contents.)

Independent of that, it is debatable whether the "P" should be upper- or lower-case. Not sure what would lead to highest consistency.

2025-01-14 17:02 UTC, bockthom requested changes
As I haven't had a look at the tests yet, I have now done so. I only have a few minor comments (but I did not check the actual centrality values; especially for eccentricity, I still don't have an impression whether the values do make sense or not :see_no_evil:)

In addition to my comments below, please don't forget about the changes to the README regarding "author networks" that we have agreed on in today's meeting.

2025-01-21 12:12 UTC, bockthom reviewed
Just two comments regarding wording:

2025-01-21 12:12 UTC, bockthom commented on README.md
> +In this section, we provide descriptions of the different algorithms we provide for classifying authors into core or peripheral authors using metrics that are used on author networks. Note that the p
Instead of `i.e. ...`, please use ` (e.g., an artifact network ...).`
And please don't use "importance", as this is already an interpretation of the metric. Just stick to "centrality" instead.

2025-01-21 12:12 UTC, bockthom commented on NEWS.md
> +- Add four new metric which can be used for the classification of authors into core and peripheral: Betweenness, Closeness, Pagerank and Eccentricity (PR #276, 65d5c9cc86708777ef458b0c2e744ab4b846bdd
Could you please replace "new metric which" by "new network metrics that".
And you don't need to have upper-case letters for the metrics names.
And please add a comma before "and eccentricity". Thanks!

2025-01-22 01:15 UTC, bockthom requested changes

2025-01-22 01:15 UTC, bockthom commented on util-core-peripheral.R
> +        ## almost never occur in all but the smallest networks.
Thanks for adding this comment. While I agree with the first sentence, I don't agree with the second sentence. Could you please rephrase the second sentence? First of all, I'd like to mention that we cannot distinguish between the case where the hierarchy should be low and the case where the hierarchy should be high, as we would need more information about the clusters that are not connected. And second, we should state that we assume that such a case where hierarchy is set to 0 although it should be high occurs only rarely. ("almost never" sounds incorrect, and also the information about "smallest networks" is irrelevant in my opinion.

2025-01-22 01:15 UTC, bockthom commented on NEWS.md
> +- Add four new metric that can be used for the classification of authors into core and peripheral: betweenness, closeness, pagerank, and eccentricity (PR #276, e27acb5ad7b4c4532e787d793301d06f13e8bbb
Did you remove one of the three previously mentioned commits on purpose or inadvertently? So, I agree with the two commits mentioned, and I don't know which one else to add, so I assume that there was one commit too much in the previous version and everything is fine now. I just wanted to double check that this is intended.

2025-01-24 15:26 UTC, Leo-Send commented on NEWS.md
> +- Add four new metric that can be used for the classification of authors into core and peripheral: betweenness, closeness, pagerank, and eccentricity (PR #276, e27acb5ad7b4c4532e787d793301d06f13e8bbb
It is indeed intended, previously I had another commit in there that only included tests.

2025-01-28 15:25 UTC, hechtlC requested changes
First of all thank you for the enhancement @Leo-Send!
I have just found some small typos and wording issues. Once these are fixed, we can merge this PR.

2025-01-28 15:25 UTC, hechtlC commented on NEWS.md
> +- Add four new metric that can be used for the classification of authors into core and peripheral: betweenness, closeness, pagerank, and eccentricity (PR #276, e27acb5ad7b4c4532e787d793301d06f13e8bbb
metrics

2025-01-28 15:25 UTC, hechtlC commented on util-core-peripheral.R
> +        ## all entries with value zero are isolated vertices, so the expected value is also zero.
If you use punctuation at the end of the sentences in these comments, then you need to start the sentence in upper case.

2025-01-28 15:25 UTC, hechtlC commented on util-core-peripheral.R
> +#' The details of the classification algorithm is explained in the documentation of \code{get.author.class.by.type}.
are explained
Also for the other functions

2025-01-28 15:25 UTC, hechtlC commented on README.md
> +Core/Peripheral classification descibes the process of dividing the authors of a project into either `core` or `peripheral` developers based on the principle that the core developers contribute most
describes
also two spaces after 80%

2025-01-29 12:43 UTC, hechtlC approved these changes

2025-01-29 13:34 UTC, merged